"""Type stubs for biocompiler.type_system — verdicts, predicates, and registry."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Dict, List, Optional, Set, Tuple

from .types import Verdict, TypeCheckResult
from .sliding_gc import SlidingGCResult, WindowViolation


# ────────────────────────────────────────────────────────────
# Enums
# ────────────────────────────────────────────────────────────

class CertLevel(Enum):
    GOLD: str
    SILVER: str
    BRONZE: str


class SpliceVerdict(Enum):
    PASS: auto()
    UNCERTAIN: auto()
    FAIL: auto()


# ────────────────────────────────────────────────────────────
# Data tables
# ────────────────────────────────────────────────────────────

CODON_TABLE: Dict[str, str]
AA_TO_CODONS: Dict[str, List[str]]
BLOSUM62: Dict[Tuple[str, str], int]
PREDICATE_NAMES: list[str]
PROMOTER_CONSENSUS: Dict[str, Dict[str, object]]


# ────────────────────────────────────────────────────────────
# Data classes
# ────────────────────────────────────────────────────────────

@dataclass
class PredicateResult:
    predicate: str
    passed: bool
    verdict: Optional[Verdict]
    details: str
    positions: List[int]
    verification_evidence: Optional[Dict[str, Any]]
    mutagenesis_applied: bool
    unavoidable_constraints: List[str]


# ────────────────────────────────────────────────────────────
# Low-level predicate checks
# ────────────────────────────────────────────────────────────

def check_no_stop_codons(seq: str) -> PredicateResult: ...
def check_no_cryptic_splice(seq: str, low_thresh: float = ..., high_thresh: float = ..., organism: str = ...) -> PredicateResult: ...
def check_no_cpg_island(seq: str, window: int = ..., threshold: float = ..., organism: str = ...) -> PredicateResult: ...
def check_no_restriction_site(seq: str, enzymes: List[str], min_site_length: int = ...) -> PredicateResult: ...
def check_no_gt_dinucleotide(seq: str) -> PredicateResult: ...
def check_no_avoidable_gt(seq: str, organism: str = ...) -> PredicateResult: ...
def check_no_gt_dinucleotide_soft(seq: str) -> PredicateResult: ...
def check_valid_coding_seq(seq: str) -> PredicateResult: ...
def check_conservation_score(seq: str, protein: str = ..., min_score: int = ...) -> PredicateResult: ...
def check_codon_optimality(seq: str, organism: str = ..., threshold: float = ...) -> PredicateResult: ...
def check_no_cryptic_promoter(seq: str, organism: str = ..., threshold: float = ...) -> PredicateResult: ...
def check_no_unexpected_tm_domain(seq: str, is_cytosolic: bool = ..., organism: str = ...) -> PredicateResult: ...
def check_mrna_secondary_structure(seq: str, organism: str = ...) -> PredicateResult: ...
def check_co_translational_folding(seq: str, organism: str = ..., domain_boundaries: list[tuple[int, int]] = ...) -> PredicateResult: ...
def check_mrna_stability(seq: str, organism: str = ...) -> PredicateResult: ...


# ────────────────────────────────────────────────────────────
# High-level evaluate API
# ────────────────────────────────────────────────────────────

def evaluate_gc_in_range(seq: str, gc_lo: float = ..., gc_hi: float = ...) -> TypeCheckResult: ...
def evaluate_no_cryptic_splice(seq: str, organism: str = ..., **kwargs: Any) -> TypeCheckResult: ...
def evaluate_splice_correct(seq: str, organism: str = ..., **kwargs: Any) -> TypeCheckResult: ...
def evaluate_codon_adapted(seq: str, organism: str = ..., threshold: float = ...) -> TypeCheckResult: ...
def evaluate_no_restriction_site(seq: str, enzymes: List[str] = ..., **kwargs: Any) -> TypeCheckResult: ...
def evaluate_in_frame(seq: str, **kwargs: Any) -> TypeCheckResult: ...
def evaluate_no_instability_motif(seq: str, **kwargs: Any) -> TypeCheckResult: ...
def evaluate_no_unexpected_tm_domain(seq: str, organism: str = ..., **kwargs: Any) -> TypeCheckResult: ...
def evaluate_mrna_secondary_structure(seq: str, organism: str = ..., **kwargs: Any) -> TypeCheckResult: ...
def evaluate_no_cryptic_promoter(seq: str, organism: str = ..., **kwargs: Any) -> TypeCheckResult: ...
def evaluate_no_cpg_island(seq: str, organism: str = ..., **kwargs: Any) -> TypeCheckResult: ...
def analyze_codon_at_position(seq: str, position: int, organism: str = ...) -> Dict[str, Any]: ...
def evaluate_co_translational_folding(seq: str, organism: str = ..., **kwargs: Any) -> TypeCheckResult: ...
def evaluate_all_predicates(seq: str, organism: str = ..., **kwargs: Any) -> List[TypeCheckResult]: ...
def evaluate_no_stop_codons(seq: str, **kwargs: Any) -> TypeCheckResult: ...
def evaluate_no_gt_dinucleotide(seq: str, organism: str = ..., **kwargs: Any) -> TypeCheckResult: ...
def evaluate_valid_coding_seq(seq: str, **kwargs: Any) -> TypeCheckResult: ...
def evaluate_conservation_score(seq: str, protein: str = ..., **kwargs: Any) -> TypeCheckResult: ...
def evaluate_codon_optimality(seq: str, organism: str = ..., **kwargs: Any) -> TypeCheckResult: ...
def evaluate_mrna_stability(seq: str, organism: str = ..., **kwargs: Any) -> TypeCheckResult: ...


# ────────────────────────────────────────────────────────────
# Sliding-window GC
# ────────────────────────────────────────────────────────────

def evaluate_sliding_gc(seq: str, window_size: int = ..., gc_min: float = ..., gc_max: float = ...) -> TypeCheckResult: ...


# ────────────────────────────────────────────────────────────
# Cross-codon helpers
# ────────────────────────────────────────────────────────────

def find_cross_codon_gt(seq: str) -> List[int]: ...
def find_cross_codon_cg(seq: str) -> List[int]: ...
def find_cross_codon_restriction(seq: str, enzymes: List[str]) -> List[int]: ...


# ────────────────────────────────────────────────────────────
# Organism-aware helpers
# ────────────────────────────────────────────────────────────

def _is_prokaryotic_organism(organism: str) -> bool: ...
def _compute_max_gt_count(protein_length: int, organism: str) -> int: ...


# ────────────────────────────────────────────────────────────
# Registry
# ────────────────────────────────────────────────────────────

class PredicateRegistry:
    def register(self, name: str, fn: Any, **kwargs: Any) -> None: ...
    def verify(self, name: str, **kwargs: Any) -> TypeCheckResult: ...
    def names(self) -> list[str]: ...

registry: PredicateRegistry
