"""
Tests for BioCompiler API authentication — default auth-on behavior.

Covers:
1. Auto-generated API key when BIOCOMPILER_API_KEY is not set
2. API key persistence to ~/.biocompiler/api_key
3. BIOCOMPILER_AUTH_MODE env var: "required" (default), "optional", "disabled"
4. HTTP 401 for unauthenticated requests in "required" mode
5. X-Auth-Warning response header in "optional" mode
6. BIOCOMPILER_API_KEY=disabled explicitly disables auth (with warning)
7. --no-auth CLI flag disables auth (with warning)
8. Health endpoint auth_enabled field reflects actual auth state
9. Valid API key grants access in all non-disabled modes
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest
from fastapi.testclient import TestClient


# ─── Helper: create app with specific env vars ──────────────────────

def _make_app_with_env(env_vars: dict[str, str], tmp_key_file: Path | None = None):
    """Create a FastAPI app with specific environment variable overrides.

    We patch os.environ before importing/reloading the api module to
    control the module-level auth configuration.
    """
    import importlib
    from biocompiler import api as api_module

    # Build a complete env dict
    env = dict(os.environ)
    # Remove any existing biocompiler auth vars
    for key in list(env.keys()):
        if key.startswith("BIOCOMPILER_API") or key == "BIOCOMPILER_AUTH_MODE":
            del env[key]
    # Apply test overrides
    env.update(env_vars)

    # Patch _get_api_key_file_path if a tmp_key_file is provided
    patches = [patch.dict(os.environ, env, clear=False)]

    if tmp_key_file is not None:
        patches.append(
            patch.object(api_module, "_get_api_key_file_path", return_value=tmp_key_file)
        )

    # We need to reload the module for the module-level code to re-execute
    # with the new env vars. But that's complex; instead, we directly
    # manipulate the module-level variables.
    return patches, api_module


class TestAutoGeneratedAPIKey:
    """Test that a random API key is generated when BIOCOMPILER_API_KEY is not set."""

    def test_auto_key_generated_when_no_env_var(self, tmp_path):
        """When BIOCOMPILER_API_KEY is not set, an auto-generated key should be created."""
        from biocompiler.api import _generate_and_persist_api_key, _get_api_key_file_path

        key_file = tmp_path / ".biocompiler" / "api_key"

        with patch("biocompiler.api._get_api_key_file_path", return_value=key_file):
            with patch.dict(os.environ, {}, clear=False):
                # Remove the env var if it exists
                os.environ.pop("BIOCOMPILER_API_KEY", None)
                key = _generate_and_persist_api_key()

        assert key is not None
        assert len(key) == 64  # 32 bytes = 64 hex chars
        assert key_file.exists()
        assert key_file.read_text().strip() == key

    def test_auto_key_persisted_and_reused(self, tmp_path):
        """The auto-generated key should be reused on subsequent startups."""
        from biocompiler.api import _generate_and_persist_api_key

        key_file = tmp_path / ".biocompiler" / "api_key"

        with patch("biocompiler.api._get_api_key_file_path", return_value=key_file):
            key1 = _generate_and_persist_api_key()
            key2 = _generate_and_persist_api_key()

        assert key1 == key2

    def test_auto_key_file_permissions(self, tmp_path):
        """The persisted key file should have restrictive permissions (0o600)."""
        from biocompiler.api import _generate_and_persist_api_key

        key_file = tmp_path / ".biocompiler" / "api_key"

        with patch("biocompiler.api._get_api_key_file_path", return_value=key_file):
            _generate_and_persist_api_key()

        # On some systems chmod may not work (e.g. Windows), so just check the file exists
        assert key_file.exists()
        # On Unix, check permissions
        if os.name == "posix":
            stat_info = key_file.stat()
            mode = stat_info.st_mode & 0o777
            assert mode == 0o600

    def test_auto_key_is_hex_string(self, tmp_path):
        """The auto-generated key should be a valid hex string."""
        from biocompiler.api import _generate_and_persist_api_key

        key_file = tmp_path / ".biocompiler" / "api_key"

        with patch("biocompiler.api._get_api_key_file_path", return_value=key_file):
            key = _generate_and_persist_api_key()

        # Should be valid hex
        int(key, 16)  # Raises ValueError if not hex


class TestAuthModeRequired:
    """Test BIOCOMPILER_AUTH_MODE=required (default)."""

    def test_required_mode_returns_401_without_key(self):
        """In required mode, unauthenticated requests should get 401."""
        from biocompiler import api as api_module

        # Save and restore state
        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "required"
            api_module._CONFIGURED_API_KEYS = {"test-secret-key-12345"}

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.get("/health")  # Health doesn't require auth
            assert resp.status_code == 200

            resp = client.post("/check", json={"sequence": "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"})
            assert resp.status_code == 401
            assert "API key" in resp.json()["detail"]
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys

    def test_required_mode_allows_with_valid_key(self):
        """In required mode, requests with a valid API key should succeed."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "required"
            api_module._CONFIGURED_API_KEYS = {"test-secret-key-12345"}

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.post(
                "/check",
                json={"sequence": "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"},
                headers={"X-API-Key": "test-secret-key-12345"},
            )
            assert resp.status_code == 200
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys

    def test_required_mode_rejects_invalid_key(self):
        """In required mode, an invalid API key should result in 401."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "required"
            api_module._CONFIGURED_API_KEYS = {"test-secret-key-12345"}

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.post(
                "/check",
                json={"sequence": "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"},
                headers={"X-API-Key": "wrong-key"},
            )
            assert resp.status_code == 401
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys


class TestAuthModeOptional:
    """Test BIOCOMPILER_AUTH_MODE=optional."""

    def test_optional_mode_allows_without_key(self):
        """In optional mode, unauthenticated requests should succeed."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "optional"
            api_module._CONFIGURED_API_KEYS = {"test-secret-key-12345"}

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.post("/check", json={"sequence": "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"})
            assert resp.status_code == 200
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys

    def test_optional_mode_adds_warning_header(self):
        """In optional mode, unauthenticated requests should get an X-Auth-Warning header."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "optional"
            api_module._CONFIGURED_API_KEYS = {"test-secret-key-12345"}

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.post("/check", json={"sequence": "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"})
            assert resp.status_code == 200
            assert "X-Auth-Warning" in resp.headers
            assert "optional" in resp.headers["X-Auth-Warning"].lower() or "recommended" in resp.headers["X-Auth-Warning"].lower()
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys

    def test_optional_mode_no_warning_with_valid_key(self):
        """In optional mode, authenticated requests should NOT get a warning header."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "optional"
            api_module._CONFIGURED_API_KEYS = {"test-secret-key-12345"}

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.post(
                "/check",
                json={"sequence": "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"},
                headers={"X-API-Key": "test-secret-key-12345"},
            )
            assert resp.status_code == 200
            # Warning header should NOT be present for authenticated requests
            assert "X-Auth-Warning" not in resp.headers
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys


class TestAuthModeDisabled:
    """Test BIOCOMPILER_AUTH_MODE=disabled."""

    def test_disabled_mode_allows_without_key(self):
        """In disabled mode, unauthenticated requests should succeed."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "disabled"
            api_module._CONFIGURED_API_KEYS = set()

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.post("/check", json={"sequence": "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"})
            assert resp.status_code == 200
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys

    def test_disabled_mode_no_warning_header(self):
        """In disabled mode, no X-Auth-Warning header should be added."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "disabled"
            api_module._CONFIGURED_API_KEYS = set()

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.post("/check", json={"sequence": "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"})
            assert resp.status_code == 200
            assert "X-Auth-Warning" not in resp.headers
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys


class TestAPIKeyDisabled:
    """Test BIOCOMPILER_API_KEY=disabled explicitly disables auth."""

    def test_api_key_disabled_env(self):
        """Setting BIOCOMPILER_API_KEY=disabled should disable auth with a warning."""
        from biocompiler.api import set_no_auth_flag

        # We test the set_no_auth_flag directly (used by CLI --no-auth)
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)
        original_cli_flag = api_module._NO_AUTH_CLI_FLAG

        try:
            api_module._AUTH_MODE = "required"
            api_module._CONFIGURED_API_KEYS = {"some-key"}
            api_module._NO_AUTH_CLI_FLAG = False

            set_no_auth_flag()

            assert api_module._AUTH_MODE == "disabled"
            assert api_module._NO_AUTH_CLI_FLAG is True
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys
            api_module._NO_AUTH_CLI_FLAG = original_cli_flag


class TestNoAuthCLIFlag:
    """Test --no-auth CLI flag behavior."""

    def test_set_no_auth_flag_disables_auth(self):
        """Calling set_no_auth_flag should set auth mode to disabled."""
        from biocompiler import api as api_module
        from biocompiler.api import set_no_auth_flag

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)
        original_cli_flag = api_module._NO_AUTH_CLI_FLAG

        try:
            api_module._AUTH_MODE = "required"
            api_module._CONFIGURED_API_KEYS = {"some-key"}
            api_module._NO_AUTH_CLI_FLAG = False

            set_no_auth_flag()

            assert api_module._AUTH_MODE == "disabled"
            assert api_module._NO_AUTH_CLI_FLAG is True
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys
            api_module._NO_AUTH_CLI_FLAG = original_cli_flag


class TestHealthEndpointAuthStatus:
    """Test that /health endpoint correctly reports auth state."""

    def test_health_auth_enabled_when_keys_set(self):
        """Health endpoint should report auth_enabled=True when keys are configured."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "required"
            api_module._CONFIGURED_API_KEYS = {"test-secret-key-12345"}

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.get("/health")
            data = resp.json()
            assert data["auth_enabled"] is True
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys

    def test_health_auth_disabled_when_no_keys(self):
        """Health endpoint should report auth_enabled=False when auth is disabled."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "disabled"
            api_module._CONFIGURED_API_KEYS = set()

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.get("/health")
            data = resp.json()
            assert data["auth_enabled"] is False
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys

    def test_health_auth_enabled_in_optional_mode(self):
        """Health endpoint should report auth_enabled=True in optional mode with keys."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "optional"
            api_module._CONFIGURED_API_KEYS = {"test-secret-key-12345"}

            app = api_module.create_app()
            client = TestClient(app)

            resp = client.get("/health")
            data = resp.json()
            assert data["auth_enabled"] is True
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys


class TestMultipleAPIKeys:
    """Test that multiple API keys work correctly."""

    def test_multiple_keys_all_accepted(self):
        """All keys in BIOCOMPILER_API_KEYS should be accepted."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "required"
            api_module._CONFIGURED_API_KEYS = {"key-alpha", "key-beta", "key-gamma"}

            app = api_module.create_app()
            client = TestClient(app)

            for key in ["key-alpha", "key-beta", "key-gamma"]:
                resp = client.post(
                    "/check",
                    json={"sequence": "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"},
                    headers={"X-API-Key": key},
                )
                assert resp.status_code == 200, f"Key {key!r} should be accepted"
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys

    def test_key_rotation_scenario(self):
        """Old and new keys should both work during rotation."""
        from biocompiler import api as api_module

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "required"
            api_module._CONFIGURED_API_KEYS = {"old-key-to-deprecate", "new-key-rotation"}

            app = api_module.create_app()
            client = TestClient(app)

            # Both keys should work
            for key in ["old-key-to-deprecate", "new-key-rotation"]:
                resp = client.post(
                    "/check",
                    json={"sequence": "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"},
                    headers={"X-API-Key": key},
                )
                assert resp.status_code == 200
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys


class TestPublicKeyFunctions:
    """Test the public helper functions for auth state inspection."""

    def test_get_auth_mode(self):
        """get_auth_mode should return the current auth mode string."""
        from biocompiler import api as api_module
        from biocompiler.api import get_auth_mode

        original = api_module._AUTH_MODE
        try:
            api_module._AUTH_MODE = "required"
            assert get_auth_mode() == "required"

            api_module._AUTH_MODE = "optional"
            assert get_auth_mode() == "optional"

            api_module._AUTH_MODE = "disabled"
            assert get_auth_mode() == "disabled"
        finally:
            api_module._AUTH_MODE = original

    def test_is_auth_enabled(self):
        """is_auth_enabled should return True only when auth is active."""
        from biocompiler import api as api_module
        from biocompiler.api import is_auth_enabled

        original_mode = api_module._AUTH_MODE
        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._AUTH_MODE = "required"
            api_module._CONFIGURED_API_KEYS = {"some-key"}
            assert is_auth_enabled() is True

            api_module._AUTH_MODE = "disabled"
            api_module._CONFIGURED_API_KEYS = set()
            assert is_auth_enabled() is False

            api_module._AUTH_MODE = "optional"
            api_module._CONFIGURED_API_KEYS = {"some-key"}
            assert is_auth_enabled() is True

            # Optional mode with no keys = not really enabled
            api_module._AUTH_MODE = "optional"
            api_module._CONFIGURED_API_KEYS = set()
            assert is_auth_enabled() is False
        finally:
            api_module._AUTH_MODE = original_mode
            api_module._CONFIGURED_API_KEYS = original_keys

    def test_get_configured_api_keys(self):
        """get_configured_api_keys should return a copy of the keys set."""
        from biocompiler import api as api_module
        from biocompiler.api import get_configured_api_keys

        original_keys = set(api_module._CONFIGURED_API_KEYS)

        try:
            api_module._CONFIGURED_API_KEYS = {"key1", "key2"}
            keys = get_configured_api_keys()
            assert keys == {"key1", "key2"}
            # Should be a copy, not the original set
            keys.add("key3")
            assert "key3" not in api_module._CONFIGURED_API_KEYS
        finally:
            api_module._CONFIGURED_API_KEYS = original_keys


class TestDefaultAuthIsEnabled:
    """Test that auth is enabled by default (the core security fix)."""

    def test_auth_is_not_disabled_by_default(self):
        """By default (no env vars), auth should NOT be in disabled mode."""
        from biocompiler.api import get_auth_mode

        # The default auth mode should be "required"
        # (unless overridden by env vars in the test environment)
        mode = get_auth_mode()
        assert mode in ("required", "optional", "disabled")
        # In the test environment, the actual mode depends on env vars,
        # but the DEFAULT when no env is set should be "required"

    def test_auto_key_makes_auth_enabled(self, tmp_path):
        """When no BIOCOMPILER_API_KEY is set, the auto-generated key should enable auth."""
        from biocompiler.api import _generate_and_persist_api_key

        key_file = tmp_path / ".biocompiler" / "api_key"

        with patch("biocompiler.api._get_api_key_file_path", return_value=key_file):
            key = _generate_and_persist_api_key()

        # If keys are configured and mode is not disabled, auth is enabled
        assert len(key) > 0

    def test_no_env_var_means_auto_generated_key(self):
        """Without BIOCOMPILER_API_KEY env var, the module should have auto-generated keys."""
        from biocompiler import api as api_module
        from biocompiler.api import get_configured_api_keys

        # In the test environment, we can't guarantee the state of env vars,
        # but we can verify that when keys are configured, they're non-empty
        keys = get_configured_api_keys()
        # Either the user set BIOCOMPILER_API_KEY or an auto-key was generated
        # The important thing is that auth is NOT simply disabled
        if api_module._AUTH_MODE != "disabled":
            assert len(keys) > 0, "Auth mode is not disabled but no keys are configured"
