"""
Type stubs for biocompiler.optimizer.cai — CAI computation and batch scoring.
"""

from typing import Any, Dict, List

import numpy as _np

HAS_NUMBA: bool
_HAS_NUMBA: bool

def _adaptiveness_to_array(codon_adaptiveness: dict[str, float]) -> _np.ndarray: ...
def _codon_to_index(codon: str) -> int: ...
def _dna_to_codon_indices(dna: str) -> _np.ndarray: ...
def _compute_cai_fast(seq: str, codon_adaptiveness: dict[str, float]) -> float: ...
def _count_dinucs_fast(seq: str, *dinucleotides: str) -> tuple[int, ...]: ...

class _BatchSwapScorer:
    def __init__(self, species_cai: Dict[str, float]) -> None: ...
    def _ensure_numpy(self) -> None: ...
    def _build_codon_indices(self, seq_codons: List[str]) -> Any: ...
    def _compute_log_sum(self, seq_codons: List[str]) -> float: ...
    def reset_incremental_state(self, seq_codons: List[str]) -> None: ...
    def update_incremental_state(self, old_codon: str, new_codon: str) -> None: ...
    @property
    def current_log_sum(self) -> float | None: ...
    def score_candidates(
        self,
        seq_codons: List[str],
        swap_position: int,
        candidate_codons: List[str],
    ) -> List[float]: ...

__all__: list[str]
