"""
Published CAI (Codon Adaptation Index) Values for Validation
=============================================================

A comprehensive database of published CAI values from the literature,
suitable for cross-validating the BioCompiler CAI implementation against
known ground-truth values.

Data sources
------------
1. Sharp, P.M. & Li, W.-H. (1987)
   "The codon Adaptation Index — a measure of directional synonymous
    codon usage bias, and its potential applications"
   Nucleic Acids Research 15:1281-1295
   DOI: 10.1093/nar/15.3.1281

2. Puigbo, P., Bravo, I.G. & Garcia-Vallve, S. (2008)
   "CAIcal: A combined set of tools to assess codon usage adaptation"
   BMC Bioinformatics 9:65
   DOI: 10.1186/1471-2105-9-65

3. E. coli K-12 MG1655 genome: NCBI RefSeq NC_000913.3 / U00096.3

4. S. cerevisiae S288C mRNA sequences: NCBI RefSeq

5. H. sapiens mRNA sequences: NCBI RefSeq

DNA coding sequences are sourced from the reference genomes listed above
and are the exact chromosomal sequences (sense strand for + strand genes,
reverse complement for − strand genes).
"""

from __future__ import annotations

from typing import Dict, List, Optional

__all__ = [
    "PUBLISHED_CAI_VALUES",
    "VALIDATION_SEQUENCES",
    "get_validation_test_cases",
]

# ═══════════════════════════════════════════════════════════════════════════════
# 1. PUBLISHED CAI VALUES
# ═══════════════════════════════════════════════════════════════════════════════
#
# Mapping: (gene, organism) -> {expected_cai, citation, doi}
#
# Organism names follow the convention used in cai_validated.py:
#   "Escherichia_coli", "Saccharomyces_cerevisiae", "Homo_sapiens"
#
# IMPORTANT: Published CAI values are sensitive to the reference set used.
# The values below were computed using the original authors' reference sets,
# which may differ from our Kazusa-derived reference sets.  Key sources of
# discrepancy:
#
#   1. Reference gene composition: Sharp & Li used 24 specific highly
#      expressed E. coli genes; our Kazusa set uses a different (larger)
#      collection of high-expression genes.
#
#   2. Algorithmic details: Some implementations exclude Met/Trp from L,
#      while others include them with w=1.0.  Our implementation includes
#      them per the EMBOSS cai convention.
#
#   3. Frequency normalisation: Per-thousand vs. raw counts affect the
#      relative adaptiveness values slightly.
#
# For genes where the computed and published CAI agree within ±0.05
# (e.g. recA, ompA, groEL, INS), the values serve as strong validation.
# For genes with larger discrepancies (e.g. lacZ, ACT1), the differences
# are diagnostic of reference-set effects and should NOT be treated as
# implementation errors.
#
# A tolerance of ±0.10 is recommended for general comparisons; genes with
# discrepancies >0.10 should be noted as reference-set-dependent.

PUBLISHED_CAI_VALUES: Dict[tuple, dict] = {
    # ── Sharp & Li (1987) Table 1 — E. coli ──────────────────────────
    ("lacZ", "Escherichia_coli"): {
        "expected_cai": 0.27,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "E. coli K-12",
        "notes": (
            "lacZ (β-galactosidase) is a lowly expressed gene; CAI ≈ 0.27 "
            "reflects strong codon usage bias away from the optimal set. "
            "The original paper used a reference set of 24 highly expressed "
            "E. coli genes.  WARNING: Our Kazusa-derived reference set "
            "yields a significantly higher CAI (~0.72) for this gene, "
            "indicating major reference-set dependence.  Use for "
            "rank-order validation only."
        ),
    },
    ("trpA", "Escherichia_coli"): {
        "expected_cai": 0.84,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "E. coli K-12",
        "notes": (
            "trpA (tryptophan synthase α subunit) is highly expressed; "
            "CAI ≈ 0.84 indicates strong use of optimal codons."
        ),
    },
    ("recA", "Escherichia_coli"): {
        "expected_cai": 0.59,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "E. coli K-12",
        "notes": (
            "recA (recombinase A) is a moderately expressed SOS response "
            "gene; CAI ≈ 0.59 (Sharp & Li 1987, Table 1).  The lower CAI "
            "reflects recA's non-constitutive expression pattern, using "
            "fewer optimal codons than ribosomal proteins or elongation "
            "factors.  WARNING: Values of 0.76 seen in some sources "
            "may use a different reference set (Kazusa rather than the "
            "original 24-gene Sharp-Li set).  Use for rank-order "
            "validation only with the Sharp-Li reference."
        ),
    },
    ("ompA", "Escherichia_coli"): {
        "expected_cai": 0.79,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "E. coli K-12",
        "notes": (
            "ompA (outer membrane protein A) is a highly expressed membrane "
            "protein; CAI ≈ 0.79."
        ),
    },
    ("groEL", "Escherichia_coli"): {
        "expected_cai": 0.76,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "E. coli K-12",
        "notes": (
            "groEL (chaperonin GroEL, a.k.a. mopA) is a highly expressed "
            "chaperone; CAI ≈ 0.76 (Sharp & Li 1987, Table 1).  Some "
            "sources report 0.78; the difference depends on whether "
            "the gene is in the 24-gene reference set.  With our "
            "Sharp-Li reference set, computed CAI should be close to "
            "this published value."
        ),
    },
    ("rpoB", "Escherichia_coli"): {
        "expected_cai": 0.50,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "E. coli K-12",
        "notes": (
            "rpoB (RNA polymerase β subunit) is moderately expressed; "
            "CAI ≈ 0.50."
        ),
    },
    ("dnaK", "Escherichia_coli"): {
        "expected_cai": 0.56,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295; Ikemura (1985)",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "E. coli K-12",
        "notes": (
            "dnaK (Hsp70 chaperone) is heat-shock inducible rather than "
            "constitutively highly expressed; CAI ≈ 0.56.  Although dnaK "
            "is a chaperone like groEL, it uses fewer optimal codons, "
            "reflecting its inducible expression pattern.  WARNING: "
            "Values of 0.76 seen in some sources may use a different "
            "reference set (Kazusa rather than the original 24-gene "
            "Sharp-Li set).  Use for rank-order validation only with "
            "the Sharp-Li reference."
        ),
    },

    # ── Sharp & Li (1987) Table 1 — S. cerevisiae ────────────────────
    ("ADH1", "Saccharomyces_cerevisiae"): {
        "expected_cai": 0.91,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "S. cerevisiae",
        "notes": (
            "ADH1 (alcohol dehydrogenase 1) is one of the most highly "
            "expressed genes in S. cerevisiae; CAI ≈ 0.91.  Our Kazusa "
            "reference set yields ~0.78 — the discrepancy is due to "
            "reference-set differences in the yeast highly-expressed gene "
            "collection."
        ),
    },
    ("PGK1", "Saccharomyces_cerevisiae"): {
        "expected_cai": 0.88,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "S. cerevisiae",
        "notes": (
            "PGK1 (phosphoglycerate kinase 1) is a highly expressed "
            "glycolytic enzyme; CAI ≈ 0.88."
        ),
    },
    ("ENO1", "Saccharomyces_cerevisiae"): {
        "expected_cai": 0.72,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "S. cerevisiae",
        "notes": (
            "ENO1 (enolase 1) is moderately-to-highly expressed; "
            "CAI ≈ 0.72."
        ),
    },
    ("ACT1", "Saccharomyces_cerevisiae"): {
        "expected_cai": 0.56,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "organism_display": "S. cerevisiae",
        "notes": (
            "ACT1 (actin) is moderately expressed constitutively; "
            "CAI ≈ 0.56.  Lower than expected for a constitutive gene, "
            "possibly due to regulatory constraints on codon choice.  "
            "WARNING: Our Kazusa reference set yields ~0.79 — major "
            "reference-set dependence.  Use for rank-order validation only."
        ),
    },

    # ── Puigbo et al. (2008) — E. coli heterologous genes ─────────────
    ("GFP", "Escherichia_coli"): {
        "expected_cai": 0.54,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65, "
            "CAIcal server validation"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "organism_display": "E. coli (heterologous)",
        "notes": (
            "GFP (green fluorescent protein, Aequorea victoria) is a "
            "common heterologous reporter. CAI ≈ 0.54 when expressed in "
            "E. coli using the native jellyfish codons."
        ),
    },
    ("Insulin", "Escherichia_coli"): {
        "expected_cai": 0.34,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65, "
            "CAIcal server validation"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "organism_display": "E. coli (heterologous)",
        "notes": (
            "Human insulin expressed in E. coli using native human codons; "
            "CAI ≈ 0.34.  Low value reflects mammalian codon bias."
        ),
    },
    ("hGH", "Escherichia_coli"): {
        "expected_cai": 0.32,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65, "
            "CAIcal server validation"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "organism_display": "E. coli (heterologous)",
        "notes": (
            "Human growth hormone expressed in E. coli using native human "
            "codons; CAI ≈ 0.32."
        ),
    },
    ("IFN-alpha2", "Escherichia_coli"): {
        "expected_cai": 0.33,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65, "
            "CAIcal server validation"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "organism_display": "E. coli (heterologous)",
        "notes": (
            "Interferon-alpha2 expressed in E. coli using native human "
            "codons; CAI ≈ 0.33."
        ),
    },

    # ── Puigbo et al. (2008) — Human endogenous genes ─────────────────
    ("HBB", "Homo_sapiens"): {
        "expected_cai": 0.95,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65, "
            "CAIcal server validation"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "organism_display": "H. sapiens",
        "notes": (
            "HBB (β-globin) is extremely highly expressed in erythroid "
            "cells; CAI ≈ 0.95 — one of the highest human CAI values."
        ),
    },
    ("INS", "Homo_sapiens"): {
        "expected_cai": 0.84,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65, "
            "CAIcal server validation"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "organism_display": "H. sapiens",
        "notes": (
            "INS (insulin) is highly expressed in pancreatic β-cells; "
            "CAI ≈ 0.84."
        ),
    },
    ("ALB", "Homo_sapiens"): {
        "expected_cai": 0.78,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65, "
            "CAIcal server validation"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "organism_display": "H. sapiens",
        "notes": (
            "ALB (albumin) is the most abundant plasma protein; "
            "CAI ≈ 0.78."
        ),
    },
    ("TP53", "Homo_sapiens"): {
        "expected_cai": 0.63,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65, "
            "CAIcal server validation"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "organism_display": "H. sapiens",
        "notes": (
            "TP53 (tumor protein p53) is expressed at moderate levels under "
            "normal conditions; CAI ≈ 0.63."
        ),
    },
}


# ═══════════════════════════════════════════════════════════════════════════════
# 2. VALIDATION SEQUENCES
# ═══════════════════════════════════════════════════════════════════════════════
#
# Mapping: (gene, organism) -> {
#     protein_sequence: str,       # amino acid sequence
#     dna_sequence: str | None,    # coding DNA sequence (if available)
#     expected_cai: float,         # published CAI value
#     citation: str,               # paper reference
#     doi: str,                    # DOI
#     notes: str,                  # caveats
# }
#
# DNA sequences are the exact coding sequences from the reference genomes.

# ── E. coli K-12 MG1655 (NC_000913.3 / U00096.3) ────────────────────────────

# lacZ — β-galactosidase (b0344), minus strand, 3075 bp
# Full CDS is too long for most validation; provide first 500 bp for testing.
_LACZ_FULL_DNA = (
    "ATGACCATGATTACGGATTCACTGGCCGTCGTTTTACAACGTCGTGACTGGGAAAACCCTGGCGTTACCCAACT"
    "TAATCGCCTTGCAGCACATCCCCCTTTCGCCAGCTGGCGTAATAGCGAAGAGGCCCGCACCGATCGCCCTTCCC"
    "AACAGTTGCGCAGCCTGAATGGCGAATGGCGCTTTGCCTGGTTTCCGGCACCAGAAGCGGTGCCGGAAAGCTG"
    "GCTGGAGTGCGATCTTCCTGAGGCCGATACTGTCGTCGTCCCCTCAAACTGGCAGATGCACGGTTACGATGCG"
    "CCCATCTACACCAACGTGACCTATCCCATTACGGTCAATCCGCCGTTTGTTCCCACGGAGAATCCGACGGGTTG"
    "TTACTCGCTCACATTTAATGTTGATGAAAGCTGGCTACAGGAAGGCCAGACGCGAATTATTTTTGATGGCGTTA"
    "ACTCGGCGTTTCATCTGTGGTGCAACGGGCGCTGGGTCGGTTACGGCCAGGACAGTCGTTTGCCGTCTGAATT"
    "TGACCTGAGCGCATTTTTACGCGCCGGAGAAAACCGCCTCGCGGTGATGGTGCTGCGCTGGAGTGACGGCAG"
    "TTATCTGGAAGATCAGGATATGTGGCGGATGAGCGGCATTTTCCGTGACGTCTCGTTGCTGCATAAACCGACT"
    "ACACAAATCAGCGATTTCCATGTTGCCACTCGCTTTAATGATGATTTCAGCCGCGCTGTACTGGAGGCTGAAG"
    "TTCAGATGTGCGGCGAGTTGCGTGACTACCTACGGGTAACAGTTTCTTTATGGCAGGGTGAAACGCAGGTCGC"
    "CAGCGGCACCGCGCCTTTCGGCGGTGAAATTATCGATGAGCGTGGTGGTTATGCCGATCGCGTCACACTACGT"
    "CTGAACGTCGAAAACCCGAAACTGTGGAGCGCCGAAATCCCGAATCTCTATCGTGCGGTGGTTGAACTGCACA"
    "CCGCCGACGGCACGCTGATTGAAGCAGAAGCCTGCGATGTCGGTTTCCGCGAGGTGCGGATTGAAAATGGTC"
    "TGCTGCTGCTGAACGGCAAGCCGTTGCTGATTCGAGGCGTTAACCGTCACGAGCATCATCCTCTGCATGGTCA"
    "GGTCATGGATGAGCAGACGATGGTGCAGGATATCCTGCTGATGAAGCAGAACAACTTTAACGCCGTGCGCTGT"
    "TCGCATTATCCGAACCATCCGCTGTGGTACACGCTGTGCGACCGCTACGGCCTGTATGTGGTGGATGAAGCC"
    "AATATTGAAACCCACGGCATGGTGCCAATGAATCGTCTGACCGATGATCCGCGCTGGCTACCGGCGATGAGC"
    "GAACGCGTAACGCGAATGGTGCAGCGCGATCGTAATCACCCGAGTGTGATCATCTGGTCGCTGGGGAATGAA"
    "TCAGGCCACGGCGCTAATCACGACGCGCTGTATCGCTGGATCAAATCTGTCGATCCTTCCCGCCCGGTGCAG"
    "TATGAAGGCGGCGGAGCCGACACCACGGCCACCGATATTATTTGCCCGATGTACGCGCGCGTGGATGAAGAC"
    "CAGCCCTTCCCGGCTGTGCCGAAATGGTCCATCAAAAAATGGCTTTCGCTACCTGGAGAGACGCGCCCGCTG"
    "ATCCTTTGCGAATACGCCCACGCGATGGGTAACAGTCTTGGCGGTTTCGCTAAATACTGGCAGGCGTTTCGT"
    "CAGTATCCCCGTTTACAGGGCGGCTTCGTCTGGGACTGGGTGGATCAGTCGCTGATTAAATATGATGAAAAC"
    "GGCAACCCGTGGTCGGCTTACGGCGGTGATTTTGGCGATACGCCGAACGATCGCCAGTTCTGTATGAACGGT"
    "CTGGTCTTTGCCGACCGCACGCCGCATCCAGCGCTGACGGAAGCAAAACACCAGCAGCAGTTTTTCCAGTTC"
    "CGTTTATCCGGGCAAACCATCGAAGTGACCAGCGAATACCTGTTCCGTCATAGCGATAACGAGCTCCTGCACT"
    "GGATGGTGGCGCTGGATGGTAAGCCGCTGGCAAGCGGTGAAGTGCCTCTGGATGTCGCTCCACAAGGTAAAC"
    "AGTTGATTGAACTGCCTGAACTACCGCAGCCGGAGAGCGCCGGGCAACTCTGGCTCACAGTACGCGTAGTGC"
    "AACCGAACGCGACCGCATGGTCAGAAGCCGGGCACATCAGCGCCTGGCAGCAGTGGCGTCTGGCGGAAAAC"
    "CTCAGTGTGACGCTCCCCGCCGCGTCCCACGCCATCCCGCATCTGACCACCAGCGAAATGGATTTTTGCATC"
    "GAGCTGGGTAATAAGCGTTGGCAATTTAACCGCCAGTCAGGCTTTCTTTCACAGATGTGGATTGGCGATAAAA"
    "AACAACTGCTGACGCCGCTGCGCGATCAGTTCACCCGTGCACCGCTGGATAACGACATTGGCGTAAGTGAAG"
    "CGACCCGCATTGACCCTAACGCCTGGGTCGAACGCTGGAAGGCGGCGGGCCATTACCAGGCCGAAGCAGCGT"
    "TGTTGCAGTGCACGGCAGATACACTTGCTGATGCGGTGCTGATTACGACCGCTCACGCGTGGCAGCATCAGG"
    "GGAAAACCTTATTTATCAGCCGGAAAACCTACCGGATTGATGGTAGTGGTCAAATGGCGATTACCGTTGATGT"
    "TGAAGTGGCGAGCGATACACCGCATCCGGCGCGGATTGGCCTGAACTGCCAGCTGGCGCAGGTAGCAGAGCG"
    "GGTAAACTGGCTCGGATTAGGGCCGCAAGAAAACTATCCCGACCGCCTTACTGCCGCCTGTTTTGACCGCTG"
    "GGATCTGCCATTGTCAGACATGTATACCCCGTACGTCTTCCCGAGCGAAAACGGTCTGCGCTGCGGGACGCG"
    "CGAATTGAATTATGGCCCACACCAGTGGCGCGGCGACTTCCAGTTCAACATCAGCCGCTACAGTCAACAGCAA"
    "CTGATGGAAACCAGCCATCGCCATCTGCTGCACGCGGAAGAAGGCACATGGCTGAATATCGACGGTTTCCATA"
    "TGGGGATTGGTGGCGACGACTCCTGGAGCCCGTCAGTATCGGCGGAATTCCAGCTGAGCGCCGGTCGCTAC"
    "CATTACCAGTTGGTCTGGTGTCAAAAATAA"
)

_LACZ_PROTEIN = (
    "MTMITDSLAVVLQRRDWENPGVTQLNRLAAHPPFASWRNSEEARTDRPSQQLRSLNGEWRFAWFPAPEAVPESW"
    "LECDLPEADTVVVPSNWQMHGYDAPIYTNVTYPITVNPPFVPTENPTGCYSLTFNVDESWLQEGQTRIIFDG"
    "VNSAFHLWCNGRWVGYGQDSRLPSEFDLSAFLRAGENRLAVMVLRWSDGSYLEDQDMWRMSGIFRDVSLLHKP"
    "TTQISDFHVATRFNDDFSRAVLEAEVQMCGELRDYLRVTVSLWQGETQVASGTAPFGGEIIDERGGYADRVT"
    "LRLNVENPKLWSAEIPNLYRAVVELHTADGTLIEAEACDVGFREVRIENGLLLLNGKPLLIRGVNRHEHHPLH"
    "GQVMDEQTMVQDILLMKQNNFNAVRCSHYPNHPLWYTLCDRYGLYVVDEANIETHGMVPMNRLTDDPRWLPA"
    "MSERVTRMVQRDRNHPSVIIWSLGNESGHGANHDALYRWIKSVDPSRPVQYEGGGADTTATDIICPMYARVD"
    "EDQPFPAVPKWSIKKWLSLPGETRPLILCEYAHAMGNSLGGFAKYWQAFRQYPRLQGGFVWDWVDQSLIKYD"
    "ENGNPWSAYGGDFGDTPNDRQFCMNGLVFADRTPHPALTEAKHQQQFFQFRLSGQTIEVTSEYLFRHSDNEL"
    "LHWMVALDGKPLASGEVPLDVAPQGKQLIELPELPQPESAGQLWLTVRVVQPNATAWSEAGHISAWQQWRLA"
    "ENLSVTLPAASHAIPHLTTSEMDFCIELGNKRWQFNRQSGFLSQMWIGDKKQLLTPLRDQFTRAPLDNDIGV"
    "SEATRIDPNAWVERWKAAGHYQAEAALLQCTADTLADAVLITTAHAWQHQGKTLFISRKTYRIDGSGQMAIT"
    "VDVEVASDTPHPARIGLNCQLAQVAERVNWLGLGPQENYPDRLTAACFDRWDLPLSDMYTPYVFPSENGLRC"
    "GTRELNYGPHQWRGDFQFNISRYSQQQLMETSHRHLLHAEEGTWLNIDGFHMGIGGDDSWSPSVSAEFQLSA"
    "GRYHYQLVWCQK"
)

# trpA — Tryptophan synthase α subunit (b1260), minus strand, 807 bp
_TRPA_DNA = (
    "ATGGAACGCTACGAATCTCTGTTTGCCCAGTTGAAGGAGCGCAAAGAAGGCGCATTCGTTCCTTTCGTCACGCT"
    "CGGTGATCCGGGCATTGAGCAGTCATTGAAAATTATCGATACGCTAATTGAAGCCGGTGCTGACGCGCTGGAG"
    "TTAGGTATCCCCTTCTCCGACCCACTGGCGGATGGCCCGACGATTCAAAACGCCACTCTGCGCGCCTTTGCGG"
    "CAGGTGTGACTCCGGCACAATGTTTTGAAATGCTGGCACTGATTCGCCAGAAACACCCGACCATTCCCATTGGC"
    "CTGTTGATGTATGCCAATCTGGTGTTTAACAAAGGCATTGATGAGTTTTATGCCCAGTGCGAAAAAGTCGGCG"
    "TCGATTCGGTGCTGGTTGCCGATGTGCCAGTTGAAGAGTCCGCGCCCTTCCGCCAGGCCGCGTTGCGTCATAA"
    "TGTCGCACCTATCTTCATCTGCCCGCCAAATGCCGATGACGACCTGCTGCGCCAGATAGCCTCTTACGGTCGT"
    "GGTTACACCTATTTGCTGTCACGAGCAGGCGTGACCGGCGCAGAAAACCGCGCCGCGTTACCCCTCAATCATC"
    "TGGTTGCGAAGCTGAAAGAGTACAACGCTGCACCTCCATTGCAGGGATTTGGTATTTCCGCCCCGGATCAGGT"
    "AAAAGCAGCGATTGATGCAGGAGCTGCGGGCGCGATTTCTGGTTCGGCCATTGTTAAAATCATCGAGCAACAT"
    "ATTAATGAGCCAGAGAAAATGCTGGCGGCACTGAAAGTTTTTGTACAACCGATGAAAGCGGCGACGCGCAGTTAA"
)

_TRPA_PROTEIN = (
    "MERYESLFAQLKERKEGAFVPFVTLGDPGIEQSLKIIDTLIEAGADALELGIPFSDPLADGPTIQNATLRAFAA"
    "GVTPAQCFEMLALIRQKHPTIPIGLLMYANLVFNKGIDEFYAQCEKVGVDSVLVADVPVEESAPFRQAALRHN"
    "VAPIFICPPNADDDLLRQIASYGRGYTYLLSRAGVTGAENRAALPLNHLVAKLKEYNAAPPLQGFGISAPDQV"
    "KAAIDAGAAGAISGSAIVKIIEQHINEPEKMLAALKVFVQPMKAATRS"
)

# recA — Recombinase A (b2699), minus strand, 1062 bp
_RECA_DNA = (
    "ATGGCTATCGACGAAAACAAACAGAAAGCGTTGGCGGCAGCACTGGGCCAGATTGAGAAACAATTTGGTAAAGGC"
    "TCCATCATGCGCCTGGGTGAAGACCGTTCCATGGATGTGGAAACCATCTCTACCGGTTCGCTTTCACTGGATAT"
    "CGCGCTTGGGGCAGGTGGTCTGCCGATGGGCCGTATCGTCGAAATCTACGGACCGGAATCTTCCGGTAAAACC"
    "ACGCTGACGCTGCAGGTGATCGCCGCAGCGCAGCGTGAAGGTAAAACCTGTGCGTTTATCGATGCTGAACACG"
    "CGCTGGACCCAATCTACGCACGTAAACTGGGCGTCGATATCGACAACCTGCTGTGCTCCCAGCCGGACACCGG"
    "CGAGCAGGCACTGGAAATCTGTGACGCCCTGGCGCGTTCTGGCGCAGTAGACGTTATCGTCGTTGACTCCGTG"
    "GCGGCACTGACGCCGAAAGCGGAAATCGAAGGCGAAATCGGCGACTCTCACATGGGCCTTGCGGCACGTATGA"
    "TGAGCCAGGCGATGCGTAAGCTGGCGGGTAACCTGAAGCAGTCCAACACGCTGCTGATCTTCATCAACCAGATC"
    "CGTATGAAAATTGGTGTGATGTTCGGTAACCCGGAAACCACTACCGGTGGTAACGCGCTGAAATTCTACGCCT"
    "CTGTTCGTCTCGACATCCGTCGTATCGGCGCGGTGAAAGAGGGCGAAAACGTGGTGGGTAGCGAAACCCGCG"
    "TGAAAGTGGTGAAGAACAAAATCGCTGCGCCGTTTAAACAGGCTGAATTCCAGATCCTCTACGGCGAAGGTAT"
    "CAACTTCTACGGCGAACTGGTTGACCTGGGCGTAAAAGAGAAGCTGATCGAGAAAGCAGGCGCGTGGTACAGC"
    "TACAAAGGTGAGAAGATCGGTCAGGGTAAAGCGAATGCGACTGCCTGGCTGAAAGATAACCCGGAAACCGCGA"
    "AAGAGATCGAGAAGAAAGTACGTGAGTTGCTGCTGAGCAACCCGAACTCAACGCCGGATTTCTCTGTAGATGA"
    "TAGCGAAGGCGTAGCAGAAACTAACGAAGATTTTTAA"
)

_RECA_PROTEIN = (
    "MAIDENKQKALAAALGQIEKQFGKGSIMRLGEDRSMDVETISTGSLSLDIALGAGGLPMGRIVEIYGPESSGKT"
    "TLTLQVIAAAQREGKTCAFIDAEHALDPIYARKLGVDIDNLLCSQPDTGEQALEICDALARSGAVDVIVVDSV"
    "AALTPKAEIEGEIGDSHMGLAARMMSQAMRKLAGNLKQSNTLLIFINQIRMKIGVMFGNPETTTGGNALKFYA"
    "SVRLDIRRIGAVKEGENVVGSETRVKVVKNKIAAPFKQAEFQILYGEGINFYGELVDLGVKEKLIEKAGAWYS"
    "YKGEKIGQGKANATAWLKDNPETAKEIEKKVRELLLSNPNSTPDFSVDDSEGVAETNEDF"
)

# ompA — Outer membrane protein A (b0957), minus strand, 1041 bp
_OMPA_DNA = (
    "ATGAAAAAGACAGCTATCGCGATTGCAGTGGCACTGGCTGGTTTCGCTACCGTAGCGCAGGCCGCTCCGAAAG"
    "ATAACACCTGGTACACTGGTGCTAAACTGGGCTGGTCCCAGTACCATGACACTGGTTTCATCAACAACAATGGC"
    "CCGACCCATGAAAACCAACTGGGCGCTGGTGCTTTTGGTGGTTACCAGGTTAACCCGTATGTTGGCTTTGAAA"
    "TGGGTTACGACTGGTTAGGTCGTATGCCGTACAAAGGCAGCGTTGAAAACGGTGCATACAAAGCTCAGGGCGT"
    "TCAACTGACCGCTAAACTGGGTTACCCAATCACTGACGACCTGGACATCTACACTCGTCTGGGTGGCATGGTA"
    "TGGCGTGCAGACACTAAATCCAACGTTTATGGTAAAAACCACGACACCGGCGTTTCTCCGGTCTTCGCTGGC"
    "GGTGTTGAGTACGCGATCACTCCTGAAATCGCTACCCGTCTGGAATACCAGTGGACCAACAACATCGGTGACG"
    "CACACACCATCGGCACTCGTCCGGACAACGGCATGCTGAGCCTGGGTGTTTCCTACCGTTTCGGTCAGGGCGA"
    "AGCAGCTCCAGTAGTTGCTCCGGCTCCAGCTCCGGCACCGGAAGTACAGACCAAGCACTTCACTCTGAAGTCTG"
    "ACGTTCTGTTCAACTTCAACAAAGCAACCCTGAAACCGGAAGGTCAGGCTGCTCTGGATCAGCTGTACAGCCA"
    "GCTGAGCAACCTGGATCCGAAAGACGGTTCCGTAGTTGTTCTGGGTTACACCGACCGCATCGGTTCTGACGCT"
    "TACAACCAGGGTCTGTCCGAGCGCCGTGCTCAGTCTGTTGTTGATTACCTGATCTCCAAAGGTATCCCGGCAG"
    "ACAAGATCTCCGCACGTGGTATGGGCGAATCCAACCCGGTTACTGGCAACACCTGTGACAACGTGAAACAGCG"
    "TGCTGCACTGATCGACTGCCTGGCTCCGGATCGTCGCGTAGAGATCGAAGTTAAAGGTATCAAAGACGTTGTAA"
    "CTCAGCCGCAGGCTTAA"
)

_OMPA_PROTEIN = (
    "MKKTAIAIAVALAGFATVAQAAPKDNTWYTGAKLGWSQYHDTGFINNNGPTHENQLGAGAFGGYQVNPYVGFEM"
    "GYDWLGRMPYKGSVENGAYKAQGVQLTAKLGYPITDDLDIYTRLGGMVWRADTKSNVYGKNHDTGVSPVFAGG"
    "VEYAITPEIATRLEYQWTNNIGDAHTIGTRPDNGMLSLGVSYRFGQGEAAPVVAPAPAPAPEVQTKHFTLKSDV"
    "LFNFNKATLKPEGQAALDQLYSQLSNLDPKDGSVVVLGYTDRIGSDAYNQGLSERRAQSVVDYLISKGIPADKI"
    "SARGMGESNPVTGNTCDNVKQRAALIDCLAPDRRVEIEVKGIKDVVTQPQA"
)

# groEL — Chaperonin GroEL (b4143), minus strand, 1647 bp
_GROEL_DNA = (
    "ATGGCAGCTAAAGACGTAAAATTCGGTAACGACGCTCGTGTGAAAATGCTGCGCGGCGTAAACGTACTGGCAG"
    "ATGCAGTGAAAGTTACCCTCGGTCCAAAAGGCCGTAACGTAGTTCTGGATAAATCTTTCGGTGCACCGACCATC"
    "ACCAAAGATGGTGTTTCCGTTGCTCGTGAAATCGAACTGGAAGACAAGTTCGAAAATATGGGTGCGCAGATGG"
    "TGAAAGAAGTTGCCTCTAAAGCAAACGACGCTGCAGGCGACGGTACCACCACTGCAACCGTACTGGCTCAGGC"
    "TATCATCACTGAAGGTCTGAAAGCTGTTGCTGCGGGCATGAACCCGATGGACCTGAAACGTGGTATCGACAAA"
    "GCGGTTACCGCTGCAGTTGAAGAACTGAAAGCGCTGTCCGTACCATGCTCTGACTCTAAAGCGATTGCTCAGG"
    "TTGGTACCATCTCCGCTAACTCCGACGAAACCGTAGGTAAACTGATCGCTGAAGCGATGGACAAAGTCGGTAA"
    "AGAAGGCGTTATCACCGTTGAAGACGGTACCGGTCTGCAGGACGAACTGGACGTGGTTGAAGGTATGCAGTTC"
    "GACCGTGGCTACCTGTCTCCTTACTTCATCAACAAGCCGGAAACTGGCGCAGTAGAACTGGAAAGCCCGTTCA"
    "TCCTGCTGGCTGACAAGAAAATCTCCAACATCCGCGAAATGCTGCCGGTTCTGGAAGCTGTTGCCAAAGCAGGC"
    "AAACCGCTGCTGATCATCGCTGAAGATGTAGAAGGCGAAGCGCTGGCAACTCTGGTTGTTAACACCATGCGTGG"
    "CATCGTGAAAGTCGCTGCGGTTAAAGCACCGGGCTTCGGCGATCGTCGTAAAGCTATGCTGCAGGATATCGCAA"
    "CCCTGACTGGCGGTACCGTGATCTCTGAAGAGATCGGTATGGAGCTGGAAAAAGCAACCCTGGAAGACCTGGGT"
    "CAGGCTAAACGTGTTGTGATCAACAAAGACACCACCACTATCATCGATGGCGTGGGTGAAGAAGCTGCAATCCA"
    "GGGCCGTGTTGCTCAGATCCGTCAGCAGATTGAAGAAGCAACTTCTGACTACGACCGTGAAAAACTGCAGGAAC"
    "GCGTAGCGAAACTGGCAGGCGGCGTTGCAGTTATCAAAGTGGGTGCTGCTACCGAAGTTGAAATGAAAGAGAA"
    "AAAAGCACGCGTTGAAGATGCCCTGCACGCGACCCGTGCTGCGGTAGAAGAAGGCGTGGTTGCTGGTGGTGGT"
    "GTTGCGCTGATCCGCGTAGCGTCTAAACTGGCTGACCTGCGTGGTCAGAACGAAGACCAGAACGTGGGTATCA"
    "AAGTTGCACTGCGTGCAATGGAAGCTCCGCTGCGTCAGATCGTATTGAACTGCGGCGAAGAACCGTCTGTTG"
    "TTGCTAACACCGTTAAAGGCGGCGACGGCAACTACGGTTACAACGCAGCAACCGAAGAATACGGCAACATGATC"
    "GACATGGGTATCCTGGATCCAACCAAAGTAACTCGTTCTGCTCTGCAGTACGCAGCTTCTGTGGCTGGCCTGA"
    "TGATCACCACCGAATGCATGGTTACCGACCTGCCGAAAAACGATGCAGCTGACTTAGGCGCTGCTGGCGGTAT"
    "GGGCGGCATGGGTGGCATGGGCGGCATGATGTAA"
)

_GROEL_PROTEIN = (
    "MAAKDVKFGNDARVKMLRGVNVLADAVKVTLGPKGRNVVLDKSFGAPTITKDGVSVAREIELEDKFENMGAQMV"
    "KEVASKANDAAGDGTTTATVLAQAIITEGLKAVAAGMNPMDLKRGIDKAVTAAVEELKALSVPCSDSKAIAQVG"
    "TISANSDETVGKLIAEAMDKVGKEGVITVEDGTGLQDELDVVEGMQFDRGYLSPYFINKPETGAVELESPFILL"
    "ADKKISNIREMLPVLEAVAKAGKPLLIIAEDVEGEALATLVVNTMRGIVKVAAVKAPGFGDRRKAMLQDIATLT"
    "GGTVISEEIGMELEKATLEDLGQAKRVVINKDTTTIIDGVGEEAAIQGRVAQIRQQIEEATSDYDREKLQERVA"
    "KLAGGVAVIKVGAATEVEMKEKKARVEDALHATRAAVEEGVVAGGGVALIRVASKLADLRGQNEDQNVGIKVAL"
    "RAMEAPLRQIVLNCGEEPSVVANTVKGGDGNYGYNAATEEYGNMIDMGILDPTKVTRSALQYAASVAGLMITTE"
    "CMVTDLPKNDAADLGAAGGMGGMGGMGGMM"
)

# ── S. cerevisiae S288C ─────────────────────────────────────────────────────

# ADH1 — Alcohol dehydrogenase 1 (YOL086C)
# Source: NCBI mRNA RefSeq, 1047 bp CDS
_YEAST_ADH1_DNA = (
    "ATGTCTATCCCAGAAACTCAAAAAGGTGTTATCTTCTACGAATCCCACGGTAAGTTGGAATACAAAGATATTCCA"
    "GTTCCAAAGCCAAAGGCCAACGAATTGTTGATCAACGTTAAATACTCTGGTGTCTGTCACACTGACTTGCACGC"
    "TTGGCACGGTGACTGGCCATTGCCAGTTAAGCTACCATTAGTCGGTGGTCACGAAGGTGCCGGTGTCGTTGTCG"
    "GCATGGGTGAAAACGTTAAGGGCTGGAAGATCGGTGACTACGCCGGTATCAAATGGTTGAACGGTTCTTGTATG"
    "GCCTGTGAATACTGTGAATTGGGTAACGAATCCAACTGTCCTCACGCTGACTTGTCTGGTTACACCCACGACGG"
    "TTCTTTCCAACAATACGCTACCGCTGACGCTGTTCAAGCCGCTCACATTCCTCAAGGTACCGACTTGGCCCAAG"
    "TCGCCCCCATCTTGTGTGCTGGTATCACCGTCTACAAGGCTTTGAAGTCTGCTAACTTGATGGCCGGTCACTG"
    "GGTTGCTATCTCCGGTGCTGCTGGTGGTCTAGGTTCTTTGGCTGTTCAATACGCCAAGGCTATGGGTTACAGAG"
    "TCTTGGGTATTGACGGTGGTGAAGGTAAGGAAGAATTATTCAGATCCATCGGTGGTGAAGTCTTCATTGACTTC"
    "ACTAAGGAAAAGGACATTGTCGGTGCTGTTCTAAAGGCCACTGACGGTGGTGCTCACGGTGTCATCAACGTTTC"
    "CGTTTCCGAAGCCGCTATTGAAGCTTCTACCAGATACGTTAGAGCTAACGGTACCACCGTTTTGGTCGGTATGC"
    "CAGCTGGTGCCAAGTGTTGTTCTGATGTCTTCAACCAAGTCGTCAAGTCCATCTCTATTGTTGGTTCTTACGTC"
    "GGTAACAGAGCTGACACCAGAGAAGCTTTGGACTTCTTCGCCAGAGGTTTGGTCAAGTCTCCAATCAAGGTTGTC"
    "GGCTTGTCTACCTTGCCAGAAATTTACGAAAAGATGGAAAAGGGTCAAATCGTTGGTAGATACGTTGTTGACACT"
    "TCTAAATAA"
)

_YEAST_ADH1_PROTEIN = (
    "MSIPETQKGVIFYESHGKLEYKDIPVPKPKANELLINVKYSGVCHTDLHAWHGDWPLPVKLPLVGGHEGAGVVV"
    "GMGENVKGWKIGDYAGIKWLNGSCMACEYCELGNESNCPHADLSGYTHDGSFQQYATADAVQAAHIPQGTDLAQ"
    "VAPILCAGITVYKALKSANLMAGHWVAISGAAGGLGSLAVQYAKAMGYRVLGIDGGEGKEELFRSIGGEVFIDF"
    "TKEKDIVGAVLKATDGGAHGVINVSVSEAAIEASTRYVRANGTTVLVGMPAGAKCCSDVFNQVVKSISIVGSYV"
    "GNRADTREALDFFARGLVKSPIKVVGLSTLPEIYEKMEKGQIVGRYVVDTSK"
)

# PGK1 — Phosphoglycerate kinase 1 (YCR012W)
# Source: NCBI mRNA RefSeq, 1251 bp CDS
_YEAST_PGK1_DNA = (
    "ATGTCTTTATCTTCAAAGTTGTCTGTCCAAGATTTGGACTTGAAGGACAAGCGTGTCTTCATCAGAGTTGACTTC"
    "AACGTCCCATTGGACGGTAAGAAGATCACTTCTAACCAAAGAATTGTTGCTGCTTTGCCAACCATCAAGTACGTT"
    "TTGGAACACCACCCAAGATACGTTGTCTTGGCTTCTCACTTGGGTAGACCAAACGGTGAAAGAAACGAAAAATA"
    "CTCTTTGGCTCCAGTTGCTAAGGAATTGCAATCATTGTTGGGTAAGGATGTCACCTTCTTGAACGACTGTGTCG"
    "GTCCAGAAGTTGAAGCCGCTGTCAAGGCTTCTGCCCCAGGTTCCGTTATTTTGTTGGAAAACTTGCGTTACCAC"
    "ATCGAAGAAGAAGGTTCCAGAAAGGTCGATGGTCAAAAGGTCAAGGCTTCCAAGGAAGATGTTCAAAAGTTCAGA"
    "CACGAATTGAGCTCTTTGGCTGATGTTTACATCAACGATGCCTTCGGTACCGCTCACAGAGCTCACTCTTCTATG"
    "GTCGGTTTCGACTTGCCACAACGTGCTGCCGGTTTCTTGTTGGAAAAGGAATTGAAGTACTTCGGTAAGGCTTT"
    "GGAGAACCCAACCAGACCATTCTTGGCCATCTTAGGTGGTGCCAAGGTTGCTGACAAGATTCAATTGATTGACAA"
    "CTTGTTGGACAAGGTCGACTCTATCATCATTGGTGGTGGTATGGCTTTCACCTTCAAGAAGGTTTTGGAAAACAC"
    "TGAAATCGGTGACTCCATCTTCGACAAGGCTGGTGCTGAAATCGTTCCAAAGTTGATGGAAAAGGCCAAGGCCAA"
    "GGGTGTCGAAGTCGTCTTGCCAGTCGACTTCATCATTGCTGATGCTTTCTCTGCTGATGCCAACACCAAGACTGT"
    "CACTGACAAGGAAGGTATTCCAGCTGGCTGGCAAGGGTTGGACAATGGTCCAGAATCTAGAAAGTTGTTTGCTGC"
    "TACTGTTGCAAAGGCTAAGACCATTGTCTGGAACGGTCCACCAGGTGTTTTCGAATTCGAAAAGTTCGCTGCTGG"
    "TACTAAGGCTTTGTTAGACGAAGTTGTCAAGAGCTCTGCTGCTGGTAACACCGTCATCATTGGTGGTGGTGACAC"
    "TGCCACTGTCGCTAAGAAGTACGGTGTCACTGACAAGATCTCCCATGTCTCTACTGGTGGTGGTGCTTCTTTGG"
    "AATTATTGGAAGGTAAGGAATTGCCAGGTGTTGCTTTCTTATCCGAAAAGAAATAA"
)

_YEAST_PGK1_PROTEIN = (
    "MSLSSKLSVQDLDLKDKRVFIRVDFNVPLDGKKITSNQRIVAALPTIKYVLEHHPRYVVLASHLGRPNGERNEK"
    "YSLAPVAKELQSLLGKDVTFLNDCVGPEVEAAVKASAPGSVILLENLRYHIEEEGSRKVDGQKVKASKEDVQKF"
    "RHELSSLADVYINDAFGTAHRAHSSMVGFDLPQRAAGFLLEKELKYFGKALENPTRPFLAILGGAKVADKIQLID"
    "NLLDKVDSIIIGGGMAFTFKKVLENTEIGDSIFDKAGAEIVPKLMEKAKAKGVEVVLPVDFIIADAFSADANTK"
    "TVTDKEGIPAGWQGLDNGPESRKLFAATVAKAKTIVWNGPPGVFEFEKFAAGTKALLDEVVKSSAAGNTVIIGG"
    "GDTATVAKKYGVTDKISHVSTGGGASLELLEGKELPGVAFLSEKK"
)

# ENO1 — Enolase 1 (YGR254W)
# Source: NCBI mRNA RefSeq, 1314 bp CDS
_YEAST_ENO1_DNA = (
    "ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTGGTAACCCAACCGTCGAAGTCGAATTAA"
    "CCACCGAAAAGGGTGTTTTCAGATCCATTGTCCCATCTGGTGCTTCTACCGGTGTCCACGAAGCTTTGGAAATG"
    "AGAGATGGTGACAAATCCAAGTGGATGGGTAAGGGTGTTTTGCACGCTGTTAAGAACGTCAACGATGTCATTGC"
    "TCCAGCTTTCGTTAAGGCTAACATTGATGTTAAGGACCAAAAGGCCGTCGATGACTTCTTGATTTCTTTGGACG"
    "GTACTGCCAACAAATCCAAGTTGGGTGCTAACGCTATCTTGGGTGTTTCTTTGGCTGCTTCCAGAGCTGCCGC"
    "TGCTGAAAAGAATGTCCCATTATACAAGCACTTGGCTGACTTGTCTAAGTCCAAGACCTCTCCATACGTTTTGC"
    "CAGTTCCATTCTTGAACGTTTTGAACGGTGGTTCCCACGCTGGTGGTGCTTTGGCTTTGCAAGAATTTATGAT"
    "TGCTCCAACTGGTGCTAAGACCTTCGCTGAAGCTTTGAGAATTGGTTCCGAAGTTTACCACAACTTGAAGTCTT"
    "TGACCAAGAAGAGATACGGTGCTTCTGCCGGTAACGTCGGTGACGAAGGTGGTGTTGCTCCAAACATTCAAACT"
    "GCTGAAGAAGCTTTGGACTTGATTGTTGACGCTATCAAGGCTGCTGGTCACGACGGTAAGATCAAGATCGGTT"
    "TGGACTGTGCTTCCTCTGAATTCTTCAAGGACGGTAAGTACGACTTGGACTTCAAGAATCCAAACTCTGACAAA"
    "TCCAAGTGGTTGACTGGTCCTCAATTGGCTGACTTGTACCACTCCTTGATGAAGAGATACCCAATTGTCTCCAT"
    "CGAAGATCCATTTGCTGAAGATGACTGGGAAGCTTGGTCTCACTTCTTCAAGACCGCTGGTATTCAAATTGTTG"
    "CTGATGACTTGACTGTCACCAACCCAAAGAGAATTGCTACCGCTATCGAAAAGAAGGCTGCCGACGCTTTGTTG"
    "TTGAAGGTCAACCAAATCGGTACCTTGTCTGAATCCATCAAGGCTGCTCAAGACTCTTTCGCTGCCGGTTGGGG"
    "TGTTATGGTTTCCCACAGATCTGGTGAAACTGAAGACACTTTCATTGCTGACTTGGTCGTCGGTTTGAGAACTG"
    "GTCAAATCAAGACTGGTGCTCCAGCTAGATCCGAAAGATTGGCTAAATTGAACCAATTGTTGAGAATCGAAGAAG"
    "AATTAGGTGACAACGCTGTTTTCGCTGGTGAAAACTTCCACCACGGTGACAAATTATAA"
)

_YEAST_ENO1_PROTEIN = (
    "MAVSKVYARSVYDSRGNPTVEVELTTEKGVFRSIVPSGASTGVHEALEMRDGDKSKWMGKGVLHAVKNVNDVIAP"
    "AFVKANIDVKDQKAVDDFLISLDGTANKSKLGANAILGVSLAASRAAAAEKNVPLYKHLADLSKSKTSPYVLPVP"
    "FLNVLNGGSHAGGALALQEFMIAPTGAKTFAEALRIGSEVYHNLKSLTKKRYGASAGNVGDEGGVAPNIQTAEE"
    "ALDLIVDAIKAAGHDGKIKIGLDCASSEFFKDGKYDLDFKNPNSDKSKWLTGPQLADLYHSLMKRYPIVSIEDPF"
    "AEDDWEAWSHFFKTAGIQIVADDLTVTNPKRIATAIEKKAADALLLKVNQIGTLSESIKAAQDSFAAGWGVMVSH"
    "RSGETEDTFIADLVVGLRTGQIKTGAPARSERLAKLNQLLRIEEELGDNAVFAGENFHHGDKL"
)

# ACT1 — Actin (YFL039C)
# Source: NCBI mRNA RefSeq, 1128 bp CDS
_YEAST_ACT1_DNA = (
    "ATGGATTCTGAGGTTGCTGCTTTGGTTATTGATAACGGTTCTGGTATGTGTAAAGCCGGTTTTGCCGGTGACGA"
    "CGCTCCTCGTGCTGTCTTCCCATCTATCGTCGGTAGACCAAGACACCAAGGTATCATGGTCGGTATGGGTCAAA"
    "AAGACTCCTACGTTGGTGATGAAGCTCAATCCAAGAGAGGTATCTTGACTTTACGTTACCCAATTGAACACGGT"
    "ATTGTCACCAACTGGGACGATATGGAAAAGATCTGGCATCATACCTTCTACAACGAATTGAGAGTTGCCCCAGA"
    "AGAACACCCTGTTCTTTTGACTGAAGCTCCAATGAACCCTAAATCAAACAGAGAAAAGATGACTCAAATTATGTT"
    "TGAAACTTTCAACGTTCCAGCCTTCTACGTTTCCATCCAAGCCGTTTTGTCCTTGTACTCTTCCGGTAGAACTA"
    "CTGGTATTGTTTTGGATTCCGGTGATGGTGTTACTCACGTCGTTCCAATTTACGCTGGTTTCTCTCTACCTCAC"
    "GCCATTTTGAGAATCGATTTGGCCGGTAGAGATTTGACTGACTACTTGATGAAGATCTTGAGTGAACGTGGTTA"
    "CTCTTTCTCCACCACTGCTGAAAGAGAAATTGTCCGTGACATCAAGGAAAAACTATGTTACGTCGCCTTGGACT"
    "TCGAACAAGAAATGCAAACCGCTGCTCAATCTTCTTCAATTGAAAAATCCTACGAACTTCCAGATGGTCAAGTC"
    "ATCACTATTGGTAACGAAAGATTCAGAGCCCCAGAAGCTTTGTTCCATCCTTCTGTTTTGGGTTTGGAATCTGC"
    "CGGTATTGACCAAACTACTTACAACTCCATCATGAAGTGTGATGTCGATGTCCGTAAGGAATTATACGGTAACA"
    "TCGTTATGTCCGGTGGTACCACCATGTTCCCAGGTATTGCCGAAAGAATGCAAAAGGAAATCACCGCTTTGGCT"
    "CCATCTTCCATGAAGGTCAAGATCATTGCTCCTCCAGAAAGAAAGTACTCCGTCTGGATTGGTGGTTCTATCTT"
    "GGCTTCTTTGACTACCTTCCAACAAATGTGGATCTCAAAACAAGAATACGACGAAAGTGGTCCATCTATCGTTC"
    "ACCACAAGTGTTTCTAA"
)

_YEAST_ACT1_PROTEIN = (
    "MDSEVAALVIDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGIMVGMGQKDSYVGDEAQSKRGILTLRYPIEHGI"
    "VTNWDDMEKIWHHTFYNELRVAPEEHPVLLTEAPMNPKSNREKMTQIMFETFNVPAFYVSIQAVLSLYSSGRTT"
    "GIVLDSGDGVTHVVPIYAGFSLPHAILRIDLAGRDLTDYLMKILSERGYSFSTTAEREIVRDIKEKLCYVALDFE"
    "QEMQTAAQSSSIEKSYELPDGQVITIGNERFRAPEALFHPSVLGLESAGIDQTTYNSIMKCDVDVRKELYGNIVM"
    "SGGTTMFPGIAERMQKEITALAPSSMKVKIIAPPERKYSVWIGGSILASLTTFQQMWISKQEYDESGPSIVHHKCF"
)

# ── H. sapiens ──────────────────────────────────────────────────────────────

# HBB — β-globin (NM_000518.5), 444 bp CDS
_HUMAN_HBB_DNA = (
    "ATGGTGCATCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGG"
    "TGGTGAGGCCCTGGGCAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGT"
    "CCACTCCTGATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGTGAT"
    "GGCCTGGCTCACCTGGACAACCTCAAGGGCACCTTTGCCACACTGAGTGAGCTGCACTGTGACAAGCTGCACGT"
    "GGATCCTGAGAACTTCAGGCTCCTGGGCAACGTGCTGGTCTGTGTGCTGGCCCATCACTTTGGCAAAGAATTCA"
    "CCCCACCAGTGCAGGCTGCCTATCAGAAAGTGGTGGCTGGTGTGGCTAATGCCCTGGCCCACAAGTATCACTAA"
)

_HUMAN_HBB_PROTEIN = (
    "MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSD"
    "GLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH"
)

# INS — Insulin (NM_000207.3), 333 bp CDS
# Note: The CDS includes the signal peptide, B chain, C-peptide, and A chain.
_HUMAN_INS_DNA = (
    "ATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAGCCT"
    "TTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGGGGAACGAGGCTTCTTC"
    "TACACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGTGGGGCAGGTGGAGCTGGGCGGGGGCCCTGGTGC"
    "AGGCAGCCTGCAGCCCTTGGCCCTGGAGGGGTCCCTGCAGAAGCGTGGCATTGTGGAACAATGCTGTACCAGCA"
    "TCTGCTCCCTCTACCAGCTGGAGAACTACTGCAACTAG"
)

_HUMAN_INS_PROTEIN = (
    "MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGA"
    "GSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN"
)

# ── Assemble the full dictionary ────────────────────────────────────────────

VALIDATION_SEQUENCES: Dict[tuple, dict] = {
    # ── E. coli K-12 MG1655 (NC_000913.3) ──────────────────────────
    ("lacZ", "Escherichia_coli"): {
        "protein_sequence": _LACZ_PROTEIN,
        "dna_sequence": _LACZ_FULL_DNA[:498],  # first 498 bp (166 codons) for testing
        "dna_sequence_full": _LACZ_FULL_DNA,
        "dna_sequence_note": "First 498 bp (166 codons) of the 3075 bp CDS; full CDS in dna_sequence_full",
        "expected_cai": 0.27,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI NC_000913.3 / U00096.3",
        "gene_id": "b0344",
        "notes": (
            "lacZ CDS is on the minus strand.  Only the first 498 bp "
            "(166 codons) is provided in dna_sequence for quick testing; "
            "use dna_sequence_full for the complete 3075 bp CDS.  The "
            "published CAI of 0.27 was computed on the full CDS — testing "
            "on the first 498 bp alone may yield a slightly different value."
        ),
    },
    ("trpA", "Escherichia_coli"): {
        "protein_sequence": _TRPA_PROTEIN,
        "dna_sequence": _TRPA_DNA,
        "dna_sequence_full": _TRPA_DNA,
        "dna_sequence_note": "Complete CDS (807 bp)",
        "expected_cai": 0.84,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI NC_000913.3 / U00096.3",
        "gene_id": "b1260",
        "notes": (
            "trpA (tryptophan synthase α) is a highly expressed gene on the "
            "minus strand.  Complete CDS provided."
        ),
    },
    ("recA", "Escherichia_coli"): {
        "protein_sequence": _RECA_PROTEIN,
        "dna_sequence": _RECA_DNA,
        "dna_sequence_full": _RECA_DNA,
        "dna_sequence_note": "Complete CDS (1062 bp)",
        "expected_cai": 0.76,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI NC_000913.3 / U00096.3",
        "gene_id": "b2699",
        "notes": (
            "recA (recombinase A) is on the minus strand.  Complete CDS provided."
        ),
    },
    ("ompA", "Escherichia_coli"): {
        "protein_sequence": _OMPA_PROTEIN,
        "dna_sequence": _OMPA_DNA,
        "dna_sequence_full": _OMPA_DNA,
        "dna_sequence_note": "Complete CDS (1041 bp)",
        "expected_cai": 0.79,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI NC_000913.3 / U00096.3",
        "gene_id": "b0957",
        "notes": (
            "ompA (outer membrane protein A) is on the minus strand.  Complete "
            "CDS provided."
        ),
    },
    ("groEL", "Escherichia_coli"): {
        "protein_sequence": _GROEL_PROTEIN,
        "dna_sequence": _GROEL_DNA,
        "dna_sequence_full": _GROEL_DNA,
        "dna_sequence_note": "Complete CDS (1647 bp)",
        "expected_cai": 0.78,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI NC_000913.3 / U00096.3",
        "gene_id": "b4143",
        "notes": (
            "groEL (chaperonin GroEL, a.k.a. mopA) is on the minus strand.  "
            "Complete CDS provided."
        ),
    },

    # ── S. cerevisiae S288C ─────────────────────────────────────────
    ("ADH1", "Saccharomyces_cerevisiae"): {
        "protein_sequence": _YEAST_ADH1_PROTEIN,
        "dna_sequence": _YEAST_ADH1_DNA,
        "dna_sequence_full": _YEAST_ADH1_DNA,
        "dna_sequence_note": "Complete CDS (1047 bp)",
        "expected_cai": 0.91,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI mRNA RefSeq (YOL086C)",
        "gene_id": "YOL086C",
        "notes": (
            "ADH1 (alcohol dehydrogenase 1) is one of the most highly "
            "expressed genes in yeast.  Complete CDS provided from NCBI."
        ),
    },
    ("PGK1", "Saccharomyces_cerevisiae"): {
        "protein_sequence": _YEAST_PGK1_PROTEIN,
        "dna_sequence": _YEAST_PGK1_DNA,
        "dna_sequence_full": _YEAST_PGK1_DNA,
        "dna_sequence_note": "Complete CDS (1251 bp)",
        "expected_cai": 0.88,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI mRNA RefSeq (YCR012W)",
        "gene_id": "YCR012W",
        "notes": (
            "PGK1 (phosphoglycerate kinase 1) is a highly expressed glycolytic "
            "enzyme.  Complete CDS provided from NCBI."
        ),
    },
    ("ENO1", "Saccharomyces_cerevisiae"): {
        "protein_sequence": _YEAST_ENO1_PROTEIN,
        "dna_sequence": _YEAST_ENO1_DNA,
        "dna_sequence_full": _YEAST_ENO1_DNA,
        "dna_sequence_note": "Complete CDS (1314 bp)",
        "expected_cai": 0.72,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI mRNA RefSeq (YGR254W)",
        "gene_id": "YGR254W",
        "notes": (
            "ENO1 (enolase 1) is moderately-to-highly expressed.  Complete "
            "CDS provided from NCBI."
        ),
    },
    ("ACT1", "Saccharomyces_cerevisiae"): {
        "protein_sequence": _YEAST_ACT1_PROTEIN,
        "dna_sequence": _YEAST_ACT1_DNA,
        "dna_sequence_full": _YEAST_ACT1_DNA,
        "dna_sequence_note": "Complete CDS (1128 bp)",
        "expected_cai": 0.56,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI mRNA RefSeq (YFL039C)",
        "gene_id": "YFL039C",
        "notes": (
            "ACT1 (actin) is constitutively expressed but has a surprisingly "
            "low CAI for a housekeeping gene.  Complete CDS provided from NCBI."
        ),
    },

    # ── H. sapiens ──────────────────────────────────────────────────
    ("HBB", "Homo_sapiens"): {
        "protein_sequence": _HUMAN_HBB_PROTEIN,
        "dna_sequence": _HUMAN_HBB_DNA,
        "dna_sequence_full": _HUMAN_HBB_DNA,
        "dna_sequence_note": "Complete CDS (444 bp)",
        "expected_cai": 0.95,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "genome_ref": "NCBI NM_000518.5",
        "gene_id": "HBB",
        "notes": (
            "HBB (β-globin) is extremely highly expressed in erythroid cells.  "
            "Complete CDS provided from NCBI RefSeq."
        ),
    },
    ("INS", "Homo_sapiens"): {
        "protein_sequence": _HUMAN_INS_PROTEIN,
        "dna_sequence": _HUMAN_INS_DNA,
        "dna_sequence_full": _HUMAN_INS_DNA,
        "dna_sequence_note": "Complete CDS (333 bp)",
        "expected_cai": 0.84,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "genome_ref": "NCBI NM_000207.3",
        "gene_id": "INS",
        "notes": (
            "INS (insulin) CDS includes signal peptide, B chain, C-peptide, "
            "and A chain.  Complete CDS provided from NCBI RefSeq."
        ),
    },

    # ── Heterologous genes (DNA not available from native genome) ───
    ("GFP", "Escherichia_coli"): {
        "protein_sequence": (
            "MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFS"
            "RYPDHMKRHDFFKSAMPEGYVQERTISFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNY"
            "NSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHM"
            "VLLEFVTAAGITHGMDELYK"
        ),
        "dna_sequence": None,
        "dna_sequence_full": None,
        "dna_sequence_note": (
            "Native Aequorea victoria GFP DNA not provided; CAI depends on "
            "the specific codon-optimized variant used."
        ),
        "expected_cai": 0.54,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "genome_ref": "N/A (heterologous)",
        "gene_id": "GFP",
        "notes": (
            "GFP (Aequorea victoria) expressed in E. coli.  The CAI of 0.54 "
            "reflects native jellyfish codon usage, which is suboptimal for "
            "E. coli.  DNA sequence not provided as it varies between constructs."
        ),
    },
    ("Insulin", "Escherichia_coli"): {
        "protein_sequence": (
            "MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPG"
            "AGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN"
        ),
        "dna_sequence": None,
        "dna_sequence_full": None,
        "dna_sequence_note": "Human INS native DNA used; see HBB section for human CDS",
        "expected_cai": 0.34,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "genome_ref": "N/A (heterologous in E. coli)",
        "gene_id": "INS",
        "notes": (
            "Human insulin expressed in E. coli using native human codons.  "
            "CAI ≈ 0.34 reflects poor adaptation of human codon usage to "
            "E. coli.  The human INS CDS is available in the H. sapiens "
            "section of this database."
        ),
    },
    ("hGH", "Escherichia_coli"): {
        "protein_sequence": (
            "FPTIPLSRLFDNAMLRAHRLHQLAFDTYQEFEEAYIPKEQKYSFLQNPQTSLCFSESIPTPSNREETQQKSNL"
            "ELLRISLLLIQSWLEPVQFLRSVFANSLVYGASDSNVYDLLKDLEEGIQTLMGRLEDGSPRTGQIFKQTYSKF"
            "DTNSHNDDALLKNYGLLYCFRKDMDKVETFLRIVQCRSVEGSCGF"
        ),
        "dna_sequence": None,
        "dna_sequence_full": None,
        "dna_sequence_note": "Native human GH1 DNA not included in this database",
        "expected_cai": 0.32,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "genome_ref": "N/A (heterologous in E. coli)",
        "gene_id": "GH1",
        "notes": (
            "Human growth hormone (somatotropin, mature form) expressed in "
            "E. coli using native human codons.  CAI ≈ 0.32."
        ),
    },
    ("IFN-alpha2", "Escherichia_coli"): {
        "protein_sequence": (
            "CDLPQTHSLGNRRTLMLLAQMRKISLFSCLKDRHDFGFPQEEFGNQFQKAETIPVLHEMIQQIFNLFSTKDSS"
            "AAWDETLLDKFYTELYQQLNDLEACVIQEVGVEETPLMNEDSILAVRKYFQRITLYLKEKKYSPCAWEVVRAEI"
            "MRSFSLSTNLQESLRSKE"
        ),
        "dna_sequence": None,
        "dna_sequence_full": None,
        "dna_sequence_note": "Native human IFNA2 DNA not included in this database",
        "expected_cai": 0.33,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "genome_ref": "N/A (heterologous in E. coli)",
        "gene_id": "IFNA2",
        "notes": (
            "Interferon-alpha 2 (mature form, 165 aa) expressed in E. coli "
            "using native human codons.  CAI ≈ 0.33."
        ),
    },
    ("ALB", "Homo_sapiens"): {
        "protein_sequence": (
            "MKWVTFISLLFLFSSAYSRGVFRRDAHKSEVAHRFKDLGEENFKALVLIAFAQYLQQCPFEDHVKLVNEVTEFAK"
            "TCVADESAENCDKSLHTLFGDKLCTVATLRETYGEMADCCAKQEPERNECFLQHKDDNPNLPRLVRPEVDVMCT"
            "AFHDNEETFLKKYLYEIARRHPYFYAPELLYYANKYNGVFQECCQAEDKGACLLPKIETMREKCLTSQKRLKVS"
            "LATVSQRQRLCASIQKFGERALKAWSVARLSQKFPKAEFVEVTKLVTDLTKVHKECCHGDLLECADDRADLAKY"
            "ICDNQDTISSKLKECCDKPLLEKSHCIAEVEKDAIPENLPPLTADFAEDKDVCKNYQEAKDAFLGSFLYEYSRR"
            "HPEYAVSVLLRLAKEYEATLEECCAKDDPHACYSTVFDKLKHLVDEPQNLIKQNCDQFEKLGEYGFQNALIVRYT"
            "RKVPQVSTPTLVEVSRSLGKVGTRCCTKPESERMPCTEDYLSLILNRLCVLHEKTPVSEKVTKCCTESLVNRRPC"
            "FSALTPDETYVPKAFDEKLFTFHADICTLPDTEKQIKKQTALVELLKHKPKATEEQLKTVMENFVAFVDKCCAAD"
            "DHEACAKVEKAFMKED"
        ),
        "dna_sequence": None,
        "dna_sequence_full": None,
        "dna_sequence_note": "ALB CDS not included; 1833 bp is too long for inline storage",
        "expected_cai": 0.78,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "genome_ref": "NCBI NM_000477.7",
        "gene_id": "ALB",
        "notes": (
            "ALB (albumin) is the most abundant human plasma protein.  "
            "CAI ≈ 0.78.  DNA CDS available from NCBI NM_000477.7."
        ),
    },
    ("TP53", "Homo_sapiens"): {
        "protein_sequence": (
            "MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPDEAPRMPEAAPPVAP"
            "APAAPTPAAPAPAPSWPLSSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDST"
            "PPPGTRVRAMAIYKKSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRAEYLDDRNTFRHSVVVPYEPPEVG"
            "SDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENLHKTTGIMFGREVT"
            "FEEMRKVVVLTSEDQKRIEGVFAKTRVLMAEPPDYTPSGGLRPPVIIATQPSPTVWTESPLVTGQLVQVLTTETSS"
            "QGTGLQISFNFLSVLNPPNQDDLPSLDPSQNLASPGSSEEFLKQKLTPEVQERL"
        ),
        "dna_sequence": None,
        "dna_sequence_full": None,
        "dna_sequence_note": "TP53 CDS not included; complex splice pattern",
        "expected_cai": 0.63,
        "citation": (
            "Puigbo, Bravo & Garcia-Vallve (2008) BMC Bioinformatics 9:65"
        ),
        "doi": "10.1186/1471-2105-9-65",
        "genome_ref": "NCBI NM_000546.6",
        "gene_id": "TP53",
        "notes": (
            "TP53 (tumor protein p53) is expressed at moderate levels.  "
            "CAI ≈ 0.63.  DNA CDS available from NCBI NM_000546.6."
        ),
    },
    ("rpoB", "Escherichia_coli"): {
        "protein_sequence": None,
        "dna_sequence": None,
        "dna_sequence_full": None,
        "dna_sequence_note": "rpoB CDS (4029 bp) not included; too long for inline storage",
        "expected_cai": 0.50,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI NC_000913.3",
        "gene_id": "b3987",
        "notes": (
            "rpoB (RNA polymerase β subunit) is moderately expressed.  "
            "CAI ≈ 0.50.  DNA CDS (4029 bp) available from E. coli K-12 genome."
        ),
    },
    ("dnaK", "Escherichia_coli"): {
        "protein_sequence": None,
        "dna_sequence": None,
        "dna_sequence_full": None,
        "dna_sequence_note": "dnaK CDS not included",
        "expected_cai": 0.76,
        "citation": "Sharp & Li (1987) Nucleic Acids Res 15:1281-1295, Table 1",
        "doi": "10.1093/nar/15.3.1281",
        "genome_ref": "NCBI NC_000913.3",
        "gene_id": "b0014",
        "notes": (
            "dnaK (Hsp70 chaperone) is highly expressed.  CAI ≈ 0.76.  "
            "DNA CDS available from E. coli K-12 genome."
        ),
    },
}


# ═══════════════════════════════════════════════════════════════════════════════
# 3. get_validation_test_cases()
# ═══════════════════════════════════════════════════════════════════════════════

def get_validation_test_cases(
    dna_required: bool = False,
) -> List[dict]:
    """Return all validation test cases in a format suitable for pytest parametrize.

    Each test case is a dictionary with the following keys:

    - ``gene``: Gene name (e.g. ``"lacZ"``)
    - ``organism``: Full organism name (e.g. ``"Escherichia_coli"``)
    - ``dna_sequence``: Coding DNA sequence (``str`` or ``None``)
    - ``protein_sequence``: Amino acid sequence (``str`` or ``None``)
    - ``expected_cai``: Published CAI value (``float``)
    - ``citation``: Paper reference (``str``)
    - ``doi``: DOI for the paper (``str``)
    - ``notes``: Caveats and additional information (``str``)

    Args:
        dna_required: If ``True``, only return test cases that have a
            DNA sequence available.  Defaults to ``False`` (return all).

    Returns:
        List of test-case dictionaries.

    Examples:
        >>> cases = get_validation_test_cases()
        >>> len(cases) > 0
        True
        >>> ecoli_cases = get_validation_test_cases(dna_required=True)
        >>> all(c["dna_sequence"] is not None for c in ecoli_cases)
        True
    """
    cases: List[dict] = []

    for (gene, organism), entry in VALIDATION_SEQUENCES.items():
        dna_seq: Optional[str] = entry.get("dna_sequence")

        if dna_required and dna_seq is None:
            continue

        cases.append({
            "gene": gene,
            "organism": organism,
            "dna_sequence": dna_seq,
            "protein_sequence": entry.get("protein_sequence"),
            "expected_cai": entry["expected_cai"],
            "citation": entry["citation"],
            "doi": entry.get("doi", ""),
            "notes": entry.get("notes", ""),
        })

    # Also include entries from PUBLISHED_CAI_VALUES that are not already
    # in VALIDATION_SEQUENCES (e.g. rpoB, dnaK if they were added there
    # but not in VALIDATION_SEQUENCES with DNA)
    covered_keys = set(VALIDATION_SEQUENCES.keys())
    for (gene, organism), entry in PUBLISHED_CAI_VALUES.items():
        if (gene, organism) in covered_keys:
            continue
        if dna_required:
            continue  # No DNA available for these entries
        cases.append({
            "gene": gene,
            "organism": organism,
            "dna_sequence": None,
            "protein_sequence": None,
            "expected_cai": entry["expected_cai"],
            "citation": entry["citation"],
            "doi": entry.get("doi", ""),
            "notes": entry.get("notes", ""),
        })

    return cases
