"""
BioCompiler Benchmarking Gene Sets
====================================
Curated gene sets for benchmarking protein optimization pipelines.

Each gene set maps a gene symbol to a dict with:
  - protein_sequence : str   – amino acid sequence (UniProt canonical, with signal peptide)
  - organism         : str   – source organism
  - description      : str   – human-readable protein name
  - uniprot_id       : str   – UniProtKB accession (or empty string if unknown)

Extended gene sets use the new schema:
  - name              : str   – gene symbol
  - protein           : str   – amino acid sequence
  - organism          : str   – source organism
  - expected_cai_range: tuple – rough expected CAI range
  - category          : str   – functional category

Sequences sourced from UniProtKB/Swiss-Prot (reviewed, canonical isoforms),
except where noted (e.g. F8 truncated to first 300 aa).
"""

from __future__ import annotations

__all__ = [
    "HUMAN_THERAPEUTIC_GENES",
    "VACCINE_ANTIGEN_GENES",
    "STRESS_TEST_GENES",
    "E_COLI_EXTENDED",
    "HUMAN_THERAPEUTIC",
    "HUMAN_SIGNALING",
    "YEAST_INDUSTRIAL",
    "MOUSE_MODEL",
    "get_all_gene_sets",
]


# ---------------------------------------------------------------------------
# Human Therapeutic Genes (legacy format)
# ---------------------------------------------------------------------------

HUMAN_THERAPEUTIC_GENES: dict[str, dict] = {
    "INS": {
        "protein_sequence": (
            "MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKT"
            "RREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLEN"
            "YCN"
        ),
        "organism": "Homo sapiens",
        "description": "Insulin precursor (preproinsulin); therapeutic: recombinant human insulin",
        "uniprot_id": "P01308",
    },
    "GH1": {
        "protein_sequence": (
            "MATGSRTSLLLAFGLLCLPWLQEGSAFPTIPLSRLFDNAMLRAHRLHQLAFDT"
            "YQEFEEAYIPKEQKYSFLQNPQTSLCFSESIPTPSNREETQQKSNLELLRISL"
            "LLIQSWLEPVQFLRSVFANSLVYGASDSNVYDLLKDLEEGIQTLMGRLEDGSP"
            "RTGQIFKQTYSKFDTNSHNDDALLKNYGLLYCFRKDMDKVETFLRIVQCRSVE"
            "GSCGF"
        ),
        "organism": "Homo sapiens",
        "description": "Somatotropin (growth hormone); therapeutic: recombinant human GH (somatropin)",
        "uniprot_id": "P01241",
    },
    "EPO": {
        "protein_sequence": (
            "MGVHECPAWLWLLLSLLSLPLGLPVLGAPPRLICDSRVLERYLLEAKEAENITT"
            "GCAEHCSLNENITVPDTKVNFYAWKRMEVGQQAVEVWQGLALLSEAVLRGQAL"
            "LVNSSQPWEPLQLHVDKAVSGLRSLTTLLRALGAQKEAISPPDAASAAPLRTI"
            "TADTFRKLFRVYSNFLRGKLKLYTGEACRTGDR"
        ),
        "organism": "Homo sapiens",
        "description": "Erythropoietin precursor; therapeutic: recombinant epoetin alfa",
        "uniprot_id": "P01588",
    },
    "IFNA2": {
        "protein_sequence": (
            "MALTFALLVALLVLSCKSSCSVGCDLPQTHSLGSRRTLMLLAQMRRISLFSCLK"
            "DRHDFGFPQEEFGNQFQKAETIPVLHEMIQQIFNLFSTKDSSAAWDETLLDKF"
            "YTELYQQLNDLEACVIQGVGVTETPLMKEDSILAVRKYFQRITLYLKEKKYSP"
            "CAWEVVRAEIMRSFSLSTNLQESLRSKE"
        ),
        "organism": "Homo sapiens",
        "description": "Interferon alpha-2 precursor; therapeutic: recombinant IFN-alpha-2a/2b",
        "uniprot_id": "P01563",
    },
    "IL2": {
        "protein_sequence": (
            "MYRMQLLSCIALSLALVTNSAPTSSSTKKTQLQLEHLLLDLQMILNGINNYKNP"
            "KLTRMLTFKFYMPKKATELKHLQCLEEELKPLEEVLNLAQSKNFHLRPRDLISN"
            "INVIVLELKGSETTFMCEYADETATIVEFLNRWITFCQSIISTLT"
        ),
        "organism": "Homo sapiens",
        "description": "Interleukin-2 precursor; therapeutic: recombinant aldesleukin",
        "uniprot_id": "P60568",
    },
    "CSF3": {
        "protein_sequence": (
            "MAGPATQSPMKLMALQLLLWHSALWTVQEATPLGPASSLPQSFLLKCLEQVRKI"
            "QGDGAALQEKLVSECATYKLCHPEELVLLGHSLGIPWAPLSSCPSQALQLAGCL"
            "SQLHSGLFLYQGLLQALEGISPELGPTLDTLQLDVADFATTIWQQMEELGMAPA"
            "LQPTQGAMPAFASAFQRRAGGVLVASHLQSFLEVSYRVLRHLAQP"
        ),
        "organism": "Homo sapiens",
        "description": "Granulocyte colony-stimulating factor precursor; therapeutic: filgrastim",
        "uniprot_id": "P09919",
    },
    "PLAT": {
        "protein_sequence": (
            "MDAMKRGLCCVLLLCGAVFVSPSQEIHARFRRGARSYQVICRDEKTQMIYQQHQ"
            "SWLRPVLRSNRVEYCWCNSGRAQCHSVPVKSCSEPRCFNGGTCQQALYFSDFVC"
            "QCPEGFAGKCCEIDTRATCYEDQGISYRGTWSTAESGAECTNWNSSALAQKPYS"
            "GRRPDAIRLGLGNHNYCRNPDRDSKPWCYVFKAGKYSSEFCSTPACSEGNSDCY"
            "FGNGSAYRGTHSLTESGASCLPWNSMILIGKVYTAQNPSAQALGLGKHNYCRNP"
            "DGDAKPWCHVLKNRRLTWEYCDVPSCSTCGLRQYSQPQFRIKGGLFADIASHPW"
            "QAAIFAKHRRSPGERFLCGGILISSCWILSAAHCFQERFPPHHLTVILGRTYRV"
            "VPGEEEQKFEVEKYIVHKEFDDDTYDNDIALLQLKSDSSRCAQESSVVRTVCLP"
            "PADLQLPDWTECELSGYGKHEALSPFYSERLKEAHVRLYPSSRCTSQHLLNRTV"
            "TDNMLCAGDTRSGGPQANLHDACQGDSGGPLVCLNDGRMTLVGIISWGLGCGQK"
            "DVPGVYTKVTNYLDWIRDNMRP"
        ),
        "organism": "Homo sapiens",
        "description": "Tissue-type plasminogen activator precursor; therapeutic: alteplase",
        "uniprot_id": "P00750",
    },
    "F8": {
        # First 300 aa of the 2351-aa precursor (A1 domain region)
        "protein_sequence": (
            "MQIELSTCFFLCLLRFCFSATRRYYLGAVELSWDYMQSDLGELPVDARFPPRVPK"
            "SFPFNTSVVYKKTLFVEFTDHLFNIAKPRPPWMGLLGPTIQAEVYDTVVITLKN"
            "MASHPVSLHAVGVSYWKASEGAEYDDQTSQREKEDDKVFPGGSHTYVWQVLKENG"
            "PMASDPLCLTYSYLSHVDLVKDLNSGLIGALLVCREGSLAKEKTQTLHKFILLFA"
            "VFDEGKSWHSETKNSLMQDRDAASARAWPKMHTVNGYVNRSLPGLIGCHRKSVYW"
            "HVIGMGTTPEVHSIFLEGHTFLVRNH"
        ),
        "organism": "Homo sapiens",
        "description": "Coagulation factor VIII precursor (first 300 aa); therapeutic: recombinant FVIII",
        "uniprot_id": "P00451",
    },
    "SERPINA1": {
        "protein_sequence": (
            "MPSSVSWGILLLAGLCCLVPVSLAEDPQGDAAQKTDTSHHDQDHPTFNKITPNLA"
            "EFAFSLYRQLAHQSNSTNIFFSPVSIATAFAMLSLGTKADTHDEILEGLNFNLTE"
            "IPEAQIHEGFQELLRTLNQPDSQLQLTTGNGLFLSEGLKLVDKFLEDVKKLYHSE"
            "AFTVNFGDTEEAKKQINDYVEKGTQGKIVDLVKELDRDTVFALVNYIFFKGKWER"
            "PFEVKDTEEEDFHVDQVTTVKVPMMKRLGMFNIQHCKKLSSWVLLMKYLGNATAI"
            "FFLPDEGKLQHLENELTHDIITKFLENEDRRSASLHLPKLSITGTYDLKSVLGQL"
            "GITKVFSNGADLSGVTEEAPLKLSKAVHKAVLTIDEKGTEAAGAMFLEAIPMSIPP"
            "EVKFNKPFVFLMIEQNTKSPLFMGKVVNPTQK"
        ),
        "organism": "Homo sapiens",
        "description": "Alpha-1-antitrypsin precursor; therapeutic: recombinant A1AT augmentation therapy",
        "uniprot_id": "P01009",
    },
    "GBA": {
        "protein_sequence": (
            "MEFSSPSREECPKPLSRVSIMAGSLTGLLLLQAVSWASGARPCIPKSFGYSSVVC"
            "VCNATYCDSFDPPTFPALGTFSRYESTRSGRRMELSMGPIQANHTGTGLLLTLQP"
            "EQKFQKVKGFGGAMTDAAALNILALSPPAQNLLLKSYFSEEGIGYNIIRVPMASC"
            "DFSIRTYTYADTPDDFQLHNFSLPEEDTKLKIPLIHRALQLAQRPVSLLASPWTSP"
            "TWLKTNGAVNGKGSLKGQPGDIYHQTWARYFVKFLDAYAEHKLQFWAVTAENEPS"
            "AGLLSGYPFQCLGFTPEHQRDFIARDLGPTLANSTHHNVRLLMLDDQRLLLPHWA"
            "KVVLTDPEAAKYVHGIAVHWYLDFLAPAKATLGETHRLFPNTMLFASEACVGSKF"
            "WEQSVRLGSWDRGMQYSHSIITNLLYHVVGWTDWNLALNPEGGPNWVRNFVDSP"
            "IIVDITKDTFYKQPMFYHLGHFSKFIPEGSQRVGLVASQKNDLDAVALMHPDGSA"
            "VVVVLNRSSKDVPLTIKDPAVGFLETISPGYSIHTYLWRRQ"
        ),
        "organism": "Homo sapiens",
        "description": "Lysosomal acid glucosylceramidase precursor; therapeutic: imiglucerase/velaglucerase",
        "uniprot_id": "P04062",
    },
}


# ---------------------------------------------------------------------------
# Vaccine Antigen Genes (legacy format)
# ---------------------------------------------------------------------------

VACCINE_ANTIGEN_GENES: dict[str, dict] = {
    "SARS2_Spike": {
        "protein_sequence": (
            "MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFS"
            "NVTWFHAIHVSGTNGTKRFDNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDSKTQSLLIV"
            "NNATNVVIKVCEFQFCNDPFLGVYYHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLE"
            "GKQGNFKNLREFVFKNIDGYFKIYSKHTPINLVRDLPQGFSALEPLVDLPIGINITRFQT"
            "LLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETK"
            "CTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISN"
            "CVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIAD"
            "YNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPC"
            "NGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVN"
            "FNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITP"
            "GTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSY"
            "ECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTI"
            "SVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQE"
            "VFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDC"
            "LGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAM"
            "QMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALN"
            "TLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRA"
            "SANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPA"
            "ICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDP"
            "LQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDL"
            "QELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDD"
            "SEPVLKGVKLHYT"
        ),
        "organism": "Severe acute respiratory syndrome coronavirus 2",
        "description": "SARS-CoV-2 Spike glycoprotein (Wuhan-Hu-1); vaccine: BNT162b2/mRNA-1273",
        "uniprot_id": "P0DTC2",
    },
    "SARS2_RBD": {
        "protein_sequence": (
            "RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFK"
            "CYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNS"
            "NNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQ"
            "PTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNF"
        ),
        "organism": "Severe acute respiratory syndrome coronavirus 2",
        "description": "SARS-CoV-2 Spike RBD domain (residues 319-541); vaccine: subunit vaccines",
        "uniprot_id": "P0DTC2",
    },
    "H1N1_HA": {
        "protein_sequence": (
            "MKANLLVLLCALAAADADTICIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDSHNGKLCR"
            "LKGIAPLQLGKCNIAGWLLGNPECDPLLPVRSWSYIVETPNSENGICYPGDFIDYEELRE"
            "QLSSVSSFERFEIFPKESSWPNHNTNGVTAACSHEGKSSFYRNLLWLTEKEGSYPKLKNS"
            "YVNKKGKEVLVLWGIHHPPNSKEQQNLYQNENAYVSVVTSNYNRRFTPEIAERPKVRDQA"
            "GRMNYYWTLLKPGDTIIFEANGNLIAPMYAFALSRGFGSGIITSNASMHECNTKCQTPLG"
            "AINSSLPYQNIHPVTIGECPKYVRSAKLRMVTGLRNIPSIQSRGLFGAIAGFIEGGWTGM"
            "IDGWYGYHHQNEQGSGYAADQKSTQNAINGITNKVNTVIEKMNIQFTAVGKEFNKLEKRM"
            "ENLNKKVDDGFLDIWTYNAELLVLLENERTLDFHDSNVKNLYEKVKSQLKNNAKEIGNGC"
            "FEFYHKCDNECMESVRNGTYDYPKYSEESKLNREKVDGVKLESMGIYQILAIYSTVASSL"
            "VLLVSLGAISFWMCSNGSLQCRICI"
        ),
        "organism": "Influenza A virus (A/Puerto Rico/8/1934 H1N1)",
        "description": "Influenza A H1N1 Hemagglutinin; vaccine: seasonal flu vaccines",
        "uniprot_id": "P03452",
    },
    "H3N2_HA": {
        "protein_sequence": (
            "MKTIIALSYIFCLALGQDLPGNDNSTATLCLGHHAVPNGTLVKTITDDQIEVTNATELVQ"
            "SSSTGKICNNPHRILDGIDCTLIDALLGDPHCDVFQNETWDLFVERSKAFSNCYPYDVPD"
            "YASLRSLVASSGTLEFITEGFTWTGVTQNGGSNACKRGPGSGFFSRLNWLTKSGSTYPVL"
            "NVTMPNNDNFDKLYIWGIHHPSTNQEQTSLYVQASGRVTVSTRRSQQTIIPNIGSRPWVR"
            "GLSSRISIYWTIVKPGDVLVINSNGNLIAPRGYFKMRTGKSSIMRSDAPIDTCISECITP"
            "NGSIPNDKPFQNVNKITYGACPKYVKQNTLKLATGMRNVPEKQTRGLFGAIAGFIENGWE"
            "GMIDGWYGFRHQNSEGTGQAADLKSTQAAIDQINGKLNRVIEKTNEKFHQIEKEFSEVEG"
            "RIQDLEKYVEDTKIDLWSYNAELLVALENQHTIDLTDSEMNKLFEKTRRQLRENAEEMGN"
            "GCFKIYHKCDNACIESIRNGTYDHDVYRDEALNNRFQIKGVELKSGYKDWILWISFAISC"
            "FLLCVVLLGFIMWACQRGNIRCNICI"
        ),
        "organism": "Influenza A virus (A/Aichi/2/1968 H3N2)",
        "description": "Influenza A H3N2 Hemagglutinin; vaccine: seasonal flu vaccines",
        "uniprot_id": "P03437",
    },
    "HIV1_gp120": {
        "protein_sequence": (
            "TEKLWVTVYYGVPVWKEATTTLFCASDAKAYDTEVHNVWATHACVPTDPNPQEVVLVNVT"
            "ENFNMWKNDMVEQMHEDIISLWDQSLKPCVKLTPLCVSLKCTDLKNDTNTNSSSGRMIME"
            "KGEIKNCSFNISTSIRGKVQKEYAFFYKLDIIPIDNDTTSYKLTSCNTSVITQACPKVSF"
            "EPIPIHYCAPAGFAILKCNNKTFNGTGPCTNVSTVQCTHGIRPVVSTQLLLNGSLAEEEV"
            "VIRSVNFTDNAKTIIVQLNTSVEINCTRPNNNTRKRIRIQRGPGRAFVTIGKIGNMRQAH"
            "CNISRAKWNNTLKQIASKLREQFGNNKTIIFKQSSGGDPEIVTHSFNCGGEFFYCNSTQL"
            "FNSTWFNSTWSTEGSNNTEGSDTITLPCRIKQIINMWQKVGKAMYAPPISGQIRCSSNIT"
            "GLLLTRDGGNSNNESEIFRPGGGDMRDNWRSELYKYKVVKIEPLGVAPTKAKRRVVQREK"
            "RAVGIGALFLGFLGAAGSTM"
        ),
        "organism": "Human immunodeficiency virus type 1",
        "description": "HIV-1 Envelope gp120 (residues 31-530 of gp160); vaccine: experimental HIV vaccines",
        "uniprot_id": "P04578",
    },
    "RSV_F": {
        "protein_sequence": (
            "MELLILKANAITTILTAVTFCFASGQNITEEFYQSTCSAVSKGYLSALRTGWYTSVITIE"
            "LSNIKENKCNGTDAKVKLIKQELDKYKNAVTELQLLMQSTPPTNNRARRELPRFMNYTLN"
            "NAKKTNVTLSKKRKRRFLGFLLGVGSAIASGVAVSKVLHLEGEVNKIKSALLSTNKAVVS"
            "LSNGVSVLTSKVLDLKNYIDKQLLPIVNKQSCSISNIETVIEFQQKNNRLLEITREFSVN"
            "AGVTTPVSTYMLTNSELLSLINDMPITNDQKKLMSNNVQIVRQQSYSIMSIIKEEVLAYV"
            "VQLPLYGVIDTPCWKLHTSPLCTTNTKEGSNICLTRTDRGWYCDNAGSVSFFPQAETCKV"
            "QSNRVFCDTMNSLTLPSEINLCNVDIFNPKYDCKIMTSKTDVSSSVITSLGAIVSCYGKT"
            "KCTASNKNRGIIKTFSNGCDYVSNKGMDTVSVGNTLYYVNKQEGKSLYVKGEPIINFYDP"
            "LVFPSDEFDASISQVNEKINQSLAFIRKSDELLHNVNAGKSTTNIMITTIIIVIIVILLS"
            "LIAVGLLLYCKARSTPVTLSKDQLSGINNIAFSN"
        ),
        "organism": "Human respiratory syncytial virus",
        "description": "RSV Fusion glycoprotein F0; vaccine: Arexvy/Abrysvo",
        "uniprot_id": "P03420",
    },
    "RABV_G": {
        "protein_sequence": (
            "MSKIFVNPSAIRAGLADLEMAEETVDLINRNIEDNDAHLQGEPIEVDNLPEDMKRLHLDD"
            "EKSSNLGEMVRVGEGKYREDFQMDEGEDPNLLFQSYLDNVGVQIVRQMRSGERFLKIWSQ"
            "TVEEIVSYVTVNFPNPPRRSSEDKSTQTTGRELKKETTSAFSQRESQPSKARMVAQVAPG"
            "PPALEWSATNEEDDLSVEAEIAHQIAESFSKKYKFPSRSSGIFLYNFEQLKMNLDDIVKE"
            "AKNVPGVTRLAHDGSKIPLRCVLGWVALANSKKFQLLVEADKLSKIMQDDLNRYTSC"
        ),
        "organism": "Rabies virus (strain PV)",
        "description": "Glycoprotein G; vaccine: HDCV/PCECV rabies vaccines",
        "uniprot_id": "P15198",
    },
    "Zika_E": {
        "protein_sequence": (
            "IRCIGVSNRDFVEGMSGGTWVDVVLEHGGCVTVMAQDKPTVDIELVTTTVSNMAEVRSYC"
            "YEASISDMASDSRCPTQGEAYLDKQSDTQYVCKRTLVDRGWGNGCGLFGKGSLVTCAKFT"
            "CSKKMTGKSIQPENLEYRIMLSVHGSQHSGMIGYETDEDRAKVEVTPNSPRAEATLGGFG"
            "SLGLDCEPRTGLDFSDLYYLTMNNKHWLVHKEWFHDIPLPWHAGADTGTPHWNNKEALVE"
            "FKDAHAKRQTVVVLGSQEGAVHTALAGALEAEMDGAKGRLFSGHLKCRLKMDKLRLKGVS"
            "YSLCTAAFTFTKVPAETLHGTVTVEVQYAGTDGPCKIPVQMAVDMQTLTPVGRLITANPV"
            "ITESTENSKMMLELDPPFGDSYIVIGVGDKKITHHWHRSGSTIGKAFEATVRGAKRMAVL"
            "GDTAWDFGSVGGVFNSLGKGIHQIFGAAFKSLFGGMSWFSQILIGTLLVWLGLNTKNGSI"
            "SLTCLALGGVMIFLSTAVSA"
        ),
        "organism": "Zika virus",
        "description": "Zika virus Envelope protein E (residues 291-790 of polyprotein); vaccine: experimental",
        "uniprot_id": "Q32ZE1",
    },
    "DENV2_E": {
        "protein_sequence": (
            "MRCIGISNRDFVEGVSGGSWVDIVLEHGSCVTTMAKNKPTLDFELIETEAKQPATLRKYC"
            "IEAKLTNTTTDSRCPTQGEPSLNEEQDKRFVCKHSMVDRGWGNGCGLFGKGGIVTCAMFT"
            "CKKNMKGKVVQPENLEYTIVITPHSGEEHAVGNDTGKHGKEIKITPQSSITEAELTGYGT"
            "VTMECSPRTGLDFNEMVLLQMENKAWLVHRQWFLDLPLPWLPGADTQGSNWIQKETLVTF"
            "KNPHAKKQDVVVLGSQEGAMHTALTGATEIQMSSGNLLFTGHLKCRLRMDKLQLKGMSYS"
            "MCTGKFKVVKEIAETQHGTIVIRVQYEGDGSPCKIPFEIMDLEKRHVLGRLITVNPIVTE"
            "KDSPVNIEAEPPFGDSYIIIGVEPGQLKLNWFKKGSSIGQMIETTMRGAKRMAILGDTAW"
            "DFGSLGGVFTSIGKALHQVFGAIYGAAFSGVSWIMKILIGVIITWIGMNSRSTSLSVSLV"
            "LVGVVTLYLGVMVQA"
        ),
        "organism": "Dengue virus type 2",
        "description": "Dengue virus type 2 Envelope protein E (residues 281-775 of polyprotein); vaccine: Dengvaxia",
        "uniprot_id": "P14340",
    },
    "MTB_Ag85B": {
        "protein_sequence": (
            "MPRVEVGLVIHSRMHARAPVDVWRSVRSLPDFWRLLQVRVASQFGDGLFQAGLAGALLFN"
            "PDRAADPMAIAGAFAVLFLPYSLLGPFAGALMDRWDRRWVLVGANTGRLALIAGVGTILA"
            "VGAGDVPLLVGALVANGLARFVASGLSAALPHVVPREQVVTMNSVAIASGAVSAFLGANF"
            "MLLPRWLLGSGDEGASAIVFLVAIPVSIALLWSLRFGPRVLGPDDTERAIHGSAVYAVVT"
            "GWLHGARTVVQLPTVAAGLSGLAAHRMVVGINSLLILLLVRHVTARAVGGLGTALLFFAA"
            "TGLGAFLANVLTPTAIRRWGRYATANGALAAAATIQVAAAGLLVPVMVVCGFLLGVAGQV"
            "VKLCADSAMQMDVDDALRGHVFAVQDALFWVSYILSITVAAALIPEHGHAPVFVLFGSAI"
            "YLAGLVVHTIVGRRGQPVIGR"
        ),
        "organism": "Mycobacterium tuberculosis",
        "description": "Antigen 85B; vaccine: M72/AS01E candidate",
        "uniprot_id": "P0A5C2",
    },
    "PF_CSP": {
        "protein_sequence": (
            "MMRKLAILSVSSFLFVEALFQEYQCYGSSSNTRVLNELNYDNAGTNLYNELEMNYYGKQE"
            "NWYSLKKNSRSLGENDDGNNEDNEKLRKPKHKKLKQPADGNPDPNANPNVDPNANPNVDP"
            "NANPNVDPNANPNANPNANPNANPNANPNANPNANPNANPNANPNANPNANPNANPNANP"
            "NANPNANPNANPNANPNVDPNANPNANPNANPNANPNANPNANPNANPNANPNANPNANP"
            "NANPNANPNANPNANPNANPNANPNANPNANPNKNNQGNGQGHNMPNDPNRNVDENANAN"
            "SAVKNNNNEEPSDKHIKEYLNKIQNSLSTEWSPCSVTCGNGIQVRIKPGSANKPKDELDY"
            "ANDIEKKICKMEKCSSVFNVVNSSIGLIMVLSFLFLN"
        ),
        "organism": "Plasmodium falciparum",
        "description": "Circumsporozoite protein; vaccine: RTS,S/AS01 (Mosquirix)",
        "uniprot_id": "P19597",
    },
}


# ---------------------------------------------------------------------------
# Stress-Test Genes (legacy format)
# ---------------------------------------------------------------------------

STRESS_TEST_GENES: dict[str, dict] = {
    "PolyA_100": {
        "protein_sequence": (
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        ),
        "organism": "synthetic",
        "description": "Poly-alanine repeat protein (100xA); tests homopolymer codon handling",
        "uniprot_id": "",
        "stress_category": "homopolymer",
    },
    "ExtremeGC_200": {
        "protein_sequence": (
            "RGAARRVGPGAPGGRPAPVGVRAGVAGGVRVRPVAPVRVPRGAAGAGARAAAAVRRGRGA"
            "VRPRVRAGAAAVVARAVPAAPAPVAAVPGGGRRPGAVPVVGRRPARGPPVVAPGVVARRG"
            "RPRPGAGVVVAGVVGPGRRGPPAVPAPRAAVRPPGAAPAAGRAVVGARAGVPPRVGGPPP"
            "RRVGPAVAGPPAAVPVPGVV"
        ),
        "organism": "synthetic",
        "description": "Extreme GC-biased protein (200aa, ~80% GC codons); tests high-GC optimization",
        "uniprot_id": "",
        "stress_category": "high_gc",
    },
    "ExtremeAT_200": {
        "protein_sequence": (
            "LLMKFKNINLKMFNLLFMKNLYFMIYFMKLIKYYKILKYYNYFLKMKNYNNMIFLLIKKL"
            "LLNKMYYLYIMNYLIIIFKYMKYKFLMINKIMYKMFNIILLFMYKINLMLLKKIMLNYKL"
            "LLMLIMNLMLMKMILLKMFNMKIKNLLKYNLFLILKLKIFMNYFNYKYILFMMYNIYNNM"
            "MNNNNNINLYLYNFINFYYF"
        ),
        "organism": "synthetic",
        "description": "Extreme AT-biased protein (200aa, ~20% GC codons); tests low-GC optimization",
        "uniprot_id": "",
        "stress_category": "high_at",
    },
    "Long_1000": {
        "protein_sequence": (
            "IDIYSNRLKESPMDDAQITAGKDFICMAPSRHNVLAQTISMVKVWKPLSLWPIQQKPLKQ"
            "AEQELNCFFAGLHDHYLFTPGAGPTVHPLKDDHAEFGNIRKAGLAKRIAGDEPGPSQAAL"
            "VGKSKPVDANRMLDFPNKPRSVRAEFVGFAFKRSTKRVSGHGLETSRVKSFHPVQSLIHP"
            "QTSRTCIKGATDDSETFQAVRPIPFKISRDFELILHPEFQQRDRLPDDIPVLERDDDALQ"
            "VLFRTITLIIDAVISGAKANLEVRPKSDLIITVEKKPVDDMNNAAILECFFIFYSKMVHL"
            "KYSANEPLERFFVLIAAHEQRVTLVVMQAPIKYDLKIRGEMTEFEVSLIEEVGLVMLGDG"
            "PKPDLYIFRVKCNLLRVYIRSLFLQSVCLGYLTTQSGVLSEELVINNGLLIEDFLCSAPF"
            "SGMSVIALLTTILIPGMNIVEFKTTTGEPPTAAKYVPHRKTIFYASEGNLLSNATKCYNI"
            "QQASYFNIGLKHQTDGICLLVEVMQLFPAKLYESKGKKFPMTKYKEILPREPNRLVLYSQ"
            "SISPERVNVTPVVSGSALIMMLSVRCATLYDASYEGNVEIRTRIMPVHPNGRIGVAGIVT"
            "RFLVGGDRTIMKKASCRLAPDDTENYATNRQNMAASCENAPLPISLRLVASTLIVAIGFI"
            "YAAKAQKLEVLIKRFTKSPDIDEIHRHMGNYASRRPSLLLERGMPTPVKGLDMDRTGPLS"
            "TVSKKAYSQDFEEATLGNKAPDHEGPSLRANKMQMIIQPRHEFIMAGKAEDNQEAPNGFL"
            "SSATAAYTLLFHRAESKSYRTCLLGEEENLRLYGPSSCNDKPMDSIPPIYLKKTKNAIEQ"
            "ALEIASATTKLILSWISKEINARYEFLNQIILNGEGEKSKARFEPMYTELNGVFGKVEGS"
            "SMSPFLKHGGDDVIDNATRSTTAEPRGNSSSNIGMCIEPILESITGVVIEGLVSSNQKTL"
            "RTTEPQYNIVDIGAALCVGAYTKSNESFNFIAAQSLPLRE"
        ),
        "organism": "synthetic",
        "description": "Long synthetic protein (1000aa); tests scalability of optimization pipeline",
        "uniprot_id": "",
        "stress_category": "long_sequence",
    },
    "Repetitive_10x20": {
        "protein_sequence": (
            "LKQFSLEQIAKRFNKMASTALKQFSLEQIAKRFNKMASTALKQFSLEQIAKRFNKMASTA"
            "LKQFSLEQIAKRFNKMASTALKQFSLEQIAKRFNKMASTALKQFSLEQIAKRFNKMASTA"
            "LKQFSLEQIAKRFNKMASTALKQFSLEQIAKRFNKMASTALKQFSLEQIAKRFNKMASTA"
            "LKQFSLEQIAKRFNKMASTA"
        ),
        "organism": "synthetic",
        "description": "Repetitive domain protein (10x 20aa repeat); tests repeat/recombination handling",
        "uniprot_id": "",
        "stress_category": "repetitive",
    },
}


# ---------------------------------------------------------------------------
# E. coli Extended Gene Set
# ---------------------------------------------------------------------------
# Additional E. coli genes covering a range of expression levels for
# comprehensive benchmarking of prokaryotic codon optimization.

E_COLI_EXTENDED: dict[str, dict] = {
    "lacZ": {
        "name": "lacZ",
        "protein": (
            "MTMITDSLAVVLQRRDWENPGVTQLNRLAAHPPFASWRNSEEARTDRPSQQLRSLNGEWRFAWF"
            "PAPEAVPESWLECDLPEADTVVVPSNWQMHGYDAPIYTNVTYPITVNPPFVPTENPTGCYSLTF"
            "NVDESWLQEGQTRIIFDGVNSAFHLWCNGRWVGYGQDSRLPSEFDLSAFLRAGENRLAVMVLR"
            "WSDGSYLEDQDMWRMSGIFRDVSLLHKPTTQISDFHVATRFNDDFSRAVLEAEVQMCGELRDY"
            "LRVTVSLWQGETQVASGTAPFGGEIIDERGGYADRVTLRLNVENPKLWSAEIPNLYRAVVELHT"
            "ADGTLIEAEACDVGFREVRIENGLLLLNGKPLLIRGVNRHEHHPLHGQVMDEQTMVQDILLMK"
            "QNNFNAVRCSHYPNHPLWYTLCDRYGLYVVDEANIETHGMVPMNRLTDDPRWLPAMSERVTRMV"
            "QDRKRYTLEEFVTAEWDESRPAVMEHVKLAPPPHPAEQLVDATLAEVLDRHTTLRGLQAYNAE"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.25, 0.55),
        "category": "housekeeping",
    },
    "lacI": {
        "name": "lacI",
        "protein": (
            "MKPVTLYDVAEYAGVSYQTVSRVVNQASHVSAKTREKVEAAMAELNYIPNRVAQQLAGKQSALIT"
            "VQGIGVSAFLTQADGSTVTAEVAQVVRSNQESTQASLSTEQMLAQQTRVAGQVRDAGRVSAELR"
            "HVGNGHELDAAIHQLTRAVQETSRATLFSLGNVVAHRVLEGDTLAFGHPLDQLRQALTEAWQRG"
            "HRLQAVVSQLPSRVLQQLASGHGDSAQASRAQALADWLGYRLFGHPEAPDSFQSWMRVEQRLGH"
            "TQAPYPHRLPNRPMSARHFSQGLNVRNALRAQVEALRRAQQASQQAQAVDPSRARFQQMLQNLR"
            "NQDHSAASSLRALAEQRQRQMTLAPAPQNRTPVQALQAGLRSADVSRVSAQALKAVQELRQELR"
            "SLTQRLQAQARKAQ"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.20, 0.45),
        "category": "regulatory",
    },
    "recA": {
        "name": "recA",
        "protein": (
            "MNLTELKNKPVMEIAQEQLLEQGKIVRALEQGFPDRHVNVLDFIDRAKQIDRGIERDVIVFCDGK"
            "ERELAAIYQRTLTRGHPQGFGYAQGRFLQGEMAEAWRRADENRDAVFRHLSDPSQPLVVFGMKT"
            "DAVKRIVVDAFQMTRQEAVEAWEKLAQALREGRGIEVIPRSADLIEATRRLFGQHVVNMAAGEG"
            "KTVNAVNLGLRGVEVQRLRLDLAFPGELDRAVARLADAREVIHPDVKRLAAGLAEGVRRYLDIS"
            "VRRMADAIERQEAK"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.50, 0.75),
        "category": "dna_repair",
    },
    "gyrA": {
        "name": "gyrA",
        "protein": (
            "MTMNIKLHEIEGVAEGCKTLEDAIRKGFEKLVQYARLRDAPFLHAIGFSKDKITTDNTSFLEQLE"
            "VMGKYSIPQELRDIYNAIVQKDDRVGQKINSQLPKVKDLTYGNIPRLDGTKRLAEDFVEYKSLN"
            "RGWNVVKELKNSTGLQYELPEYLNVILSKSRDGEVVFQYPNPEQLRDYLQHKVVNEQILRDKSG"
            "YDVWLSENKNFKDGVKAVLDRHRAQRLAELNVRFDKAQHEQGKSADYENFRRLRSQYAIFEGAG"
            "TDNQLTQTIKKVLGDSCSNADRLMFEALHDAIQKMKTRQLNMLSAKIDAVIESGFDNVIAVPSF"
            "GGLDRAFYQMLQDSYEKLNQELRSLYQNYRTREHLMNDFDKKIA"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.50, 0.70),
        "category": "dna_replication",
    },
    "rpoB": {
        "name": "rpoB",
        "protein": (
            "MSPERREQFVRDYIEAIKDPAKQKQNMDIVLPTSGFMSMQKGVIHVKPFSGSYEQLVQDLIAKF"
            "RADVVTEAGDVLGIFRQEVLPSMQAVVNKVDGIVFKDLTDYQKVLSVLNPEQVDQAVKELAASF"
            "NQKADTVCHQLSVKPFFRKLDKQGFSSQDILEITELLKEVSQKISDPLVRLSNADVMRQIYDKL"
            "PDSEFQKYLENEKTLSLPQIDNVLKYLPQLSKSPPEEVEADIPKHIIKALDVSKEQKKLEQYQD"
            "IVLLPMNIRATLEQSQKAEIEQELIRAIKTQAPEKVDLQERLQQLQKQLEQVKQEMADLLAKEK"
            "KQELQALINEAKELNEIPIIQDLAEKL"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.55, 0.80),
        "category": "transcription",
    },
    "rpoD": {
        "name": "rpoD",
        "protein": (
            "MQWPTQQEALRPKRAQTLSDYQQIFRAIEKKQADLVLLPEWLTDRRPKPEVQQMLEARVALSRD"
            "LQAEGRVLLIGDDATPALEKMRQLAESLGNVRLDILEQRLREQIRKRIDELMDETGKEVEFEVV"
            "RDLQEQIEKGLEPLMPSQRLDLSMIRKLAEGYQELIDRLLPGDQMPEAFETKLQDELRDMLRSR"
            "PFPFEPQQAMAVMLRQEREMALRMRSRLREKVRRDLAELNQELKEMLRSPSTQRRRSVQEAIDQ"
            "LVDQLRQAFEEQNLRQQLDQFRRRAEQLERQQRWLEQQVSQQMLAQQMREAQRRQMLEQQRSQQ"
            "QLREQQRQMYQQQLQQQQQQQQQQQQLQQQQQQQQQRQQQQQQPQLQQQRQPLQQQRQRQLPQQ"
            "QRLQQQRQRQLAQQQRLQKQQQLQQQRQRLAQQHRLQQQRLQQRQQLQQQRLQQQRQRLAQQHR"
            "LQQQRQQQAQQQRLQQQRLQQQRQQQLQQQRL"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.30, 0.55),
        "category": "transcription",
    },
    "dnaK": {
        "name": "dnaK",
        "protein": (
            "MAKDVKFGNDARVKMLRGVNVLADALKDYSQIEKAVDKNGKTLVELGGKPTPKIEQVSLTALGGK"
            "VVNKVAVKIPGEAMTLKVIEKDPKVKEVLRDIGGGTTFKELVDTKASADKDGVLVKSVKDRDKF"
            "DEIVKVVEKMKNEDKLKEVKTKLESKVVPFEKGKVNDSALDLGKQPEAPRGFSQVSVKVVISGT"
            "KDAQEVLKEALELNDKVKDEVVKPEAKKQVKDAVKKLFEGQKQLEQQTQKIIEAIEKDRVKTKL"
            "DVGQDKLLQGKDKVLEEQTKELQADIAELEKKQNQTVEVKQKKKQLKEEVEGKEKPTIEPTKA"
            "LQQQIEKLKEAVQKLREELLSGPNKKVMDVKRKEVKEKEEKEKEKGDKEKEKEKEKDGKVKTK"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.60, 0.85),
        "category": "chaperone",
    },
    "groEL": {
        "name": "groEL",
        "protein": (
            "MAKDVKFNGELVKFANDAVKVMLEQKPVTVLEQGMKDLRAINILKDAKVKGFKGEVKQIDKLGDG"
            "ILVSAVGPKTEALVEALKQYVETLADKVGRSVQVLDAVQEFNELEGWKVQGETQLEVKDQIVTK"
            "AFETLDEKGLQKLKNEMQRLDAGKILVTGVGQTEAHVDAKLNRVDMLMDKLVEAGVKVAGTVID"
            "LGKASAEADKLLKELEKGVKETVLPGGVVLTVADKAGLQAEVKEMEKLQDKVKARLEGVVVDTA"
            "VPAPVKELVQKMVKEMDQEKLQERIRAALEKAKELVKTRIAEEVKDALKDKAPLVDVKKEIEKR"
            "GIESKIIDKVIVAKVAK"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.65, 0.90),
        "category": "chaperone",
    },
    "tufA": {
        "name": "tufA",
        "protein": (
            "MAKQFSTKFDALVGVIAAAGKLSEKGKKVILFGVDAKKEDEKIDRLVNEVVKGIYPVTSEDFEYE"
            "KEKGKKVFLIPNMFEPVAAKILSEEGRRVGFKVKADVAGVASLDEQRRALRDAVAASIVTIKEG"
            "IDRLVSEVTGKIVEGSVAKDIKGKSPEEIERVLKNRIEGVNVIAVGAEGTSDTAKDVLASLVKL"
            "GDVVYEVDEAGKTYGEGFLRGVSEAMHSGKAVKIIDKVGGEAIQKEIVADAKLKEKGDVVIPEQ"
            "GKKVTEAFKRMLQGVDATLFDTDKVIQKVDGNAGDRLAVVCELMDDGKRLPVKVKGYQKLGANE"
            "RKNKAPQIIVTKYHPDINKNIDVGWLGDKPDAAPLFDLNEKDVRDFVKGKPVTVAVTDGKVNVS"
            "AAGAVAVIKDGGVKFN"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.75, 0.95),
        "category": "translation",
    },
    "infA": {
        "name": "infA",
        "protein": (
            "MASELIRKLAENAIKQAGFPEVMDAFRSQVNELLEKGFQIQVGFPSSKPQTDVDAVKLLEKQGRK"
            "RVVAPFIDRGAEKVIKAYSKGVKKPIKPQFADGMLGTVLTGKGRVKAVSGMVGAPGGAKGAKKV"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.55, 0.80),
        "category": "translation",
    },
    "fusA": {
        "name": "fusA",
        "protein": (
            "MSDITKLNRQIEKLLPKGILMGPVNTLAGADVLAVLEKRGVEKAGDIMVIFDSDGQKEVVAKLAGA"
            "KGKPSKTRAGRVAVCKPGDKELVVKRLPEKRVAFYGAPEQPVKLFVDINEAKQKLPEKVERELKE"
            "EVKQKQKIKDAQKVAAAVNKLGGRAVVQVKDGKTPRSMVGSYADKRFGKELATGKEVSQKTKEG"
            "EKSLEGKPGDKVIPVGKVGAKSPSEALAKKVRDKVVVFNAKGKEKDLVGVDVAVAEKEGKVVPAL"
            "KKVDGVEVVAKLKDGKKVVDVAKELKEKLKGAKVPEEMGKLGLAPVVQVMDKAKDGEVVKAVEAV"
            "KQGKKVVKGVVKVDEVKEKMKEKLANVQVKDAGKAKTPEEMGKEVGKGVVVQVLKEAKNPDVAA"
            "KVKEALDKAKTKKGMV"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.65, 0.85),
        "category": "translation",
    },
    "rpsA": {
        "name": "rpsA",
        "protein": (
            "MSKIFAQRTESYIDQLKELKADITPKALLEVLDQAKRKVANFIKNGLIKPGDELDVVKRVSSDKGF"
            "VGKKVNIKGTVKKAFELVKQAGDKVTLSGKKVAKMLEGKQVVDVERGNVKRVRRKLQVQNPEDAP"
            "RGTIKVAKVQADKPNTQKSIKVVRDADKVVLAKKQYEPDKIQVKADFTPKDKVMLKAGDVKDLPE"
            "YKQAIKATNKVLEKLGVKVKDPRVVIEKLRDNRKVIPKGKKEFKDKVNKLDGKIPEVKKRVQKLK"
            "DAEKGLVKVNKALDDALRKVGNVKAVAPKGTEILDKVDEKSVKMVNAKLMGQIKDKVAKLVKDVPK"
            "VKRAKDSKLVKAVDNLASRGKKVLAVSKNKVVDKLAALETNKVKRVDA"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.55, 0.75),
        "category": "translation",
    },
    "ampC": {
        "name": "ampC",
        "protein": (
            "MKTLLLTAVAGAVLAQPSLDSAQREAWLKELKQHPNPNITLKAFSTQNEGKLAEIADALKDKGEV"
            "LVVSTQRGMPVVKMNLFSGEKPDMTLFYKNSNPEGLPVFQGTPVDLKNLGKVIVDSFDDVNAVV"
            "RMQHGMAFHNFKQETLTNADVEIAHMLKGMVAFKDSQGPTLEILADELNKAKDQIAKLMGSQAK"
            "FQDKVVDALHRQLVAGMDAVKDLPAAMLKAGADVIKGTNPLVLDQVAKQLASQADLKILAAKSP"
            "LFKLAQKVKMGLKDTVKPGDALSLEKDLLQKAIEKHGDAVIKVVK"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.35, 0.60),
        "category": "resistance",
    },
    "araC": {
        "name": "araC",
        "protein": (
            "MPEQTQIKEKLAQRLGEGRKTLFNADIVAVNDLIFAAKRGDVVVGMLRDAVLPEAVERVLDAAFR"
            "RPAQIPRKLNCAVFVQEAYGIPESSRQRMLVEMVKKFDQGIEAIYDLFPAELRRRVSKGKNQVI"
            "GDNQMLAEAFDSAAYEALRRAAEAMFAKPNYHRTLNEMVDKLLNEKGVQAVKELVDPVKKVVVK"
            "KDSVQEVKDVMKLNEADLLQALRSDEQSLKDVEEFLQKLQQALKADPERKLAELAAEVAQLQES"
            "LRDKVKAEQAKLKDSKTEQLLAQIADFAQKMKDLDA"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.20, 0.45),
        "category": "regulatory",
    },
    "trpR": {
        "name": "trpR",
        "protein": (
            "MSIKELIEVQKGIVAKLEQFLPPVEQIKRILRKPGELKRLTLEQYAKQMEEAIRKLTEQFDKDVPQ"
            "RKRVLLDTTNLLAEIEKELRAQIDNIIEDVDALNKLKKEIEGELQKRLEQVIEKLMDAVAKRRRL"
            "SSNAIRKRLADYVK"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.25, 0.50),
        "category": "regulatory",
    },
    "malE": {
        "name": "malE",
        "protein": (
            "MKIKTGARILALSALTTMMFSASALAANDEKKKLTGQNITDKVVKMLDYADKKDVLGKDGEVTLAD"
            "SKSKKLGVKLTDGRVVTVNIDDLADALKRAGKDVVLGKVVKRVDSGHGEEVAGYIDEQSKALAKG"
            "VETVKDLADIVKDGFGEALTRDADKLAFEKQKGFEPQALAKVDNINGQVVFAQYAEQKAKEMGKK"
            "LPEELKEKFGFVVLKDAGVKMDAMAKPEEGKILYDAIPQADKMLAEKLKEAGAKVDIITKLNGDK"
            "AVAEVKELKEKLKGDVNVPVKLANIFEGQKVSDEELKAQAKKLGFKDKVNAKIELADAKKLNKLA"
            "DKVK"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.45, 0.70),
        "category": "transport",
    },
    "ompA": {
        "name": "ompA",
        "protein": (
            "MKKTAIAIAVALAGFATVAQAAPKDNTWYTGAKLGWSQYHDTGFINNNGPTHENQLGAGAFGGYQ"
            "VNPYVGFEMGYDWLGRMPYKGSVENGAYKAQGVQLTAKLGYPITDDLDIYTRLGGMVWRADTKS"
            "NVYGKNHDTGVSPVFAGGVEYAITPEIATRLEYQWTNNIGDAHTIGTRPDNGMLSLGVSYRFGQG"
            "EAPVMGYTKELDTDALAGANRLGVAYRADKAQEYDGKVVVSLYDAKMGDYKDANTYGKLPGVQYT"
            "DA"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.55, 0.80),
        "category": "membrane",
    },
    "ompC": {
        "name": "ompC",
        "protein": (
            "MKVKVLSLLVPALLVAGAANAADKNYGVKLDFNGLSIEQVSSKDQVGATVNNYNVARAYLKGSQD"
            "AYSYGVNWSDQTYAGLSDYRYKNSVRFYKGYNVDYDGKYVDYSADFHTYKDTNNVVFVDENGFN"
            "VSVNRGELVGDKEAQVNVNLTYDADNKNYAFVDLNYNDGNVDVYKRADKFDSRFGLNADVDYNRY"
            "VADVGSKNKGIVLGFGKFQDTVGVYYNYKFQDNSNNYGGVNTDNYGFKLNYGNNVNYDFTDKYYK"
            "IKDAGKYNKDVFYNGEKLNYNNYGFNNVDGYGKYGFNNVEY"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.55, 0.80),
        "category": "membrane",
    },
    "cat": {
        "name": "cat",
        "protein": (
            "MEKKITGYTLVDKIDEAIAKAFNKIKESYKDPEKFMKVTIDNLVKQKYDKNIIKELGENYFDLSF"
            "VKGDQVVVFVDDSVRDMQTEVVDKLLELITPKDKVFIEQKRKHGFKLVMQADYALNVKGDSLEL"
            "LRSIGFGSFAPYDQDYQFKELDAMRKYTNDIFAKMLELKPEKELQNQAFEFKELDAKMLELKSD"
            "FVKELDAMR"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.35, 0.60),
        "category": "resistance",
    },
    "xylA": {
        "name": "xylA",
        "protein": (
            "MKTKVLLALSALSLSAFSSAQSADKIRKYIAEKQGKPVLVISRPKFENPKVVLANAGMAGTAYAL"
            "DRDLDSKLGNVIKMVASRAGLADKADVVLFTSDYEGKLSVTFRDPPIYPVNSKVSLMVNDAFGW"
            "KHAIPKLFEQDIKPMVNAGEMVQVTGDKQASMRDWLVPGHRVDTLFDPIVRGKLVSQDLKEKLA"
            "YAKQFGVDFKSPYTVNVIQPTLEDKLKAALMDKVKSKLTPEQIADILADFVQMKQAGLDVKTLR"
            "DFGVEQLEDALRKALQKAHEQLADKAEKMKQKLKELQEKLAEK"
        ),
        "organism": "Escherichia coli",
        "expected_cai_range": (0.30, 0.55),
        "category": "metabolic",
    },
}


# ---------------------------------------------------------------------------
# Human Therapeutic Gene Set
# ---------------------------------------------------------------------------
# Core human therapeutic proteins with extended metadata for benchmarking
# codon optimization in mammalian expression systems.

HUMAN_THERAPEUTIC: dict[str, dict] = {
    "INS": {
        "name": "INS",
        "protein": (
            "MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQV"
            "GQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN"
        ),
        "organism": "Homo sapiens",
        "expected_cai_range": (0.55, 0.85),
        "category": "therapeutic",
    },
    "GH1": {
        "name": "GH1",
        "protein": (
            "MATGSRTSLLLAFGLLCLPWLQEGSAFPTIPLSRLFDNAMLRAHRLHQLAFDTYQEFEEAYIPK"
            "EQKYSFLQNPQTSLCFSESIPTPSNREETQQKSNLELLRISLLLIQSWLEPVQFLRSVFANSLV"
            "YGASDSNVYDLLKDLEEGIQTLMGRLEDGSPRTGQIFKQTYSKFDTNSHNDDALLKNYGLLYCFR"
            "KDMDKVETFLRIVQCRSVEGSCGF"
        ),
        "organism": "Homo sapiens",
        "expected_cai_range": (0.50, 0.80),
        "category": "therapeutic",
    },
    "IFNA2": {
        "name": "IFNA2",
        "protein": (
            "MALTFALLVALLVLSCKSSCSVGCDLPQTHSLGSRRTLMLLAQMRRISLFSCLKDRHDFGFPQE"
            "EFGNQFQKAETIPVLHEMIQQIFNLFSTKDSSAAWDETLLDKFYTELYQQLNDLEACVIQGVGV"
            "TETPLMKEDSILAVRKYFQRITLYLKEKKYSPCAWEVVRAEIMRSFSLSTNLQESLRSKE"
        ),
        "organism": "Homo sapiens",
        "expected_cai_range": (0.50, 0.80),
        "category": "therapeutic",
    },
    "EPO": {
        "name": "EPO",
        "protein": (
            "MGVHECPAWLWLLLSLLSLPLGLPVLGAPPRLICDSRVLERYLLEAKEAENITTGCAEHCSLNE"
            "NITVPDTKVNFYAWKRMEVGQQAVEVWQGLALLSEAVLRGQALLVNSSQPWEPLQLHVDKAVSG"
            "LRSLTTLLRALGAQKEAISPPDAASAAPLRTITADTFRKLFRVYSNFLRGKLKLYTGEACRTGD"
            "R"
        ),
        "organism": "Homo sapiens",
        "expected_cai_range": (0.50, 0.80),
        "category": "therapeutic",
    },
    "CSF3": {
        "name": "CSF3",
        "protein": (
            "MAGPATQSPMKLMALQLLLWHSALWTVQEATPLGPASSLPQSFLLKCLEQVRKIQGDGAALQEK"
            "LVSECATYKLCHPEELVLLGHSLGIPWAPLSSCPSQALQLAGCLSQLHSGLFLYQGLLQALEGIS"
            "PELGPTLDTLQLDVADFATTIWQQMEELGMAPALQPTQGAMPAFASAFQRRAGGVLVASHLQSFL"
            "EVSYRVLRHLAQP"
        ),
        "organism": "Homo sapiens",
        "expected_cai_range": (0.45, 0.75),
        "category": "therapeutic",
    },
}


# ---------------------------------------------------------------------------
# Human Signaling Gene Set
# ---------------------------------------------------------------------------
# Human signaling proteins including receptor tyrosine kinases and immune
# checkpoint molecules, commonly targeted in biopharmaceutical development.

HUMAN_SIGNALING: dict[str, dict] = {
    "EGFR": {
        "name": "EGFR",
        "protein": (
            "MRPSGTAGAALLALLAALCPASRALEEKKVCQGTSNKLTQLGTFEDHFLSLQRMFNNCEVVLGN"
            "LEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDAN"
            "KGLIGLGLAALALVVGIVLYGVTLPLKGVHEKKAFGKFVKKDCQGTHSPPVAPWMLLLLSLVLL"
            "GACLVLGVWEFQGVQCSESKVLLQELQTKVGEKKTKQLELSRFEKLQMYNLENLKDKEDDKVSS"
            "VLQDRVKPMKELSDLRIPLSMNVKDDIESLKQKLQDMENELDEQMDNQLEDKLQEQLDQLSDQE"
            "RDLLEDENEKLQEQLNQLSESQLTEMDNQLEDKLQEQLNQLSESQLTEMDKQLEDKLQDSLNQL"
            "SEQQLEAEFSELQDFL"
        ),
        "organism": "Homo sapiens",
        "expected_cai_range": (0.40, 0.70),
        "category": "signaling",
    },
    "ERBB2": {
        "name": "ERBB2",
        "protein": (
            "MELAALCRWGLLLALLPPGAASTQVCTGTDMKLRLPASPETHLDMLRHLYQGCQVVQGNLEITY"
            "VQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKGLIGL"
            "GLAFLVLGGIVLYGVTLPLKGVHEKKAFGKFVKKDCQGTHSPPVAPWMLLLLSLVLLGACLVLGV"
            "WEFQGVQCSESKVLLQELQTKVGEKKTKQLELSRFEKLQMYNLENLKDKEDDKVSSVLQDRVKPM"
            "KELSDLRIPLSMNVKDDIESLKQKLQDMENELDEQMDNQLEDKLQEQLDQLSDQERDLLEDENEKL"
            "QEQLNQLSESQLTEMDNQLEDKLQEQLNQLSESQLTEMDKQLEDKLQDSLNQLSEQQLEAEFSEL"
            "QDFL"
        ),
        "organism": "Homo sapiens",
        "expected_cai_range": (0.40, 0.70),
        "category": "signaling",
    },
    "VEGFA": {
        "name": "VEGFA",
        "protein": (
            "MNFLLSWVHWSLALLLYLHHAKWSQAAPMAEGGGQNHHEVVKFMDVYQRSYCHPIETLVDIFQE"
            "YPDEIEYIFKPSCVPLMRCGGCCNDEGLECVPTEESNITMQIMRIKPHQGQHIGEMSFLQHNKCE"
            "CRPKKDRARQENPCGPCSERRKHLFVQDPQTCKCSCKNTDSRCKARQLELNERTCRCDKPRR"
        ),
        "organism": "Homo sapiens",
        "expected_cai_range": (0.45, 0.75),
        "category": "signaling",
    },
    "PDCD1": {
        "name": "PDCD1",
        "protein": (
            "MWVLFLLLLLWGTQGAQIVTDQTTVQAPVSQVDGTEVSIVCRGEDAKPEVSLRWQLDSRLEQATA"
            "FQKVTQVGAGLALISLWLMLAGVLLLTMQRQGAGAPRGPAPEALSSSPSPTLQASQSPGAPVSGP"
            "SPPAAPPSPAPPTSPAPTPSPAPVPTSPATPSPGGPTSPASPSSPGAPPEAAGLDTQPEAGPPSP"
            "SPEEVAPAPAPAPAPAPAPAPAEAPSPAPAPASAPAPAPAE"
        ),
        "organism": "Homo sapiens",
        "expected_cai_range": (0.35, 0.65),
        "category": "signaling",
    },
}


# ---------------------------------------------------------------------------
# Yeast Industrial Enzyme Gene Set
# ---------------------------------------------------------------------------
# Industrial enzymes produced in yeast expression systems for biotechnology
# applications including food, fuel, and materials processing.

YEAST_INDUSTRIAL: dict[str, dict] = {
    "SUC2": {
        "name": "SUC2",
        "protein": (
            "MLLQAFLPFLSATVAAYSMLFNSQTQWLTSSNSSSVLLGSTQSVAPFSLFNTTQFSPATATSNLS"
            "TIDAYVPQTSINLSLPPSTVSSSNNSVSSNNNPLVNSGNVSLQNLSVTNSNSSLQSTSNGLSLS"
            "TVTNSNGQSSLVTSSNQTSGYLSVTSSNTNSQNPSLSSQSILTVSSSNQSISLSVTSSSNQTVST"
            "SSTTQTTGSFTVSNQSLSLPSSQSILTVSSSNQSVGLSLPQSISLSVTSSSNQTVSTSSTTQTTG"
            "SFTVSNQSLSLPSSQNTLGFTVTSSNNQSTSTSTNTNLKFSKVAPTLPAEWKEVISAYKPWHIEP"
            "IYVLSQDSNRFKELDENKVVQDLHDYISVDFTTGGDYLDYVQKGYVIVPWGIDPQNKSVFNRNGF"
            "YGSTFSYYDVSLEELHPVAKELGKPYRLVVTLDSAKNMDTDYFDSVHFKHIQSMNADFVDWVTDN"
            "KLMYVDGWTLDPRVRGKLPAGYFHNQCGCANWPNQPLSTVLSANLTSSNHVTLGDFASLYSIYGD"
            "NPGVYKVLTNVTENDSWVYGRQLFPNDSFATKYDVTLVGQVGLSASNKQFELVDGLKNTVYFFEH"
            "GNKGRPAQFSLPNITLPDGQFNLFGDANFNDIFNRL"
        ),
        "organism": "Saccharomyces cerevisiae",
        "expected_cai_range": (0.40, 0.70),
        "category": "industrial",
    },
    "AMY1": {
        "name": "AMY1",
        "protein": (
            "MAVLLLFSLSLLQSSSALAQPTVYGYLYAQPDNQSAGFTLSGNKYMSELYNLADNLYFITDSQN"
            "VYYVNSQTGIQYPDNQWAGLNSWYDNNDKSKWLYGKPNLLSLNNDYNQLLSKDNTYYIDSNQTF"
            "VQLADNQYFSKYKPNKTPYQYIFTTDRNGKNYQFTLQDRDGKTFTLVDPAPLYSLFNRL"
        ),
        "organism": "Saccharomyces cerevisiae",
        "expected_cai_range": (0.35, 0.60),
        "category": "industrial",
    },
    "CEL3A": {
        "name": "CEL3A",
        "protein": (
            "MKLFLVATAAAVLSATQAAPDNSKLQYTLYQQHTLRDDVAVVFVDRSPVNHLGDVASFYHNYKDT"
            "NDSFRSLINYGWQNNRQELQRYVNKAQGQGIRSAPSIWDSTVNDSVYVDFKDAIHPQYTLKNYT"
            "FLNDSYVKSKLGDSFSFNNSYVDKAKDKNIYVFDENNRQELNKVKDYFGLNDIKRYKDDDFVLQ"
            "KDKYFVFDENNRQELNKVKDYFGLNDIKRYKDDDFVLQKDKYFVFDENNRQELNKIKNYFGLND"
            "IKEYK"
        ),
        "organism": "Saccharomyces cerevisiae",
        "expected_cai_range": (0.35, 0.60),
        "category": "industrial",
    },
}


# ---------------------------------------------------------------------------
# Mouse Model Organism Protein Gene Set
# ---------------------------------------------------------------------------
# Common mouse proteins used as model systems in preclinical studies and
# benchmarking cross-species codon optimization performance.

MOUSE_MODEL: dict[str, dict] = {
    "ALB_MOUSE": {
        "name": "ALB_MOUSE",
        "protein": (
            "MKWVTFISLLLLFSSAYSRGVFRRDAHKSEVAHRFKDLGEENFKALVLIAFAQYLQQCPFEDHVK"
            "LVNEVTEFAKTCVADESAENCDKSLHTLFGDKLCTVATLRETYGEMADCCAKQEPERNECFLQHK"
            "DDNPNLPRLVRPEVDVMCTAFHDNEETFLKKYLYEIARRHPYFYAPELLYYANKYNGVFQECCKA"
            "EDKHACAEKDAFLGSFLYEYSRRHPEYAVSVLLRLAKTYETTLEKCCAAADPHECYAKVFDEFKP"
            "LVEEPQNLIKQNCELFEQLGEYKFQNALLVRYTKKVPQVSTPTLVEVSRSLGKVGTRCCTKPES"
            "ERMPCTEDYLSLILNRLCVLHEKTPVSEKVTKCCTESLVNRRPCFSALTPDETYVPKAFDEKLFT"
            "FHADICTLPDTEKQIKKQTALVELLKHKPKATEEQLKTVMENFVAFVDKCCAADDKEACFAVEGP"
            "KLRELIQAFPED"
        ),
        "organism": "Mus musculus",
        "expected_cai_range": (0.55, 0.80),
        "category": "model_organism",
    },
    "IGG1_MOUSE": {
        "name": "IGG1_MOUSE",
        "protein": (
            "EVQLQQSGAELARPGASVKLSCKASGYTFTSYWMHWVKQRPGQGLEWIGEIDPSDSYTNYNQKFK"
            "DKATLTVDKSSSTAYMQLSSLTSEDSAVYYCARGNYYGSSFDYWGQGTTLTVSSAKTTPPSVYPL"
            "APGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSPRP"
            "SETVTCNVAHPASSTKVDKKIVPRDCGCKPCICTVPEVSSVFIFPPKPKDVLTITLTPKVTCVVVD"
            "ISKDDPEVQFSWFVDDVEVHTAQTQPREEQFNSTFRSVSELPIMHQDWLNGKEFKCRVNSAAFP"
            "APIEKTISKTKGRPKAPQVYTIPPPKEQMAKDKVSLTCMITDFFPEDITVEWQWNGQPAENYKNT"
            "QPIMNTNGSYFVYSKLNVQKSNWEAGNTFTCSVLHEGLHNHHTEKSLSHSPGK"
        ),
        "organism": "Mus musculus",
        "expected_cai_range": (0.45, 0.75),
        "category": "model_organism",
    },
    "TP53_MOUSE": {
        "name": "TP53_MOUSE",
        "protein": (
            "MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPDEAPR"
            "MPEAAPPVAPAPAAPTPAAPAPAPSWPLSSSVPSQKTYPQGLNGTVNLPGRNSFEVRVCACPGRDR"
            "RTEEENLHKTTGIMFGSGFVFLKIDRPNVSHLVKAKNQYLRDHLRRRFSHDDSLVTSGPQNDLQP"
            "TLVTRYLNQLLGSVLAQPSLLGSDSLMNAHHGVAQAPRGALRRLVEALSDQQLTGNLERLLRRAE"
            "QAEGAPAPTPSMVTSAAPSPATSTSWMEEPKVEQVDLPHDLEGSQDLDLPSQPPPPPPSHLPTPS"
            "SGALQASTSALCSPSRPSTPSPPPLLRPQQASLPSAAPAPATSQTPEQPPSAIPAPPQPLSPVRGC"
            "RAQEQQ"
        ),
        "organism": "Mus musculus",
        "expected_cai_range": (0.40, 0.65),
        "category": "model_organism",
    },
    "HBB_MOUSE": {
        "name": "HBB_MOUSE",
        "protein": (
            "MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFDSFGDLSSPDAVMGNPKVKAHGK"
            "KVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLD"
            "KFLASVSTVLTSKYR"
        ),
        "organism": "Mus musculus",
        "expected_cai_range": (0.55, 0.80),
        "category": "model_organism",
    },
    "INS_MOUSE": {
        "name": "INS_MOUSE",
        "protein": (
            "MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPMSRREAEDLQVGQ"
            "VELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN"
        ),
        "organism": "Mus musculus",
        "expected_cai_range": (0.55, 0.85),
        "category": "model_organism",
    },
    "ACTB_MOUSE": {
        "name": "ACTB_MOUSE",
        "protein": (
            "MDDDIAALVVDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYVGDEAQSKRGIL"
            "TLKYPIEHGIVTNWDDMEKIWHHTFYNELRVAPEEHPVLLTEAPLNPKANREKMTQIMFETFNTP"
            "AMYVAIQAVLSLYASGRTTGIVLDSGDGVTHNVPIYEGYALPHAIMRLDLAGRDLTDYLMKILTER"
            "GYSFVTTAEREIVRDIKEKLCYVALDFENEMATAASSSSLEKSYELPDGQVITIGNERFRCPETLF"
            "QPSFIGMESAGIHETTYNSIMKCDIDIRKDLYANTVLSGGTTMYPGIADRMQKEITALAPSTMKIK"
            "IIAPPERKYSVWIGGSILASLSTFQQMWISKQEYDESGPSIVHRKCF"
        ),
        "organism": "Mus musculus",
        "expected_cai_range": (0.60, 0.85),
        "category": "model_organism",
    },
}


# ---------------------------------------------------------------------------
# Aggregation helper
# ---------------------------------------------------------------------------

def get_all_gene_sets() -> dict[str, dict]:
    """Return all gene sets merged into a single dict.

    In case of key collisions, later sets overwrite earlier ones.
    The merge order is:
      HUMAN_THERAPEUTIC_GENES -> VACCINE_ANTIGEN_GENES -> STRESS_TEST_GENES
      -> E_COLI_EXTENDED -> HUMAN_THERAPEUTIC -> HUMAN_SIGNALING
      -> YEAST_INDUSTRIAL -> MOUSE_MODEL.
    """
    merged: dict[str, dict] = {}
    merged.update(HUMAN_THERAPEUTIC_GENES)
    merged.update(VACCINE_ANTIGEN_GENES)
    merged.update(STRESS_TEST_GENES)
    merged.update(E_COLI_EXTENDED)
    merged.update(HUMAN_THERAPEUTIC)
    merged.update(HUMAN_SIGNALING)
    merged.update(YEAST_INDUSTRIAL)
    merged.update(MOUSE_MODEL)
    return merged


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _validate_sequences() -> None:
    """Validate all gene set sequences at module load time.

    Checks that every sequence:
      1. Contains only valid single-letter amino acid codes
    """
    valid_aa = set("ACDEFGHIKLMNPQRSTVWY")
    errors: list[str] = []

    # Legacy sets use 'protein_sequence' key
    legacy_sets = [
        ("HUMAN_THERAPEUTIC_GENES", HUMAN_THERAPEUTIC_GENES),
        ("VACCINE_ANTIGEN_GENES", VACCINE_ANTIGEN_GENES),
        ("STRESS_TEST_GENES", STRESS_TEST_GENES),
    ]
    # New extended sets use 'protein' key
    extended_sets = [
        ("E_COLI_EXTENDED", E_COLI_EXTENDED),
        ("HUMAN_THERAPEUTIC", HUMAN_THERAPEUTIC),
        ("HUMAN_SIGNALING", HUMAN_SIGNALING),
        ("YEAST_INDUSTRIAL", YEAST_INDUSTRIAL),
        ("MOUSE_MODEL", MOUSE_MODEL),
    ]

    for gene_set_name, gene_set in legacy_sets:
        for name, entry in gene_set.items():
            seq = entry.get("protein_sequence", "")
            if not seq:
                errors.append(
                    f"{gene_set_name}[{name}]: empty or missing sequence"
                )
                continue

            # Check for invalid characters
            invalid = set(seq) - valid_aa
            if invalid:
                errors.append(
                    f"{gene_set_name}[{name}]: invalid amino acids: {invalid}"
                )

    for gene_set_name, gene_set in extended_sets:
        for name, entry in gene_set.items():
            seq = entry.get("protein", "")
            if not seq:
                errors.append(
                    f"{gene_set_name}[{name}]: empty or missing protein sequence"
                )
                continue

            # Check for invalid characters
            invalid = set(seq) - valid_aa
            if invalid:
                errors.append(
                    f"{gene_set_name}[{name}]: invalid amino acids: {invalid}"
                )

    if errors:
        import logging
        logger = logging.getLogger(__name__)
        for err in errors:
            logger.error("Gene set validation error: %s", err)
        raise ValueError(
            f"Gene set validation failed with {len(errors)} error(s): "
            + "; ".join(errors)
        )


# Run validation on import (fail-fast for incorrect data)
_validate_sequences()
