"""Type stubs for biocompiler.cli — Command-line interface."""

from __future__ import annotations

import argparse
from typing import List, Optional


# ────────────────────────────────────────────────────────────
# Public functions
# ────────────────────────────────────────────────────────────

def main() -> None:
    """Entry point for the biocompiler CLI."""
    ...

def build_parser() -> argparse.ArgumentParser:
    """Build and return the argument parser for the CLI."""
    ...

def verify(seq: str, cert_text: str) -> bool:
    """Verify a certificate against a DNA sequence."""
    ...

def colorize(text: str, *codes: str) -> str:
    """Wrap text in ANSI escape codes; no-op when stdout is not a TTY."""
    ...


# ────────────────────────────────────────────────────────────
# Command handlers
# ────────────────────────────────────────────────────────────

def cmd_optimize(args: argparse.Namespace) -> None: ...
def cmd_batch(args: argparse.Namespace) -> None: ...
def cmd_check(args: argparse.Namespace) -> None: ...
def cmd_benchmark(args: argparse.Namespace) -> None: ...
def cmd_scan(args: argparse.Namespace) -> None: ...
def cmd_structure(args: argparse.Namespace) -> None: ...
def cmd_stability(args: argparse.Namespace) -> None: ...
def cmd_solubility(args: argparse.Namespace) -> None: ...
def cmd_immunogenicity(args: argparse.Namespace) -> None: ...
def cmd_assess(args: argparse.Namespace) -> None: ...
def cmd_validate_cai(args: argparse.Namespace) -> None: ...
def cmd_validate_maxentscan(args: argparse.Namespace) -> None: ...
def cmd_whatif(args: argparse.Namespace) -> None: ...
def cmd_explain(args: argparse.Namespace) -> None: ...
def cmd_report(args: argparse.Namespace) -> None: ...
