"""Deprecated: use biocompiler.provenance.slot_verification instead."""
import warnings

warnings.warn(
    "biocompiler.slot_verification is deprecated — use biocompiler.provenance.slot_verification instead",
    DeprecationWarning,
    stacklevel=2,
)

from biocompiler.provenance.slot_verification import *  # noqa: F401,F403

__all__ = [
    "SLOT_PREDICATES",
    "is_slot_predicate",
    "VerificationEvidence",
    "verify_no_cryptic_splice",
    "verify_no_cryptic_promoter",
    "verify_no_unexpected_tm_domain",
    "verify_mrna_secondary_structure",
    "verify_co_translational_folding",
    "verify_conservation_score",
    "verify_codon_optimality",
    "verify_structure_predicate",
    "verify_stability_predicate",
    "verify_solubility_predicate",
    "verify_immunogenicity_predicate",
    "verify_soundness",
    "SoundnessReport",
    "SoundnessResult",
    "verify_slot_predicate",
    "_recheck_predicate",
    "_check_esmfold_available",
    "_apply_recheck_to_soundness",
    "_recheck_core_predicate",
    "_check_foldx_available",
    "_check_camsol_available",
    "_check_mhc_available",
    "_check_maxent_available",
    "_STRUCTURE_PREDICATES",
    "_STABILITY_PREDICATES",
    "_SOLUBILITY_PREDICATES",
    "_IMMUNOGENICITY_PREDICATES",
    "_PERMISSIVE_SPLICE_RELAXATION",
    "_PERMISSIVE_PROMOTER_RELAXATION",
    "_PERMISSIVE_TM_RELAXATION",
    "_PERMISSIVE_DG_RELAXATION",
    "_PERMISSIVE_CAI_RELAXATION",
    "_PERMISSIVE_BLOSUM_RELAXATION",
    "_BLOSUM_MIN_SCORE_FLOOR",
    "_TM_WINDOW_SIZE",
    "_VERIFIED_STABLE_DG_KCAL",
    "_PERMISSIVE_STABLE_DG_KCAL",
    "_PERMISSIVE_BORDERLINE_DG_KCAL",
    "_VERIFIED_SOLUBILITY_THRESHOLD",
    "_PERMISSIVE_SOLUBILITY_THRESHOLD",
    "_BORDERLINE_SOLUBILITY_FACTOR",
]
