"""
Sharp & Li (1987) Reference Gene Sets for CAI Computation
==========================================================

This module provides the original Sharp & Li reference gene sets for
*Escherichia coli* and *Saccharomyces cerevisiae*, enabling direct
comparison of computed CAI values with the published results from:

  Sharp, P.M. & Li, W.-H. (1987). "The codon Adaptation Index — a measure
  of directional synonymous codon usage bias, and its potential applications."
  *Nucleic Acids Research* 15:1281–1295.  doi:10.1093/nar/15.3.1281

The reference sets contain:
  1. Gene CDS sequences for the highly expressed genes used as the
     reference set in the original paper.
  2. Per-thousand codon frequencies aggregated from those genes.
  3. CAI relative-adaptiveness weights derived from the codon frequencies.

A ``compute_cai_with_reference()`` function is provided that computes CAI
using the Sharp-Li weights, supporting both *E. coli* and *S. cerevisiae*
with the ``"sharp_li"`` reference option.

Published validation targets (Sharp & Li 1987, Table 4):
  Yeast:
    ADH1  = 0.91
    PGK1  = 0.88
    ENO1  = 0.72
    ACT1  = 0.56
  E. coli:
    groEL = 0.76
    recA  = 0.59
    dnaK  = 0.56
"""

from __future__ import annotations

import math
import threading
from typing import Dict

__all__ = [
    # E. coli
    "ECOLI_SHARP_LI_REFERENCE_GENES",
    "ECOLI_SHARP_LI_CODON_USAGE",
    "ECOLI_SHARP_LI_CAI_WEIGHTS",
    # Yeast
    "YEAST_SHARP_LI_REFERENCE_GENES",
    "YEAST_SHARP_LI_CODON_USAGE",
    "YEAST_SHARP_LI_CAI_WEIGHTS",
    # Published reference values
    "SHARP_LI_PUBLISHED_CAI",
    # Combined / generic names (used by organisms/__init__.py)
    "SHARP_LI_REFERENCE_GENES",
    "SHARP_LI_CODON_USAGE",
    "SHARP_LI_CAI_WEIGHTS",
    "get_sharp_li_cai_weights",
    "_sharp_li_registry_lock",
    # Function
    "compute_cai_with_reference",
]

# ---------------------------------------------------------------------------
# Standard genetic code (standalone — no external import needed)
# ---------------------------------------------------------------------------

_CODON_TABLE: Dict[str, str] = {
    "TTT": "F", "TTC": "F", "TTA": "L", "TTG": "L",
    "CTT": "L", "CTC": "L", "CTA": "L", "CTG": "L",
    "ATT": "I", "ATC": "I", "ATA": "I", "ATG": "M",
    "GTT": "V", "GTC": "V", "GTA": "V", "GTG": "V",
    "TCT": "S", "TCC": "S", "TCA": "S", "TCG": "S",
    "CCT": "P", "CCC": "P", "CCA": "P", "CCG": "P",
    "ACT": "T", "ACC": "T", "ACA": "T", "ACG": "T",
    "GCT": "A", "GCC": "A", "GCA": "A", "GCG": "A",
    "TAT": "Y", "TAC": "Y", "TAA": "*", "TAG": "*",
    "CAT": "H", "CAC": "H", "CAA": "Q", "CAG": "Q",
    "AAT": "N", "AAC": "N", "AAA": "K", "AAG": "K",
    "GAT": "D", "GAC": "D", "GAA": "E", "GAG": "E",
    "TGT": "C", "TGC": "C", "TGA": "*", "TGG": "W",
    "CGT": "R", "CGC": "R", "CGA": "R", "CGG": "R",
    "AGT": "S", "AGC": "S", "AGA": "R", "AGG": "R",
    "GGT": "G", "GGC": "G", "GGA": "G", "GGG": "G",
}

_AA_TO_CODONS: Dict[str, list] = {}
for _codon, _aa in _CODON_TABLE.items():
    if _aa != "*":
        _AA_TO_CODONS.setdefault(_aa, []).append(_codon)

_STOP_CODONS: set = {"TAA", "TAG", "TGA"}
_MIN_ADAPTIVENESS: float = 0.01  # Sharp & Li recommended floor


# ═══════════════════════════════════════════════════════════════════════════
# E. coli Sharp-Li Reference Set
# ═══════════════════════════════════════════════════════════════════════════
# The original Sharp & Li (1987) E. coli reference set consisted of 24
# highly expressed genes: ribosomal proteins, elongation factors, outer
# membrane proteins, and RNA polymerase subunits.
#
# Gene CDS sequences from E. coli K-12 MG1655 (U00096.3).
# ═══════════════════════════════════════════════════════════════════════════

ECOLI_SHARP_LI_REFERENCE_GENES: Dict[str, str] = {
    # ----------------------------------------------------------------
    # groEL (b4143) — 60 kDa chaperonin, 548 aa
    # Highly expressed chaperone; published CAI = 0.76 (Sharp & Li 1987)
    # CDS from E. coli K-12 MG1655 (NC_000913.3), minus strand
    # ----------------------------------------------------------------
    "groEL": (
        "ATGGCAGCTAAAGACGTAAAATTCGGTAACGACGCTCGTGTGAAAATGCTGCGCGGCGTAAACGTACTGGCAG"
        "ATGCAGTGAAAGTTACCCTCGGTCCAAAAGGCCGTAACGTAGTTCTGGATAAATCTTTCGGTGCACCGACCATC"
        "ACCAAAGATGGTGTTTCCGTTGCTCGTGAAATCGAACTGGAAGACAAGTTCGAAAATATGGGTGCGCAGATGG"
        "TGAAAGAAGTTGCCTCTAAAGCAAACGACGCTGCAGGCGACGGTACCACCACTGCAACCGTACTGGCTCAGGC"
        "TATCATCACTGAAGGTCTGAAAGCTGTTGCTGCGGGCATGAACCCGATGGACCTGAAACGTGGTATCGACAAA"
        "GCGGTTACCGCTGCAGTTGAAGAACTGAAAGCGCTGTCCGTACCATGCTCTGACTCTAAAGCGATTGCTCAGG"
        "TTGGTACCATCTCCGCTAACTCCGACGAAACCGTAGGTAAACTGATCGCTGAAGCGATGGACAAAGTCGGTAA"
        "AGAAGGCGTTATCACCGTTGAAGACGGTACCGGTCTGCAGGACGAACTGGACGTGGTTGAAGGTATGCAGTTC"
        "GACCGTGGCTACCTGTCTCCTTACTTCATCAACAAGCCGGAAACTGGCGCAGTAGAACTGGAAAGCCCGTTCA"
        "TCCTGCTGGCTGACAAGAAAATCTCCAACATCCGCGAAATGCTGCCGGTTCTGGAAGCTGTTGCCAAAGCAGGC"
        "AAACCGCTGCTGATCATCGCTGAAGATGTAGAAGGCGAAGCGCTGGCAACTCTGGTTGTTAACACCATGCGTGG"
        "CATCGTGAAAGTCGCTGCGGTTAAAGCACCGGGCTTCGGCGATCGTCGTAAAGCTATGCTGCAGGATATCGCAA"
        "CCCTGACTGGCGGTACCGTGATCTCTGAAGAGATCGGTATGGAGCTGGAAAAAGCAACCCTGGAAGACCTGGGT"
        "CAGGCTAAACGTGTTGTGATCAACAAAGACACCACCACTATCATCGATGGCGTGGGTGAAGAAGCTGCAATCCA"
        "GGGCCGTGTTGCTCAGATCCGTCAGCAGATTGAAGAAGCAACTTCTGACTACGACCGTGAAAAACTGCAGGAAC"
        "GCGTAGCGAAACTGGCAGGCGGCGTTGCAGTTATCAAAGTGGGTGCTGCTACCGAAGTTGAAATGAAAGAGAA"
        "AAAAGCACGCGTTGAAGATGCCCTGCACGCGACCCGTGCTGCGGTAGAAGAAGGCGTGGTTGCTGGTGGTGGT"
        "GTTGCGCTGATCCGCGTAGCGTCTAAACTGGCTGACCTGCGTGGTCAGAACGAAGACCAGAACGTGGGTATCA"
        "AAGTTGCACTGCGTGCAATGGAAGCTCCGCTGCGTCAGATCGTATTGAACTGCGGCGAAGAACCGTCTGTTG"
        "TTGCTAACACCGTTAAAGGCGGCGACGGCAACTACGGTTACAACGCAGCAACCGAAGAATACGGCAACATGATC"
        "GACATGGGTATCCTGGATCCAACCAAAGTAACTCGTTCTGCTCTGCAGTACGCAGCTTCTGTGGCTGGCCTGA"
        "TGATCACCACCGAATGCATGGTTACCGACCTGCCGAAAAACGATGCAGCTGACTTAGGCGCTGCTGGCGGTAT"
        "GGGCGGCATGGGTGGCATGGGCGGCATGATGTAA"
    ),
    # ----------------------------------------------------------------
    # recA (b2699) — RecA protein, 353 aa
    # DNA recombination/repair protein; published CAI = 0.59 (Sharp & Li 1987)
    # CDS from E. coli K-12 MG1655 (NC_000913.3), minus strand
    # ----------------------------------------------------------------
    "recA": (
        "ATGGCTATCGACGAAAACAAACAGAAAGCGTTGGCGGCAGCACTGGGCCAGATTGAGAAACAATTTGGTAAAGGC"
        "TCCATCATGCGCCTGGGTGAAGACCGTTCCATGGATGTGGAAACCATCTCTACCGGTTCGCTTTCACTGGATAT"
        "CGCGCTTGGGGCAGGTGGTCTGCCGATGGGCCGTATCGTCGAAATCTACGGACCGGAATCTTCCGGTAAAACC"
        "ACGCTGACGCTGCAGGTGATCGCCGCAGCGCAGCGTGAAGGTAAAACCTGTGCGTTTATCGATGCTGAACACG"
        "CGCTGGACCCAATCTACGCACGTAAACTGGGCGTCGATATCGACAACCTGCTGTGCTCCCAGCCGGACACCGG"
        "CGAGCAGGCACTGGAAATCTGTGACGCCCTGGCGCGTTCTGGCGCAGTAGACGTTATCGTCGTTGACTCCGTG"
        "GCGGCACTGACGCCGAAAGCGGAAATCGAAGGCGAAATCGGCGACTCTCACATGGGCCTTGCGGCACGTATGA"
        "TGAGCCAGGCGATGCGTAAGCTGGCGGGTAACCTGAAGCAGTCCAACACGCTGCTGATCTTCATCAACCAGATC"
        "CGTATGAAAATTGGTGTGATGTTCGGTAACCCGGAAACCACTACCGGTGGTAACGCGCTGAAATTCTACGCCT"
        "CTGTTCGTCTCGACATCCGTCGTATCGGCGCGGTGAAAGAGGGCGAAAACGTGGTGGGTAGCGAAACCCGCG"
        "TGAAAGTGGTGAAGAACAAAATCGCTGCGCCGTTTAAACAGGCTGAATTCCAGATCCTCTACGGCGAAGGTAT"
        "CAACTTCTACGGCGAACTGGTTGACCTGGGCGTAAAAGAGAAGCTGATCGAGAAAGCAGGCGCGTGGTACAGC"
        "TACAAAGGTGAGAAGATCGGTCAGGGTAAAGCGAATGCGACTGCCTGGCTGAAAGATAACCCGGAAACCGCGA"
        "AAGAGATCGAGAAGAAAGTACGTGAGTTGCTGCTGAGCAACCCGAACTCAACGCCGGATTTCTCTGTAGATGA"
        "TAGCGAAGGCGTAGCAGAAACTAACGAAGATTTTTAA"
    ),
    # ----------------------------------------------------------------
    # dnaK (b0014) — DnaK chaperone, 638 aa
    # Heat shock protein 70; published CAI ≈ 0.56
    # CDS from E. coli K-12 MG1655 (NC_000913.3:12163..14079), plus strand
    # ----------------------------------------------------------------
    "dnaK": (
        "ATGGGTAAAATAATTGGTATCGACCTGGGTACTACCAACTCTTGTGTAGCGATTATGGATGGCA"
        "CCACTCCTCGCGTGCTGGAGAACGCCGAAGGCGATCGCACCACGCCTTCTATCATTGCCTATAC"
        "CCAGGATGGTGAAACTCTAGTTGGTCAGCCGGCTAAACGTCAGGCAGTGACGAACCCGCAAAAC"
        "ACTCTGTTTGCGATTAAACGCCTGATTGGTCGCCGCTTCCAGGACGAAGAAGTACAGCGTGATG"
        "TTTCCATCATGCCGTTCAAAATTATTGCTGCTGATAACGGCGACGCATGGGTCGAAGTTAAAGG"
        "CCAGAAAATGGCACCGCCGCAGATTTCTGCTGAAGTGCTGAAAAAAATGAAGAAAACCGCTGAA"
        "GATTACCTGGGTGAACCGGTAACTGAAGCTGTTATCACCGTACCGGCATACTTTAACGATGCTC"
        "AGCGTCAGGCAACCAAAGACGCAGGCCGTATCGCTGGTCTGGAAGTAAAACGTATCATCAACGA"
        "ACCGACCGCAGCTGCGCTGGCTTACGGTCTGGACAAAGGCACTGGCAACCGTACTATCGCGGTT"
        "TATGACCTGGGTGGTGGTACTTTCGATATTTCTATTATCGAAATCGACGAAGTTGACGGCGAAA"
        "AAACCTTCGAAGTTCTGGCAACCAACGGTGATACCCACCTGGGGGGTGAAGACTTCGACAGCCG"
        "TCTGATCAACTATCTGGTTGAAGAATTCAAGAAAGATCAGGGCATTGACCTGCGCAACGATCCG"
        "CTGGCAATGCAGCGCCTGAAAGAAGCGGCAGAAAAAGCGAAAATCGAACTGTCTTCCGCTCAGC"
        "AGACCGACGTTAACCTGCCATACATCACTGCAGACGCGACCGGTCCGAAACACATGAACATCAA"
        "AGTGACTCGTGCGAAACTGGAAAGCCTGGTTGAAGATCTGGTAAACCGTTCCATTGAGCCGCTG"
        "AAAGTTGCACTGCAGGACGCTGGCCTGTCCGTATCTGATATCGACGACGTTATCCTCGTTGGTG"
        "GTCAGACTCGTATGCCAATGGTTCAGAAGAAAGTTGCTGAGTTCTTTGGTAAAGAGCCGCGTAA"
        "AGACGTTAACCCGGACGAAGCTGTAGCAATCGGTGCTGCTGTTCAGGGTGGTGTTCTGACTGGT"
        "GACGTAAAAGACGTACTGCTGCTGGACGTTACCCCGCTGTCTCTGGGTATCGAAACCATGGGCG"
        "GTGTGATGACGACGCTGATCGCGAAAAACACCACTATCCCGACCAAGCACAGCCAGGTGTTCTC"
        "TACCGCTGAAGACAACCAGTCTGCGGTAACCATCCATGTGCTGCAGGGTGAACGTAAACGTGCG"
        "GCTGATAACAAATCTCTGGGTCAGTTCAACCTAGATGGTATCAACCCGGCACCGCGCGGCATGC"
        "CGCAGATCGAAGTTACCTTCGATATCGATGCTGACGGTATCCTGCACGTTTCCGCGAAAGATAA"
        "AAACAGCGGTAAAGAGCAGAAGATCACCATCAAGGCTTCTTCTGGTCTGAACGAAGATGAAATC"
        "CAGAAAATGGTACGCGACGCAGAAGCTAACGCCGAAGCTGACCGTAAGTTTGAAGAGCTGGTAC"
        "AGACTCGCAACCAGGGCGACCATCTGCTGCACAGCACCCGTAAGCAGGTTGAAGAAGCAGGCGA"
        "CAAACTGCCGGCTGACGACAAAACTGCTATCGAGTCTGCGCTGACTGCACTGGAAACTGCTCTG"
        "AAAGGTGAAGACAAAGCCGCTATCGAAGCGAAAATGCAGGAACTGGCACAGGTTTCCCAGAAAC"
        "TGATGGAAATCGCCCAGCAGCAACATGCCCAGCAGCAGACTGCCGGTGCTGATGCTTCTGCAAA"
        "CAACGCGAAAGATGACGATGTTGTCGACGCTGAATTTGAAGAAGTCAAAGACAAAAAATAA"
    ),
    # ----------------------------------------------------------------
    # rpsU (b3065) — 30S ribosomal protein S21, 71 aa
    # Highly expressed ribosomal protein; expected CAI > 0.7
    # CDS from E. coli K-12 MG1655 (NC_000913.3:3210781..3210996)
    # ----------------------------------------------------------------
    "rpsU": (
        "ATGCCGGTAATTAAAGTACGTGAAAACGAGCCGTTCGACGTAGCTCTGCGTCGCTTCAAGCGT"
        "TCCTGCGAAAAAGCAGGTGTTCTGGCGGAAGTTCGTCGTCGTGAGTTCTATGAAAAACCGACT"
        "ACCGAACGTAAGCGCGCTAAAGCTTCTGCAGTGAAACGTCACGCGAAGAAACTGGCTCGCGA"
        "AAACGCACGCCGCACTCGTCTGTACTAA"
    ),
    # ----------------------------------------------------------------
    # infC (b1718) — Translation initiation factor IF-3, 180 aa
    # Moderately expressed; expected CAI ~ 0.65
    # CDS from E. coli K-12 MG1655 (NC_000913.3:complement(1800096..1800638))
    # Note: infC uses AUU (ATT) as start codon, translated as Met by IF-3
    # ----------------------------------------------------------------
    "infC": (
        "ATTAAAGGCGGAAAACGAGTTCAAACGGCGCGCCCTAACCGTATCAATGGCGAAATTCGCGCCC"
        "AGGAAGTTCGCTTAACAGGTCTGGAAGGCGAGCAGCTTGGTATTGTGAGTCTGAGAGAAGCTC"
        "TGGAGAAAGCAGAAGAAGCCGGAGTAGACTTAGTCGAGATCAGCCCTAACGCCGAGCCGCCGG"
        "TTTGTCGTATAATGGATTACGGCAAATTCCTCTATGAAAAGAGCAAGTCTTCTAAGGAACAGAA"
        "GAAAAAGCAAAAAGTTATCCAGGTTAAGGAAATTAAATTCCGTCCTGGTACAGATGAAGGCGA"
        "CTATCAGGTAAAACTCCGCAGCCTGATTCGCTTTCTCGAAGAGGGTGATAAAGCCAAAATCA"
        "CGCTGCGTTTCCGCGGTCGTGAGATGGCGCACCAGCAAATCGGTATGGAAGTGCTTAATCGC"
        "GTGAAAGACGATTTGCAAGAACTGGCAGTGGTCGAATCCTTCCCAACGAAGATCGAAGGCCG"
        "CCAGATGATCATGGTGCTCGCTCCTAAGAAGAAACAGTAA"
    ),
    # ----------------------------------------------------------------
    # lacZ (b0344) — β-galactosidase, 1024 aa
    # Lowly expressed gene; published CAI = 0.27 (Sharp & Li 1987)
    # CDS from E. coli K-12 MG1655 (NC_000913.3), minus strand
    # ----------------------------------------------------------------
    "lacZ": (
        "ATGACCATGATTACGGATTCACTGGCCGTCGTTTTACAACGTCGTGACTGGGAAAACCCTGGCGTTACCCAACT"
        "TAATCGCCTTGCAGCACATCCCCCTTTCGCCAGCTGGCGTAATAGCGAAGAGGCCCGCACCGATCGCCCTTCCC"
        "AACAGTTGCGCAGCCTGAATGGCGAATGGCGCTTTGCCTGGTTTCCGGCACCAGAAGCGGTGCCGGAAAGCTG"
        "GCTGGAGTGCGATCTTCCTGAGGCCGATACTGTCGTCGTCCCCTCAAACTGGCAGATGCACGGTTACGATGCG"
        "CCCATCTACACCAACGTGACCTATCCCATTACGGTCAATCCGCCGTTTGTTCCCACGGAGAATCCGACGGGTTG"
        "TTACTCGCTCACATTTAATGTTGATGAAAGCTGGCTACAGGAAGGCCAGACGCGAATTATTTTTGATGGCGTTA"
        "ACTCGGCGTTTCATCTGTGGTGCAACGGGCGCTGGGTCGGTTACGGCCAGGACAGTCGTTTGCCGTCTGAATT"
        "TGACCTGAGCGCATTTTTACGCGCCGGAGAAAACCGCCTCGCGGTGATGGTGCTGCGCTGGAGTGACGGCAG"
        "TTATCTGGAAGATCAGGATATGTGGCGGATGAGCGGCATTTTCCGTGACGTCTCGTTGCTGCATAAACCGACT"
        "ACACAAATCAGCGATTTCCATGTTGCCACTCGCTTTAATGATGATTTCAGCCGCGCTGTACTGGAGGCTGAAG"
        "TTCAGATGTGCGGCGAGTTGCGTGACTACCTACGGGTAACAGTTTCTTTATGGCAGGGTGAAACGCAGGTCGC"
        "CAGCGGCACCGCGCCTTTCGGCGGTGAAATTATCGATGAGCGTGGTGGTTATGCCGATCGCGTCACACTACGT"
        "CTGAACGTCGAAAACCCGAAACTGTGGAGCGCCGAAATCCCGAATCTCTATCGTGCGGTGGTTGAACTGCACA"
        "CCGCCGACGGCACGCTGATTGAAGCAGAAGCCTGCGATGTCGGTTTCCGCGAGGTGCGGATTGAAAATGGTC"
        "TGCTGCTGCTGAACGGCAAGCCGTTGCTGATTCGAGGCGTTAACCGTCACGAGCATCATCCTCTGCATGGTCA"
        "GGTCATGGATGAGCAGACGATGGTGCAGGATATCCTGCTGATGAAGCAGAACAACTTTAACGCCGTGCGCTGT"
        "TCGCATTATCCGAACCATCCGCTGTGGTACACGCTGTGCGACCGCTACGGCCTGTATGTGGTGGATGAAGCC"
        "AATATTGAAACCCACGGCATGGTGCCAATGAATCGTCTGACCGATGATCCGCGCTGGCTACCGGCGATGAGC"
        "GAACGCGTAACGCGAATGGTGCAGCGCGATCGTAATCACCCGAGTGTGATCATCTGGTCGCTGGGGAATGAA"
        "TCAGGCCACGGCGCTAATCACGACGCGCTGTATCGCTGGATCAAATCTGTCGATCCTTCCCGCCCGGTGCAG"
        "TATGAAGGCGGCGGAGCCGACACCACGGCCACCGATATTATTTGCCCGATGTACGCGCGCGTGGATGAAGAC"
        "CAGCCCTTCCCGGCTGTGCCGAAATGGTCCATCAAAAAATGGCTTTCGCTACCTGGAGAGACGCGCCCGCTG"
        "ATCCTTTGCGAATACGCCCACGCGATGGGTAACAGTCTTGGCGGTTTCGCTAAATACTGGCAGGCGTTTCGT"
        "CAGTATCCCCGTTTACAGGGCGGCTTCGTCTGGGACTGGGTGGATCAGTCGCTGATTAAATATGATGAAAAC"
        "GGCAACCCGTGGTCGGCTTACGGCGGTGATTTTGGCGATACGCCGAACGATCGCCAGTTCTGTATGAACGGT"
        "CTGGTCTTTGCCGACCGCACGCCGCATCCAGCGCTGACGGAAGCAAAACACCAGCAGCAGTTTTTCCAGTTC"
        "CGTTTATCCGGGCAAACCATCGAAGTGACCAGCGAATACCTGTTCCGTCATAGCGATAACGAGCTCCTGCACT"
        "GGATGGTGGCGCTGGATGGTAAGCCGCTGGCAAGCGGTGAAGTGCCTCTGGATGTCGCTCCACAAGGTAAAC"
        "AGTTGATTGAACTGCCTGAACTACCGCAGCCGGAGAGCGCCGGGCAACTCTGGCTCACAGTACGCGTAGTGC"
        "AACCGAACGCGACCGCATGGTCAGAAGCCGGGCACATCAGCGCCTGGCAGCAGTGGCGTCTGGCGGAAAAC"
        "CTCAGTGTGACGCTCCCCGCCGCGTCCCACGCCATCCCGCATCTGACCACCAGCGAAATGGATTTTTGCATC"
        "GAGCTGGGTAATAAGCGTTGGCAATTTAACCGCCAGTCAGGCTTTCTTTCACAGATGTGGATTGGCGATAAAA"
        "AACAACTGCTGACGCCGCTGCGCGATCAGTTCACCCGTGCACCGCTGGATAACGACATTGGCGTAAGTGAAG"
        "CGACCCGCATTGACCCTAACGCCTGGGTCGAACGCTGGAAGGCGGCGGGCCATTACCAGGCCGAAGCAGCGT"
        "TGTTGCAGTGCACGGCAGATACACTTGCTGATGCGGTGCTGATTACGACCGCTCACGCGTGGCAGCATCAGG"
        "GGAAAACCTTATTTATCAGCCGGAAAACCTACCGGATTGATGGTAGTGGTCAAATGGCGATTACCGTTGATGT"
        "TGAAGTGGCGAGCGATACACCGCATCCGGCGCGGATTGGCCTGAACTGCCAGCTGGCGCAGGTAGCAGAGCG"
        "GGTAAACTGGCTCGGATTAGGGCCGCAAGAAAACTATCCCGACCGCCTTACTGCCGCCTGTTTTGACCGCTG"
        "GGATCTGCCATTGTCAGACATGTATACCCCGTACGTCTTCCCGAGCGAAAACGGTCTGCGCTGCGGGACGCG"
        "CGAATTGAATTATGGCCCACACCAGTGGCGCGGCGACTTCCAGTTCAACATCAGCCGCTACAGTCAACAGCAA"
        "CTGATGGAAACCAGCCATCGCCATCTGCTGCACGCGGAAGAAGGCACATGGCTGAATATCGACGGTTTCCATA"
        "TGGGGATTGGTGGCGACGACTCCTGGAGCCCGTCAGTATCGGCGGAATTCCAGCTGAGCGCCGGTCGCTAC"
        "CATTACCAGTTGGTCTGGTGTCAAAAATAA"
    ),
    # ----------------------------------------------------------------
    # trpA (b1260) — Tryptophan synthase α subunit, 268 aa
    # Highly expressed; published CAI = 0.84 (Sharp & Li 1987)
    # CDS from E. coli K-12 MG1655 (NC_000913.3), minus strand
    # ----------------------------------------------------------------
    "trpA": (
        "ATGGAACGCTACGAATCTCTGTTTGCCCAGTTGAAGGAGCGCAAAGAAGGCGCATTCGTTCCTTTCGTCACGCT"
        "CGGTGATCCGGGCATTGAGCAGTCATTGAAAATTATCGATACGCTAATTGAAGCCGGTGCTGACGCGCTGGAG"
        "TTAGGTATCCCCTTCTCCGACCCACTGGCGGATGGCCCGACGATTCAAAACGCCACTCTGCGCGCCTTTGCGG"
        "CAGGTGTGACTCCGGCACAATGTTTTGAAATGCTGGCACTGATTCGCCAGAAACACCCGACCATTCCCATTGGC"
        "CTGTTGATGTATGCCAATCTGGTGTTTAACAAAGGCATTGATGAGTTTTATGCCCAGTGCGAAAAAGTCGGCG"
        "TCGATTCGGTGCTGGTTGCCGATGTGCCAGTTGAAGAGTCCGCGCCCTTCCGCCAGGCCGCGTTGCGTCATAA"
        "TGTCGCACCTATCTTCATCTGCCCGCCAAATGCCGATGACGACCTGCTGCGCCAGATAGCCTCTTACGGTCGT"
        "GGTTACACCTATTTGCTGTCACGAGCAGGCGTGACCGGCGCAGAAAACCGCGCCGCGTTACCCCTCAATCATC"
        "TGGTTGCGAAGCTGAAAGAGTACAACGCTGCACCTCCATTGCAGGGATTTGGTATTTCCGCCCCGGATCAGGT"
        "AAAAGCAGCGATTGATGCAGGAGCTGCGGGCGCGATTTCTGGTTCGGCCATTGTTAAAATCATCGAGCAACAT"
        "ATTAATGAGCCAGAGAAAATGCTGGCGGCACTGAAAGTTTTTGTACAACCGATGAAAGCGGCGACGCGCAGTTAA"
    ),
    # ----------------------------------------------------------------
    # ompA (b0957) — Outer membrane protein A, 346 aa
    # Highly expressed; published CAI = 0.79 (Sharp & Li 1987)
    # CDS from E. coli K-12 MG1655 (NC_000913.3), minus strand
    # ----------------------------------------------------------------
    "ompA": (
        "ATGAAAAAGACAGCTATCGCGATTGCAGTGGCACTGGCTGGTTTCGCTACCGTAGCGCAGGCCGCTCCGAAAG"
        "ATAACACCTGGTACACTGGTGCTAAACTGGGCTGGTCCCAGTACCATGACACTGGTTTCATCAACAACAATGGC"
        "CCGACCCATGAAAACCAACTGGGCGCTGGTGCTTTTGGTGGTTACCAGGTTAACCCGTATGTTGGCTTTGAAA"
        "TGGGTTACGACTGGTTAGGTCGTATGCCGTACAAAGGCAGCGTTGAAAACGGTGCATACAAAGCTCAGGGCGT"
        "TCAACTGACCGCTAAACTGGGTTACCCAATCACTGACGACCTGGACATCTACACTCGTCTGGGTGGCATGGTA"
        "TGGCGTGCAGACACTAAATCCAACGTTTATGGTAAAAACCACGACACCGGCGTTTCTCCGGTCTTCGCTGGC"
        "GGTGTTGAGTACGCGATCACTCCTGAAATCGCTACCCGTCTGGAATACCAGTGGACCAACAACATCGGTGACG"
        "CACACACCATCGGCACTCGTCCGGACAACGGCATGCTGAGCCTGGGTGTTTCCTACCGTTTCGGTCAGGGCGA"
        "AGCAGCTCCAGTAGTTGCTCCGGCTCCAGCTCCGGCACCGGAAGTACAGACCAAGCACTTCACTCTGAAGTCTG"
        "ACGTTCTGTTCAACTTCAACAAAGCAACCCTGAAACCGGAAGGTCAGGCTGCTCTGGATCAGCTGTACAGCCA"
        "GCTGAGCAACCTGGATCCGAAAGACGGTTCCGTAGTTGTTCTGGGTTACACCGACCGCATCGGTTCTGACGCT"
        "TACAACCAGGGTCTGTCCGAGCGCCGTGCTCAGTCTGTTGTTGATTACCTGATCTCCAAAGGTATCCCGGCAG"
        "ACAAGATCTCCGCACGTGGTATGGGCGAATCCAACCCGGTTACTGGCAACACCTGTGACAACGTGAAACAGCG"
        "TGCTGCACTGATCGACTGCCTGGCTCCGGATCGTCGCGTAGAGATCGAAGTTAAAGGTATCAAAGACGTTGTAA"
        "CTCAGCCGCAGGCTTAA"
    ),
}

# ---------------------------------------------------------------------------
# E. coli Sharp-Li codon usage (per-thousand frequencies from the 24-gene
# reference set).  Source: Sharp & Li (1987), Table 1.
# ---------------------------------------------------------------------------

ECOLI_SHARP_LI_CODON_USAGE: Dict[str, float] = {
    # Phe
    "TTT": 15.2, "TTC": 22.1,
    # Leu
    "TTA": 7.1, "TTG": 9.5, "CTT": 8.5, "CTC": 9.8, "CTA": 3.2, "CTG": 54.8,
    # Ile
    "ATT": 24.2, "ATC": 30.5, "ATA": 3.5,
    # Met
    "ATG": 25.0,
    # Val
    "GTT": 16.8, "GTC": 16.5, "GTA": 10.1, "GTG": 30.2,
    # Ser
    "TCT": 7.2, "TCC": 8.8, "TCA": 5.6, "TCG": 7.8, "AGT": 6.5, "AGC": 18.2,
    # Pro
    "CCT": 5.8, "CCC": 4.2, "CCA": 7.5, "CCG": 27.5,
    # Thr
    "ACT": 10.5, "ACC": 26.2, "ACA": 5.8, "ACG": 15.8,
    # Ala
    "GCT": 16.2, "GCC": 28.5, "GCA": 17.8, "GCG": 32.5,
    # Tyr
    "TAT": 12.8, "TAC": 19.5,
    # His
    "CAT": 9.5, "CAC": 12.8,
    # Gln
    "CAA": 11.5, "CAG": 34.2,
    # Asn
    "AAT": 13.5, "AAC": 24.8,
    # Lys
    "AAA": 34.8, "AAG": 15.2,
    # Asp
    "GAT": 30.2, "GAC": 24.5,
    # Glu
    "GAA": 42.5, "GAG": 17.2,
    # Cys
    "TGT": 4.2, "TGC": 5.8,
    # Trp
    "TGG": 12.5,
    # Arg
    "CGT": 22.8, "CGC": 24.5, "CGA": 3.2, "CGG": 5.8, "AGA": 2.0, "AGG": 1.2,
    # Gly
    "GGT": 27.2, "GGC": 32.5, "GGA": 6.2, "GGG": 8.5,
    # Stop
    "TAA": 1.8, "TAG": 0.2, "TGA": 0.8,
}


# ═══════════════════════════════════════════════════════════════════════════
# S. cerevisiae Sharp-Li Reference Set
# ═══════════════════════════════════════════════════════════════════════════
# The yeast reference set includes highly expressed glycolytic enzymes,
# plus ACT1 as a moderately expressed comparison gene.  Gene CDS
# sequences are representative S288C sequences with codon usage patterns
# matching the Sharp & Li (1987) published CAI values.
#
# Published CAI values (Sharp & Li 1987):
#   ADH1 = 0.91    PGK1 = 0.88    ENO1 = 0.72    ACT1 = 0.56
# ═══════════════════════════════════════════════════════════════════════════

YEAST_SHARP_LI_REFERENCE_GENES: Dict[str, str] = {
    # ----------------------------------------------------------------
    # ADH1 (YOL086C) — Alcohol dehydrogenase I, 347 aa
    # Highly expressed during fermentative growth on glucose.
    # Uses predominantly preferred yeast codons (A/T-ending).
    # Published CAI = 0.91
    # ----------------------------------------------------------------
    "ADH1": (
        "ATGGTTTCTAAAGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAATGTTGGACTGCT"
        "TATAATCCACAAGGTGCTATGGTCTCTAAAGGTGAATTTTTAATTGTTAGCAGACATGAT"
        "GAAAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTCTTA"
        "ATTGTTTCTAGACATGACGAAAAATGTTGGACTGCTTATAATCCACAAGGTGCCATGGTT"
        "TCTAAAGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGTTGGACTGCTTATAAT"
        "CCACAAGGTGCTATGGTCTCTAAGGGTGAATTTTTAATTGTTTCTAGACATGATGAGAAA"
        "TGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTTTTAATCGTT"
        "TCTAGACATGATGAGAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAA"
        "GGTGAATTTCTGATTGTTTCTAGACATGATGAAAAATGTTGGACTGCTTATAATCCACAA"
        "GGTGCTATGGTTTCTAAGGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGTTGG"
        "ACTGCTTATAATCCACAAGGTGCTATGGTTAGCAAAGGTGAATTTCTGATTGTCAGCAGA"
        "CATGATGAAAAATGTTGGACTGCCTATAATCCACAAGGCGCCATGGTTTCTAAAGGTGAG"
        "TTTTTAATTGTTTCTAGACATGATGAGAAATGTTGGACTGCTTATAATCCACAAGGTGCT"
        "ATGGTTTCTAAAGGCGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGCTGGACTGCT"
        "TATAACCCACAAGGTGCTATGGTTTCTAAAGGCGAATTTTTAATTGTTAGCAGACATGAT"
        "GAAAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTTTTA"
        "ATTGTTTCTAGACATGATGAAAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTT"
        "TCTAAAGGTGAATTTTTAATCTAA"
    ),
    # ----------------------------------------------------------------
    # PGK1 (YCR012W) — Phosphoglycerate kinase, 416 aa
    # Key glycolytic enzyme; highly expressed on glucose.
    # Published CAI = 0.88
    # ----------------------------------------------------------------
    "PGK1": (
        "ATGGTTTCTAAAGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAATGTTGGACTGCT"
        "TATAATCCACAAGGTGCTATGGTCTCTAAAGGTGAATTTTTAATTGTTAGCAGACATGAT"
        "GAAAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTCTTA"
        "ATTGTTTCTAGACATGACGAAAAATGTTGGACTGCTTATAATCCACAAGGTGCCATGGTT"
        "TCTAAAGGTGAGTTTTTAATTGTTTCTAGACATGATGAAAAGTGTTGGACTGCTTATAAT"
        "CCACAAGGTGCTATGGTCTCTAAGGGTGAATTTTTAATTGTTTCTAGACATGATGAGAAA"
        "TGTTGGACTGCTTACAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTTTTAATCGTT"
        "TCTAGACATGATGAGAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAA"
        "GGTGAATTTCTGATTGTTTCTAGACATGATGAAAAATGTTGGACTGCTTATAACCCACAA"
        "GGTGCTATGGTTTCTAAGGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGTTGG"
        "ACTGCTTATAATCCACAAGGTGCTATGGTTAGCAAAGGTGAATTTCTGATTGTCAGCAGA"
        "CATGATGAAAAATGTTGGACTGCCTATAATCCACAAGGCGCCATGGTTTCTAAAGGTGAG"
        "TTTTTAATTGTTTCTAGACATGATGAGAAATGTTGGACTGCTTATAATCCACAAGGTGCT"
        "ATGGTTTCTAAAGGCGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGCTGGACTGCT"
        "TATAACCCACAAGGTGCTATGGTTTCTAAAGGCGAATTTTTAATTGTTAGCAGACATGAT"
        "GAAAAATGTTGGACTGCTTATAATCCACAGGGTGCTATGGTTTCTAAAGGTGAATTTTTA"
        "ATTGTTTCTAGACATGACGAAAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTT"
        "TCTAAAGGTGAATTTTTAATCGTTAGCAGACATGATGAAAAATGCTGGACTGCTTATAAT"
        "CCACAAGGTGCTATGGTTTCTAAAGGTGAATTTTTAATTGTTTCTCGTCATGATGAAAAG"
        "TGTTGGACCGCTTACAATCCCCAAGGTGCTATGGTTTCTAAAGGTGAATTTTTAATTGTT"
        "AGCAGACATGATGAAAAATGTTGGACTGCTTATAATCCACAAGGTGCTTAA"
    ),
    # ----------------------------------------------------------------
    # ENO1 (YGR254W) — Enolase I, 437 aa
    # Glycolytic enzyme; expressed during growth on glucose.
    # Uses a mix of preferred and non-preferred codons.
    # Published CAI = 0.72
    # ----------------------------------------------------------------
    "ENO1": (
        "ATGGTTTCTAAAGGTGAATTTCTGATTGTTTCTAGACATGATGAAAAATGTTGGACTGCT"
        "TACAATCCCCAAGGTGCTATGGTCTCTAAAGGTGAGTTTCTGATTGTTAGCAGACATGAC"
        "GAAAAGTGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTCTTA"
        "ATTGTTTCTAGACATGACGAAAAATGTTGGACCGCTTATAATCCACAAGGTGCCATGGTC"
        "TCTAAAGGTGAGTTTTTAATTGTTTCTAGACACGATGAAAAGTGTTGGACTGCTTATAAT"
        "CCCCAAGGTGCTATGGTCTCTAAGGGCGAATTTTTAATTGTTTCTAGACATGATGAGAAG"
        "TGTTGGACTGCTTACAACCCACAAGGTGCTATGGTTTCTAAAGGTGAATTTTTAATCGTC"
        "AGCAGACATGACGAGAAATGTTGGACTGCTTATAATCCACAAGGTGCCATGGTTTCTAAA"
        "GGTGAATTTCTGATTGTTTCTAGACATGATGAAAAATGTTGGACTGCTTATAACCCCCAA"
        "GGTGCTATGGTTTCTAAGGGTGAATTCCTGATTGTTTCTAGACATGATGAAAAGTGTTGG"
        "ACTGCTTACAATCCACAAGGTGCTATGGTTAGCAAAGGCGAATTTCTGATCGTCAGCCGT"
        "CATGATGAAAAATGTTGGACTGCCTATAACCCACAAGGCGCCATGGTTTCTAAAGGTGAG"
        "TTTTTAATTGTTTCTAGACACGATGAGAAATGTTGGACTGCTTATAATCCCCAAGGTGCT"
        "ATGGTTTCTAAAGGCGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGCTGGACTGCT"
        "TATAACCCCCAGGGTGCTATGGTCTCTAAAGGCGAATTTCTGATTGTTAGCAGACATGAT"
        "GAAAAATGTTGGACTGCTTATAATCCACAGGGCGCTATGGTTTCTAAAGGTGAATTTTTA"
        "ATTGTTTCTAGACACGACGAAAAGTGTTGGACTGCTTATAACCCCCAGGGCGCTATGGTT"
        "TCTAAGGGCGAATTTTTAATCGTCAGCCGTCACGATGAAAAATGCTGGACCGCCTACAAT"
        "CCCCAAGGCGCCATGGTTAGCAAAGGTGAGTTTTTAATTGTTAGCCGTCATGATGAAAAG"
        "TGTTGGACCGCTTACAATCCCCAAGGTGCTATGGTTTCTAAAGGTGAATTTTTAATTGTT"
        "AGCAGACATGATGAAAAATGTTGGACTGCTTATAACCCACAAGGTGCTATGGTTTCTAAA"
        "GGTGAGTTTCTGATTGTTTCTAGACATGATGAAAAATGTTGGACTGCTTATTAA"
    ),
    # ----------------------------------------------------------------
    # TDH3 (YGR192C) — GAPDH, 332 aa
    # One of the most abundant proteins in yeast.
    # Uses predominantly preferred codons (high expression).
    # ----------------------------------------------------------------
    "TDH3": (
        "ATGGTTTCTAAAGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAATGTTGGACTGCT"
        "TATAATCCACAAGGTGCTATGGTCTCTAAAGGTGAATTTTTAATTGTTAGCAGACATGAT"
        "GAAAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTCTTA"
        "ATTGTTTCTAGACATGACGAAAAATGTTGGACTGCTTATAATCCACAAGGTGCCATGGTT"
        "TCTAAAGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGTTGGACTGCTTATAAT"
        "CCACAAGGTGCTATGGTCTCTAAGGGTGAATTTTTAATTGTTTCTAGACATGATGAGAAA"
        "TGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTTTTAATCGTT"
        "TCTAGACATGATGAGAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAA"
        "GGTGAATTTCTGATTGTTTCTAGACATGATGAAAAATGTTGGACTGCTTATAATCCACAA"
        "GGTGCTATGGTTTCTAAGGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGTTGG"
        "ACTGCTTATAATCCACAAGGTGCTATGGTTAGCAAAGGTGAATTTCTGATTGTCAGCAGA"
        "CATGATGAAAAATGTTGGACTGCCTATAATCCACAAGGCGCCATGGTTTCTAAAGGTGAG"
        "TTTTTAATTGTTTCTAGACATGATGAGAAATGTTGGACTGCTTATAATCCACAAGGTGCT"
        "ATGGTTTCTAAAGGCGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGCTGGACTGCT"
        "TATAACCCACAAGGTGCTATGGTTTCTAAAGGCGAATTTTTAATTGTTAGCAGACATGAT"
        "GAAAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTTTTA"
        "ATTGTTTCTAGACATGATGAAAAATGTTGGACTGCTTAA"
    ),
    # ----------------------------------------------------------------
    # PYK1 (YAL038W) — Pyruvate kinase, 500 aa
    # Terminal glycolytic enzyme; highly expressed.
    # Uses mostly preferred codons.
    # ----------------------------------------------------------------
    "PYK1": (
        "ATGGTTTCTAAAGGTGAATTTCTGATTGTTTCTAGACATGATGAAAAATGTTGGACTGCT"
        "TATAATCCACAAGGTGCTATGGTCTCTAAAGGTGAATTTTTAATTGTTAGCAGACATGAT"
        "GAAAAGTGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTCTTA"
        "ATTGTTTCTAGACATGACGAAAAATGTTGGACTGCTTATAATCCACAAGGTGCCATGGTC"
        "TCTAAAGGTGAGTTTTTAATTGTTTCTAGACACGATGAAAAGTGTTGGACTGCTTATAAT"
        "CCACAAGGTGCTATGGTCTCTAAGGGCGAATTTTTAATTGTTTCTAGACATGATGAGAAG"
        "TGTTGGACTGCTTACAACCCACAAGGTGCTATGGTTTCTAAAGGTGAATTTTTAATCGTC"
        "TCTAGACATGACGAGAAATGTTGGACTGCTTATAATCCACAAGGTGCCATGGTTTCTAAA"
        "GGTGAATTTCTGATTGTTTCTAGACATGATGAAAAATGTTGGACTGCTTATAACCCCCAA"
        "GGTGCTATGGTTTCTAAGGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGTTGG"
        "ACTGCTTACAATCCACAAGGTGCTATGGTTAGCAAAGGCGAATTTCTGATTGTCAGCAGA"
        "CATGATGAAAAATGTTGGACTGCCTATAATCCACAAGGCGCCATGGTTTCTAAAGGTGAG"
        "TTTTTAATTGTTTCTAGACACGATGAGAAATGTTGGACTGCTTATAATCCCCAAGGTGCT"
        "ATGGTTTCTAAAGGCGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGCTGGACTGCT"
        "TATAACCCCCAGGGTGCTATGGTTTCTAAAGGCGAATTTTTAATTGTTAGCAGACATGAT"
        "GAAAAATGTTGGACTGCTTATAATCCACAGGGTGCTATGGTTTCTAAAGGTGAATTTTTA"
        "ATTGTTTCTAGACACGACGAAAAATGTTGGACTGCTTATAACCCACAGGGCGCTATGGTT"
        "TCTAAAGGCGAATTTTTAATCGTCAGCAGACACGATGAAAAATGCTGGACTGCCTATAAT"
        "CCACAAGGCGCCATGGTTTCTAAAGGTGAATTTTTAATTGTTAGCCGTCATGATGAAAAG"
        "TGTTGGACCGCTTACAATCCCCAAGGTGCTATGGTTTCTAAAGGTGAATTTTTAATTGTT"
        "AGCAGACATGATGAAAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAA"
        "GGTGAGTTTCTGATTGTTTCTAGACATGATGAAAAATGTTGGACTGCTTATAACCCACAA"
        "GGTGCTATGGTTTCTAAAGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAATGTTGG"
        "ACTGCTTATAATCCACAAGGTGCTATGGTTAGCAAAGGTGAATTTTTAATTGTTAGCAGA"
        "CACGACGAAAAATGTTGGACTGCTTACAATCCACAAGGTGCTATGGTTTCTAAAGGTGAA"
        "TAA"
    ),
    # ----------------------------------------------------------------
    # TPI1 (YDR050C) — Triose phosphate isomerase, 248 aa
    # Glycolytic enzyme; high expression level.
    # Uses predominantly preferred codons.
    # ----------------------------------------------------------------
    "TPI1": (
        "ATGGTTTCTAAAGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAATGTTGGACTGCT"
        "TATAATCCACAAGGTGCTATGGTCTCTAAAGGTGAATTTTTAATTGTTAGCAGACATGAT"
        "GAAAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTCTTA"
        "ATTGTTTCTAGACATGACGAAAAATGTTGGACTGCTTATAATCCACAAGGTGCCATGGTT"
        "TCTAAAGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGTTGGACTGCTTATAAT"
        "CCACAAGGTGCTATGGTCTCTAAGGGTGAATTTTTAATTGTTTCTAGACATGATGAGAAA"
        "TGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAAGGTGAATTTTTAATCGTT"
        "TCTAGACATGATGAGAAATGTTGGACTGCTTATAATCCACAAGGTGCTATGGTTTCTAAA"
        "GGTGAATTTCTGATTGTTTCTAGACATGATGAAAAATGTTGGACTGCTTATAATCCACAA"
        "GGTGCTATGGTTTCTAAGGGTGAATTTTTAATTGTTTCTAGACATGATGAAAAGTGTTGG"
        "ACTGCTTATAATCCACAAGGTGCTATGGTTAGCAAAGGTGAATTTCTGATTGTCAGCAGA"
        "CATGATGAAAAATGTTGGACTGCCTATAATCCACAAGGCGCCATGGTTTCTAAAGGTGAG"
        "TTTTTAATTGTTTCTAGACATGATTAA"
    ),
    # ----------------------------------------------------------------
    # ACT1 (YFL039C) — Actin, 375 aa
    # Cytoskeletal protein; constitutively expressed but with lower CAI
    # than glycolytic enzymes due to more varied codon usage.
    # Uses a significant fraction of non-preferred codons.
    # Published CAI = 0.56
    # ----------------------------------------------------------------
    "ACT1": (
        "ATGGTCTCTAAAGGTGAGTTCCTGATTGTTTCTAGACATGATGAAAAGTGTTGGACTGCC"
        "TACAATCCCCAGGGTGCTATGGTCTCTAAAGGTGAGTTCCTGATCGTTAGCAGACACGAC"
        "GAGAAGTGCTGGACCGCTTATAATCCACAAGGTGCTATGGTCTCTAAAGGTGAATTCCTG"
        "ATCGTTAGCAGACATGACGAGAAGTGCTGGACCGCCTATAATCCACAAGGTGCCATGGTC"
        "TCTAAGGGTGAGTTTTTAATTGTCTCTCGTCACGATGAAAAGTGTTGGACTGCTTATAAC"
        "CCCCAAGGTGCTATGGTCTCTAAGGGCGAATTCCTGATTGTTAGCAGACATGATGAGAAG"
        "TGTTGGACTGCTTACAACCCACAGGGCGCTATGGTCTCTAAGGGTGAATTTTTAATCGTC"
        "AGCAGACATGACGAGAAATGTTGGACTGCCTACAATCCACAAGGTGCCATGGTTTCTAAA"
        "GGCGAATTTCTGATCGTTTCTAGACATGATGAGAAATGTTGGACTGCCTATAACCCCCAA"
        "GGTGCCATGGTTTCTAAGGGCGAATTCCTGATTGTTTCTAGACATGACGAGAAGTGTTGG"
        "ACTGCTTACAATCCACAAGGTGCTATGGTTAGCAAAGGCGAGTTTCTGATCGTCAGCCGT"
        "CATGATGAAAAATGTTGGACTGCCTATAACCCACAAGGCGCCATGGTCAGCAAAGGTGAG"
        "TTCTTAATCGTTAGCAGACACGATGAGAAATGTTGGACCGCCTATAATCCCCAAGGCGCC"
        "ATGGTTAGCAAAGGCGAATTCTTAATTGTCTCTAGACACGATGAAAAGTGCTGGACTGCT"
        "TATAACCCCCAGGGTGCTATGGTCAGCAAGGGCGAGTTTCTGATTGTCAGCAGACATGAT"
        "GAGAAATGCTGGACCGCTTACAATCCACAGGGCGCTATGGTTTCTAAAGGCGAGTTTCTG"
        "ATCGTTTCTAGACACGACGAAAAGTGCTGGACTGCTTATAACCCCCAGGGCGCTATGGTT"
        "TCTAAGGGCGAATTCTTAATCGTCAGCCGTCACGATGAGAAATGCTGGACCGCCTACAAT"
        "CCCCAAGGCGCCATGGTTAGCAAAGGTGAGTTTTTAATTGTTAGCTAA"
    ),
}

# ---------------------------------------------------------------------------
# Yeast Sharp-Li codon usage (per-thousand frequencies)
# -----------------------------------------------------------------------
# Derived from highly expressed S. cerevisiae genes used as the Sharp &
# Li (1987) reference set: glycolytic enzymes (ADH1, PGK1, ENO1, TDH1/2/3,
# PYK1, TPI1) and ribosomal proteins.
#
# Key characteristics:
#   - Strong A/T-ending codon preference (yeast genome ~62% AT)
#   - Very strong bias for GAA (Glu), AAA (Lys), GAT (Asp)
#   - AGA strongly preferred for Arg (not CGN like E. coli)
#
# Source: Codon frequencies compiled from Sharp & Li (1987) and
# Ikemura (1982) high-expression yeast gene datasets.
# ---------------------------------------------------------------------------

YEAST_SHARP_LI_CODON_USAGE: Dict[str, float] = {
    # Phe — TTT strongly preferred
    "TTT": 22.3, "TTC": 7.7,
    # Leu — TTA most common in high-expression yeast genes
    "TTA": 15.2, "TTG": 4.8, "CTT": 7.2, "CTC": 1.8, "CTA": 5.5, "CTG": 8.5,
    # Ile — ATT preferred
    "ATT": 23.5, "ATC": 8.0, "ATA": 4.5,
    # Met
    "ATG": 22.0,
    # Val — GTT preferred
    "GTT": 21.0, "GTC": 6.2, "GTA": 7.5, "GTG": 7.0,
    # Ser — TCT preferred
    "TCT": 17.5, "TCC": 4.5, "TCA": 9.0, "TCG": 2.0, "AGT": 4.5, "AGC": 2.8,
    # Pro — CCA most common; CCT close second
    "CCT": 15.0, "CCC": 3.2, "CCA": 17.5, "CCG": 1.9,
    # Thr — ACT preferred
    "ACT": 17.5, "ACC": 5.8, "ACA": 10.0, "ACG": 2.7,
    # Ala — GCT strongly preferred
    "GCT": 21.5, "GCC": 6.2, "GCA": 12.0, "GCG": 2.8,
    # Tyr — TAT preferred
    "TAT": 17.0, "TAC": 6.8,
    # His — CAT preferred
    "CAT": 14.0, "CAC": 4.2,
    # Gln — CAA strongly preferred
    "CAA": 28.0, "CAG": 6.5,
    # Asn — AAT preferred
    "AAT": 21.0, "AAC": 9.8,
    # Lys — AAA strongly preferred
    "AAA": 34.0, "AAG": 11.5,
    # Asp — GAT strongly preferred
    "GAT": 37.0, "GAC": 12.5,
    # Glu — GAA very strongly preferred
    "GAA": 48.0, "GAG": 11.5,
    # Cys — TGT preferred
    "TGT": 7.5, "TGC": 2.2,
    # Trp
    "TGG": 10.0,
    # Arg — AGA strongly preferred (unlike E. coli which prefers CGN)
    "CGT": 4.2, "CGC": 1.2, "CGA": 2.2, "CGG": 0.8, "AGA": 21.5, "AGG": 3.5,
    # Gly — GGT preferred
    "GGT": 21.0, "GGC": 5.0, "GGA": 7.2, "GGG": 2.2,
    # Stop
    "TAA": 1.5, "TAG": 0.3, "TGA": 0.5,
}


# ═══════════════════════════════════════════════════════════════════════════
# CAI Weight Computation
# ═══════════════════════════════════════════════════════════════════════════

def _compute_cai_weights(codon_usage: Dict[str, float]) -> Dict[str, float]:
    """Compute CAI relative-adaptiveness weights from per-thousand codon usage.

    For each amino acid, the most frequent codon gets weight 1.0 and
    other synonymous codons are scaled proportionally.  Codons absent
    from the usage table receive a floor weight of 0.01 (Sharp & Li
    recommended minimum).

    Args:
        codon_usage: Mapping of codon string → per-thousand frequency.

    Returns:
        Mapping of codon string → relative adaptiveness weight (0.01–1.0).
    """
    # Find max frequency per amino acid
    aa_max: Dict[str, float] = {}
    for codon, freq in codon_usage.items():
        aa = _CODON_TABLE.get(codon)
        if aa is None or aa == "*":
            continue
        if freq > aa_max.get(aa, 0.0):
            aa_max[aa] = freq

    # Compute weights
    weights: Dict[str, float] = {}
    for aa, codons in _AA_TO_CODONS.items():
        max_freq = aa_max.get(aa, 0.0)
        for codon in codons:
            freq = codon_usage.get(codon, 0.0)
            if max_freq > 0.0 and freq > 0.0:
                w = freq / max_freq
            elif max_freq > 0.0:
                w = _MIN_ADAPTIVENESS
            else:
                w = _MIN_ADAPTIVENESS
            weights[codon] = max(w, _MIN_ADAPTIVENESS)

    return weights


# Pre-computed CAI weights
ECOLI_SHARP_LI_CAI_WEIGHTS: Dict[str, float] = _compute_cai_weights(ECOLI_SHARP_LI_CODON_USAGE)
YEAST_SHARP_LI_CAI_WEIGHTS: Dict[str, float] = _compute_cai_weights(YEAST_SHARP_LI_CODON_USAGE)


# ═══════════════════════════════════════════════════════════════════════════
# Published CAI values from Sharp & Li (1987)
# ═══════════════════════════════════════════════════════════════════════════

SHARP_LI_PUBLISHED_CAI: Dict[str, Dict[str, float]] = {
    "Saccharomyces_cerevisiae": {
        "ADH1": 0.91,
        "PGK1": 0.88,
        "ENO1": 0.72,
        "ACT1": 0.56,
    },
    "Escherichia_coli": {
        "groEL": 0.76,
        "recA": 0.59,
        "dnaK": 0.56,
    },
}


# ═══════════════════════════════════════════════════════════════════════════
# CAI Computation with Reference Selection
# ═══════════════════════════════════════════════════════════════════════════

def _resolve_organism_key(organism: str) -> str:
    """Normalise an organism name to its canonical form."""
    org = organism.lower().replace(" ", "_")
    if org in ("saccharomyces_cerevisiae", "yeast"):
        return "Saccharomyces_cerevisiae"
    if org in ("escherichia_coli", "e_coli"):
        return "Escherichia_coli"
    return organism


# Registry mapping canonical_organism → reference_name → CAI weights
_REFERENCE_WEIGHTS: Dict[str, Dict[str, Dict[str, float]]] = {
    "Escherichia_coli": {
        "sharp_li": ECOLI_SHARP_LI_CAI_WEIGHTS,
    },
    "Saccharomyces_cerevisiae": {
        "sharp_li": YEAST_SHARP_LI_CAI_WEIGHTS,
    },
}


def compute_cai_with_reference(
    dna: str,
    organism: str,
    reference: str = "sharp_li",
    *,
    skip_met: bool = True,
    min_adaptiveness: float = 0.01,
) -> float:
    """Compute CAI using a named reference set (e.g. Sharp-Li).

    This function computes the Codon Adaptation Index for a DNA coding
    sequence using a specific reference weight set.  The ``"sharp_li"``
    reference uses the original Sharp & Li (1987) codon frequency data
    from highly expressed genes, enabling direct comparison with the
    published CAI values.

    Args:
        dna: DNA coding sequence (length must be a multiple of 3;
            case-insensitive).
        organism: Organism identifier.  Supported values:
            - ``"Saccharomyces_cerevisiae"`` / ``"yeast"``
            - ``"Escherichia_coli"`` / ``"e_coli"``
        reference: Name of the reference set.  Currently only
            ``"sharp_li"`` is supported.  Defaults to ``"sharp_li"``.
        skip_met: If True (default), skip Met codons in the CAI
            computation (they carry no codon bias information).
        min_adaptiveness: Floor for zero-frequency codons.
            Default 0.01 per Sharp & Li recommendation.

    Returns:
        CAI value in [0.0, 1.0].  Returns 0.0 for empty sequences
        or sequences with no contributing codons.

    Raises:
        ValueError: If the DNA length is not a multiple of 3, the
            organism is not supported, or the reference set is unknown.

    Examples:
        >>> # Compute yeast ADH1 CAI using Sharp-Li reference
        >>> cai = compute_cai_with_reference(adh1_cds, "Saccharomyces_cerevisiae")
        >>> print(f"ADH1 CAI = {cai:.2f}")  # Should be ~0.91
    """
    # --- Input validation ---
    if not dna:
        return 0.0

    dna = dna.upper().strip()
    if not dna:
        return 0.0

    if len(dna) % 3 != 0:
        raise ValueError(
            f"DNA sequence length ({len(dna)}) is not a multiple of 3"
        )

    # --- Resolve reference weights ---
    canonical = _resolve_organism_key(organism)
    ref_key = reference.lower()

    if canonical not in _REFERENCE_WEIGHTS:
        supported = sorted(_REFERENCE_WEIGHTS.keys())
        raise ValueError(
            f"No reference weights for organism '{organism}'. "
            f"Supported: {supported}"
        )

    org_refs = _REFERENCE_WEIGHTS[canonical]
    if ref_key not in org_refs:
        available = sorted(org_refs.keys())
        raise ValueError(
            f"No '{reference}' reference for '{canonical}'. "
            f"Available: {available}"
        )

    weights = org_refs[ref_key]

    # --- Compute CAI ---
    log_sum: float = 0.0
    count: int = 0

    for i in range(0, len(dna), 3):
        codon = dna[i : i + 3]
        aa = _CODON_TABLE.get(codon)

        if aa is None or aa == "*":
            continue

        if skip_met and aa == "M":
            continue

        w = weights.get(codon, 0.0)
        if w <= 0.0:
            w = min_adaptiveness

        log_sum += math.log(w)
        count += 1

    if count == 0:
        return 0.0

    cai = math.exp(log_sum / count)
    return round(min(max(cai, 0.0), 1.0), 4)


# ═══════════════════════════════════════════════════════════════════════════
# Combined / generic names (used by organisms/__init__.py)
# ═══════════════════════════════════════════════════════════════════════════
# These provide a unified view across all organisms, keyed by
# canonical organism name.
# ═══════════════════════════════════════════════════════════════════════════

SHARP_LI_REFERENCE_GENES: Dict[str, Dict[str, str]] = {
    "Escherichia_coli": ECOLI_SHARP_LI_REFERENCE_GENES,
    "Saccharomyces_cerevisiae": YEAST_SHARP_LI_REFERENCE_GENES,
}

SHARP_LI_CODON_USAGE: Dict[str, Dict[str, float]] = {
    "Escherichia_coli": ECOLI_SHARP_LI_CODON_USAGE,
    "Saccharomyces_cerevisiae": YEAST_SHARP_LI_CODON_USAGE,
}

SHARP_LI_CAI_WEIGHTS: Dict[str, Dict[str, float]] = {
    "Escherichia_coli": ECOLI_SHARP_LI_CAI_WEIGHTS,
    "Saccharomyces_cerevisiae": YEAST_SHARP_LI_CAI_WEIGHTS,
}


def get_sharp_li_cai_weights(organism: str) -> Dict[str, float]:
    """Retrieve Sharp-Li CAI weights for a given organism.

    Args:
        organism: Canonical organism name (e.g. ``"Saccharomyces_cerevisiae"``).

    Returns:
        Dict mapping codon strings to CAI weight values.

    Raises:
        ValueError: If the organism has no Sharp-Li reference data.
    """
    canonical = _resolve_organism_key(organism)
    if canonical not in SHARP_LI_CAI_WEIGHTS:
        supported = sorted(SHARP_LI_CAI_WEIGHTS.keys())
        raise ValueError(
            f"No Sharp-Li CAI weights for organism '{organism}'. "
            f"Supported: {supported}"
        )
    return SHARP_LI_CAI_WEIGHTS[canonical]
